/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.tests;

import controlador.Utils;
import java.awt.Desktop;
import java.awt.FileDialog;
import java.awt.Frame;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Pacient;
import vista.Sessio1;

/**
 *
 * @author a630703
 */
public class Cogstate extends Test {

    Frame parent;
    String valoracio;
    
    /**
     * Creates new form Cogstate
     * @param parent
     * @param pacientActual
     * @param valoracio
     */
    public Cogstate(Frame parent, Pacient pacientActual, String valoracio) {
        super(pacientActual);
        initComponents();
        
        label = "COGSTATE";
        
        this.parent = parent;
        this.valoracio = valoracio;
        
        initCogstateButtons();
    }
    
    private void initCogstateButtons() {
        File file = new File(Utils.PACIENT_DATA_PATH+this.pacientActual.getId()+File.separator+this.pacientActual.getId()+"COGSTATE_T"+valoracio+".pdf");
        if (file.exists()){
            obrePdfBtn.setEnabled(true);
        } else{
            obrePdfBtn.setEnabled(false);
        }
        file = new File(Utils.PACIENT_DATA_PATH+this.pacientActual.getId()+File.separator+this.pacientActual.getId()+"COGSTATE_T"+valoracio+".xlsx");
        if (file.exists()){
            obreExcelBtn.setEnabled(true);
        } else {
            obreExcelBtn.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        digitsDirecteScroll3 = new javax.swing.JScrollPane();
        digitsDirectePanel3 = new javax.swing.JPanel();
        jLabel165 = new javax.swing.JLabel();
        obrePdfBtn = new javax.swing.JButton();
        obreExcelBtn = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        digitsDirectePanel3.setEnabled(false);

        jLabel165.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel165.setText("Cogstate");

        obrePdfBtn.setText("Obre pdf");
        obrePdfBtn.setEnabled(false);
        obrePdfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obrePdfBtnActionPerformed(evt);
            }
        });

        obreExcelBtn.setText("Obre excel");
        obreExcelBtn.setEnabled(false);
        obreExcelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obreExcelBtnActionPerformed(evt);
            }
        });

        jButton18.setText("Importar pdf");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setText("Importar excel");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout digitsDirectePanel3Layout = new javax.swing.GroupLayout(digitsDirectePanel3);
        digitsDirectePanel3.setLayout(digitsDirectePanel3Layout);
        digitsDirectePanel3Layout.setHorizontalGroup(
            digitsDirectePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(digitsDirectePanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(digitsDirectePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel165)
                    .addGroup(digitsDirectePanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(digitsDirectePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton18)
                            .addComponent(obrePdfBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(digitsDirectePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(obreExcelBtn)
                            .addComponent(jButton19))))
                .addContainerGap())
        );
        digitsDirectePanel3Layout.setVerticalGroup(
            digitsDirectePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, digitsDirectePanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel165)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(digitsDirectePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(obrePdfBtn)
                    .addComponent(obreExcelBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(digitsDirectePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton18)
                    .addComponent(jButton19))
                .addContainerGap())
        );

        digitsDirecteScroll3.setViewportView(digitsDirectePanel3);

        add(digitsDirecteScroll3, "card1");
    }// </editor-fold>//GEN-END:initComponents

    private void obrePdfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obrePdfBtnActionPerformed
        File file = new File(Utils.PACIENT_DATA_PATH+this.pacientActual.getId()+File.separator+this.pacientActual.getId()+"COGSTATE_T"+valoracio+".pdf");
        try {
            Desktop.getDesktop().open(file);
        } catch (IOException ex) {
            Logger.getLogger(Sessio1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_obrePdfBtnActionPerformed

    private void obreExcelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obreExcelBtnActionPerformed
        File file = new File(Utils.PACIENT_DATA_PATH+this.pacientActual.getId()+File.separator+this.pacientActual.getId()+"COGSTATE_T"+valoracio+".xlsx");
        try {
            Desktop.getDesktop().open(file);
        } catch (IOException ex) {
            Logger.getLogger(Sessio1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_obreExcelBtnActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        FileDialog fd = new FileDialog(parent, "Esculli un arxiu", FileDialog.LOAD);
        fd.setDirectory(System.getProperty("user.home"));
        fd.setFile("*.pdf");
        fd.setVisible(true);
        String filename = fd.getFile();
        String dir=fd.getDirectory();
        if (filename != null){
            try {
                File f = new File(Utils.PACIENT_DATA_PATH+pacientActual.getId()+File.separator);
                if (!f.exists()){
                    f.mkdir();
                }
                Files.copy(Paths.get(dir+filename), Paths.get(Utils.PACIENT_DATA_PATH+this.pacientActual.getId()+File.separator+this.pacientActual.getId()+"COGSTATE.pdf"), StandardCopyOption.REPLACE_EXISTING);

            } catch (IOException ex) {
                Logger.getLogger(Sessio1.class.getName()).log(Level.SEVERE, null, ex);
            } finally{
                obrePdfBtn.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        FileDialog fd = new FileDialog(parent, "Esculli un arxiu", FileDialog.LOAD);
        fd.setDirectory(System.getProperty("user.home"));
        fd.setFile("*.xlsx");
        fd.setVisible(true);
        String filename = fd.getFile();
        String dir=fd.getDirectory();
        if (filename != null){
            try {
                File f = new File(Utils.PACIENT_DATA_PATH+pacientActual.getId()+File.separator);
                if (!f.exists()){
                    f.mkdir();
                }
                Files.copy(Paths.get(dir+filename), Paths.get(Utils.PACIENT_DATA_PATH+this.pacientActual.getId()+File.separator+this.pacientActual.getId()+"COGSTATE_T"+valoracio+".xlsx"), StandardCopyOption.REPLACE_EXISTING);
            } catch (IOException ex) {
                Logger.getLogger(Sessio1.class.getName()).log(Level.SEVERE, null, ex);
            } finally{
                obreExcelBtn.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jButton19ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel digitsDirectePanel3;
    private javax.swing.JScrollPane digitsDirecteScroll3;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JLabel jLabel165;
    private javax.swing.JButton obreExcelBtn;
    private javax.swing.JButton obrePdfBtn;
    // End of variables declaration//GEN-END:variables
}
