/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.tests;

import controlador.Utils;
import model.Pacient;

import java.util.Properties;

/**
 *
 * @author a630703
 */
public class MFE extends Test {

    /**
     * Creates new form Test
     *
     * @param pacientActual
     */
    public MFE(Pacient pacientActual) {
        super(pacientActual);
        initComponents();

        label = "MFE";
        numPaginesTotal = this.getComponentCount();
        
        Utils.initTaula(mfeQPanel,mfeTotal);
    }

    @Override
    public void guardarResultats(Properties prop) {
        // MFE
        Utils.setProperty(prop,"mfeTotal",mfeTotal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mfeButtonGroup1 = new javax.swing.ButtonGroup();
        mfeButtonGroup2 = new javax.swing.ButtonGroup();
        mfeButtonGroup3 = new javax.swing.ButtonGroup();
        mfeButtonGroup4 = new javax.swing.ButtonGroup();
        mfeButtonGroup5 = new javax.swing.ButtonGroup();
        mfeButtonGroup6 = new javax.swing.ButtonGroup();
        mfeButtonGroup7 = new javax.swing.ButtonGroup();
        mfeButtonGroup8 = new javax.swing.ButtonGroup();
        mfeButtonGroup9 = new javax.swing.ButtonGroup();
        mfeButtonGroup10 = new javax.swing.ButtonGroup();
        mfeButtonGroup11 = new javax.swing.ButtonGroup();
        mfeButtonGroup12 = new javax.swing.ButtonGroup();
        mfeButtonGroup13 = new javax.swing.ButtonGroup();
        mfeButtonGroup14 = new javax.swing.ButtonGroup();
        mfeButtonGroup15 = new javax.swing.ButtonGroup();
        mfeButtonGroup16 = new javax.swing.ButtonGroup();
        mfeButtonGroup17 = new javax.swing.ButtonGroup();
        mfeButtonGroup18 = new javax.swing.ButtonGroup();
        mfeButtonGroup19 = new javax.swing.ButtonGroup();
        mfeButtonGroup20 = new javax.swing.ButtonGroup();
        mfeButtonGroup21 = new javax.swing.ButtonGroup();
        mfeButtonGroup22 = new javax.swing.ButtonGroup();
        mfeButtonGroup23 = new javax.swing.ButtonGroup();
        mfeButtonGroup24 = new javax.swing.ButtonGroup();
        mfeButtonGroup25 = new javax.swing.ButtonGroup();
        mfeButtonGroup26 = new javax.swing.ButtonGroup();
        mfeButtonGroup27 = new javax.swing.ButtonGroup();
        mfeButtonGroup28 = new javax.swing.ButtonGroup();
        mfeScroll1 = new javax.swing.JScrollPane();
        mfePanel2 = new javax.swing.JPanel();
        jLabel109 = new javax.swing.JLabel();
        mfeQPanel = new javax.swing.JPanel();
        orientacioBtn22 = new javax.swing.JToggleButton();
        memoBtn22 = new javax.swing.JToggleButton();
        orientacioBtn23 = new javax.swing.JToggleButton();
        memoBtn23 = new javax.swing.JToggleButton();
        orientacioBtn24 = new javax.swing.JToggleButton();
        memoBtn24 = new javax.swing.JToggleButton();
        raoBtn22 = new javax.swing.JToggleButton();
        raoBtn24 = new javax.swing.JToggleButton();
        raoBtn25 = new javax.swing.JToggleButton();
        activitatsFBtn22 = new javax.swing.JToggleButton();
        activitatsFBtn23 = new javax.swing.JToggleButton();
        activitatsFBtn24 = new javax.swing.JToggleButton();
        activitatsDBtn23 = new javax.swing.JToggleButton();
        activitatsDBtn24 = new javax.swing.JToggleButton();
        cuidatBtn17 = new javax.swing.JToggleButton();
        cuidatBtn18 = new javax.swing.JToggleButton();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jLabel167 = new javax.swing.JLabel();
        jLabel168 = new javax.swing.JLabel();
        jLabel169 = new javax.swing.JLabel();
        jLabel170 = new javax.swing.JLabel();
        jLabel171 = new javax.swing.JLabel();
        jLabel172 = new javax.swing.JLabel();
        jLabel173 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        jToggleButton83 = new javax.swing.JToggleButton();
        jToggleButton84 = new javax.swing.JToggleButton();
        jToggleButton85 = new javax.swing.JToggleButton();
        jToggleButton86 = new javax.swing.JToggleButton();
        jToggleButton87 = new javax.swing.JToggleButton();
        jToggleButton88 = new javax.swing.JToggleButton();
        jToggleButton89 = new javax.swing.JToggleButton();
        jToggleButton90 = new javax.swing.JToggleButton();
        jToggleButton92 = new javax.swing.JToggleButton();
        jToggleButton93 = new javax.swing.JToggleButton();
        jToggleButton94 = new javax.swing.JToggleButton();
        jToggleButton95 = new javax.swing.JToggleButton();
        jToggleButton96 = new javax.swing.JToggleButton();
        jToggleButton97 = new javax.swing.JToggleButton();
        jToggleButton99 = new javax.swing.JToggleButton();
        jToggleButton100 = new javax.swing.JToggleButton();
        jToggleButton101 = new javax.swing.JToggleButton();
        jToggleButton103 = new javax.swing.JToggleButton();
        jToggleButton104 = new javax.swing.JToggleButton();
        jToggleButton105 = new javax.swing.JToggleButton();
        jToggleButton107 = new javax.swing.JToggleButton();
        jToggleButton109 = new javax.swing.JToggleButton();
        jToggleButton111 = new javax.swing.JToggleButton();
        jLabel117 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jToggleButton57 = new javax.swing.JToggleButton();
        jToggleButton58 = new javax.swing.JToggleButton();
        jToggleButton59 = new javax.swing.JToggleButton();
        jLabel137 = new javax.swing.JLabel();
        jToggleButton61 = new javax.swing.JToggleButton();
        jToggleButton62 = new javax.swing.JToggleButton();
        jToggleButton63 = new javax.swing.JToggleButton();
        jLabel138 = new javax.swing.JLabel();
        jToggleButton65 = new javax.swing.JToggleButton();
        jToggleButton66 = new javax.swing.JToggleButton();
        jToggleButton67 = new javax.swing.JToggleButton();
        jLabel139 = new javax.swing.JLabel();
        jLabel157 = new javax.swing.JLabel();
        jLabel158 = new javax.swing.JLabel();
        jLabel159 = new javax.swing.JLabel();
        jLabel160 = new javax.swing.JLabel();
        jLabel161 = new javax.swing.JLabel();
        jLabel162 = new javax.swing.JLabel();
        jLabel163 = new javax.swing.JLabel();
        jLabel164 = new javax.swing.JLabel();
        jLabel174 = new javax.swing.JLabel();
        jLabel175 = new javax.swing.JLabel();
        jLabel176 = new javax.swing.JLabel();
        jLabel177 = new javax.swing.JLabel();
        jLabel178 = new javax.swing.JLabel();
        jLabel179 = new javax.swing.JLabel();
        jLabel180 = new javax.swing.JLabel();
        jLabel181 = new javax.swing.JLabel();
        jLabel182 = new javax.swing.JLabel();
        jLabel183 = new javax.swing.JLabel();
        jLabel184 = new javax.swing.JLabel();
        jLabel185 = new javax.swing.JLabel();
        jLabel186 = new javax.swing.JLabel();
        jLabel187 = new javax.swing.JLabel();
        jLabel188 = new javax.swing.JLabel();
        jToggleButton69 = new javax.swing.JToggleButton();
        jToggleButton70 = new javax.swing.JToggleButton();
        jToggleButton71 = new javax.swing.JToggleButton();
        jToggleButton73 = new javax.swing.JToggleButton();
        jToggleButton74 = new javax.swing.JToggleButton();
        jToggleButton75 = new javax.swing.JToggleButton();
        jToggleButton77 = new javax.swing.JToggleButton();
        jToggleButton78 = new javax.swing.JToggleButton();
        jToggleButton79 = new javax.swing.JToggleButton();
        jToggleButton81 = new javax.swing.JToggleButton();
        jToggleButton82 = new javax.swing.JToggleButton();
        jToggleButton113 = new javax.swing.JToggleButton();
        jToggleButton115 = new javax.swing.JToggleButton();
        jToggleButton116 = new javax.swing.JToggleButton();
        jToggleButton117 = new javax.swing.JToggleButton();
        jToggleButton119 = new javax.swing.JToggleButton();
        jToggleButton120 = new javax.swing.JToggleButton();
        jToggleButton121 = new javax.swing.JToggleButton();
        jToggleButton123 = new javax.swing.JToggleButton();
        jToggleButton124 = new javax.swing.JToggleButton();
        jToggleButton125 = new javax.swing.JToggleButton();
        jToggleButton127 = new javax.swing.JToggleButton();
        jToggleButton128 = new javax.swing.JToggleButton();
        jToggleButton129 = new javax.swing.JToggleButton();
        jToggleButton131 = new javax.swing.JToggleButton();
        jToggleButton132 = new javax.swing.JToggleButton();
        jToggleButton133 = new javax.swing.JToggleButton();
        jToggleButton135 = new javax.swing.JToggleButton();
        jToggleButton136 = new javax.swing.JToggleButton();
        jToggleButton137 = new javax.swing.JToggleButton();
        jToggleButton139 = new javax.swing.JToggleButton();
        jToggleButton140 = new javax.swing.JToggleButton();
        jToggleButton141 = new javax.swing.JToggleButton();
        jToggleButton143 = new javax.swing.JToggleButton();
        jToggleButton144 = new javax.swing.JToggleButton();
        jToggleButton145 = new javax.swing.JToggleButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        mfeTotal = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        jLabel109.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel109.setText("<html><center><b>QÜESTIONARI DE MEMÒRIA DE LA VIDA DIÀRIA</b>");

        mfeQPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Qüestionari", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        mfeQPanel.setLayout(new java.awt.GridBagLayout());

        mfeButtonGroup2.add(orientacioBtn22);
        orientacioBtn22.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(orientacioBtn22, gridBagConstraints);

        mfeButtonGroup1.add(memoBtn22);
        memoBtn22.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(memoBtn22, gridBagConstraints);

        mfeButtonGroup2.add(orientacioBtn23);
        orientacioBtn23.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(orientacioBtn23, gridBagConstraints);

        mfeButtonGroup1.add(memoBtn23);
        memoBtn23.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(memoBtn23, gridBagConstraints);

        mfeButtonGroup2.add(orientacioBtn24);
        orientacioBtn24.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(orientacioBtn24, gridBagConstraints);

        mfeButtonGroup1.add(memoBtn24);
        memoBtn24.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(memoBtn24, gridBagConstraints);

        mfeButtonGroup3.add(raoBtn22);
        raoBtn22.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(raoBtn22, gridBagConstraints);

        mfeButtonGroup5.add(raoBtn24);
        raoBtn24.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(raoBtn24, gridBagConstraints);

        mfeButtonGroup3.add(raoBtn25);
        raoBtn25.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(raoBtn25, gridBagConstraints);

        mfeButtonGroup4.add(activitatsFBtn22);
        activitatsFBtn22.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(activitatsFBtn22, gridBagConstraints);

        mfeButtonGroup4.add(activitatsFBtn23);
        activitatsFBtn23.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(activitatsFBtn23, gridBagConstraints);

        mfeButtonGroup5.add(activitatsFBtn24);
        activitatsFBtn24.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(activitatsFBtn24, gridBagConstraints);

        mfeButtonGroup6.add(activitatsDBtn23);
        activitatsDBtn23.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(activitatsDBtn23, gridBagConstraints);

        mfeButtonGroup5.add(activitatsDBtn24);
        activitatsDBtn24.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(activitatsDBtn24, gridBagConstraints);

        mfeButtonGroup7.add(cuidatBtn17);
        cuidatBtn17.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(cuidatBtn17, gridBagConstraints);

        mfeButtonGroup7.add(cuidatBtn18);
        cuidatBtn18.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(cuidatBtn18, gridBagConstraints);

        jLabel118.setText("<html><center>Mai /<br>poques vegades");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 2);
        mfeQPanel.add(jLabel118, gridBagConstraints);

        jLabel119.setText("<html><center>Algun cop /<br>poques vegades");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 2);
        mfeQPanel.add(jLabel119, gridBagConstraints);

        jLabel167.setText("<html><center>Moltes vegades<br>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 2);
        mfeQPanel.add(jLabel167, gridBagConstraints);

        jLabel168.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        mfeQPanel.add(jLabel168, gridBagConstraints);

        jLabel169.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        mfeQPanel.add(jLabel169, gridBagConstraints);

        jLabel170.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        mfeQPanel.add(jLabel170, gridBagConstraints);

        jLabel171.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        mfeQPanel.add(jLabel171, gridBagConstraints);

        jLabel172.setText("6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        mfeQPanel.add(jLabel172, gridBagConstraints);

        jLabel173.setText("7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        mfeQPanel.add(jLabel173, gridBagConstraints);

        jLabel120.setText("<html>No recordar un canvi en les seves activitats diàries; per exemple, haver canviat<br> el lloc on guardava una cosa, o no recordar l'hora de fer alguna cosa en concret.<br>Seguir per error l'antiga rutina.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        mfeQPanel.add(jLabel120, gridBagConstraints);

        jLabel87.setText("Oblidar on ha posat alguna cosa. Perdre coses per casa.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mfeQPanel.add(jLabel87, gridBagConstraints);

        jLabel88.setText("No recordar llocs en els que li diuen que ha estat vàries vegades amb anterioritat.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 8);
        mfeQPanel.add(jLabel88, gridBagConstraints);

        jLabel89.setText("Tenir dificultats per seguir una història per televisió.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mfeQPanel.add(jLabel89, gridBagConstraints);

        jLabel90.setText("<html>Haver de tornar a comprovar si ha fet realment alguna cosa que tenia la intenció<br>de fer; per exemple, tancar el gas.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mfeQPanel.add(jLabel90, gridBagConstraints);

        jLabel91.setText("<html>Oblidar quan va passar alguna cosa; per exemple, oblidar si va passar ahir o bé<br>la setmana passada");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mfeQPanel.add(jLabel91, gridBagConstraints);

        jLabel92.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        mfeQPanel.add(jLabel92, gridBagConstraints);

        jLabel93.setText("8");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        mfeQPanel.add(jLabel93, gridBagConstraints);

        jLabel95.setText("10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 5);
        mfeQPanel.add(jLabel95, gridBagConstraints);

        jLabel96.setText("<html>Oblidar completament fer coses que hauria de fer, o que tenia planejat fer.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mfeQPanel.add(jLabel96, gridBagConstraints);

        jLabel97.setText("Oblidar detalls importants del que va fer o li va passar el dia anterior.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mfeQPanel.add(jLabel97, gridBagConstraints);

        jLabel98.setText("<html>Quan parla amb algú, oblidar el que acaba de dir o preguntar a vegades:<br>\"¿de què estàvem parlant?\"");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mfeQPanel.add(jLabel98, gridBagConstraints);

        jLabel102.setText("<html>Quan llegeix un diari o una revista, ser incapaç de seguir la trama d'una història,<br>perdre el fil de l'argumentació.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mfeQPanel.add(jLabel102, gridBagConstraints);

        jLabel104.setText("11");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 5);
        mfeQPanel.add(jLabel104, gridBagConstraints);

        jLabel121.setText("<html>Tenir dificultats en l'aprenentatge d'una nova habilitat; per exemple, en aprendre<br>les regles d'un nou joc o el funcionament d'un mecanisme, després de practicar-una<br>o dues vegades.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mfeQPanel.add(jLabel121, gridBagConstraints);

        jLabel122.setText("<html>Tenir una paraula \"a la punta de la llengua\". Saber el que vol dir, però no trobar<br>l'expressió adequada.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mfeQPanel.add(jLabel122, gridBagConstraints);

        jLabel123.setText("12");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 5);
        mfeQPanel.add(jLabel123, gridBagConstraints);

        jLabel124.setText("13");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 5);
        mfeQPanel.add(jLabel124, gridBagConstraints);

        mfeButtonGroup13.add(jToggleButton83);
        jToggleButton83.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton83, gridBagConstraints);

        mfeButtonGroup12.add(jToggleButton84);
        jToggleButton84.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton84, gridBagConstraints);

        mfeButtonGroup12.add(jToggleButton85);
        jToggleButton85.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton85, gridBagConstraints);

        mfeButtonGroup13.add(jToggleButton86);
        jToggleButton86.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton86, gridBagConstraints);

        mfeButtonGroup11.add(jToggleButton87);
        jToggleButton87.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton87, gridBagConstraints);

        mfeButtonGroup11.add(jToggleButton88);
        jToggleButton88.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton88, gridBagConstraints);

        mfeButtonGroup3.add(jToggleButton89);
        jToggleButton89.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton89, gridBagConstraints);

        mfeButtonGroup4.add(jToggleButton90);
        jToggleButton90.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton90, gridBagConstraints);

        mfeButtonGroup6.add(jToggleButton92);
        jToggleButton92.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton92, gridBagConstraints);

        mfeButtonGroup6.add(jToggleButton93);
        jToggleButton93.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton93, gridBagConstraints);

        mfeButtonGroup7.add(jToggleButton94);
        jToggleButton94.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton94, gridBagConstraints);

        mfeButtonGroup8.add(jToggleButton95);
        jToggleButton95.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton95, gridBagConstraints);

        mfeButtonGroup8.add(jToggleButton96);
        jToggleButton96.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton96, gridBagConstraints);

        mfeButtonGroup8.add(jToggleButton97);
        jToggleButton97.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton97, gridBagConstraints);

        mfeButtonGroup9.add(jToggleButton99);
        jToggleButton99.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton99, gridBagConstraints);

        mfeButtonGroup9.add(jToggleButton100);
        jToggleButton100.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton100, gridBagConstraints);

        mfeButtonGroup9.add(jToggleButton101);
        jToggleButton101.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton101, gridBagConstraints);

        mfeButtonGroup10.add(jToggleButton103);
        jToggleButton103.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton103, gridBagConstraints);

        mfeButtonGroup10.add(jToggleButton104);
        jToggleButton104.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton104, gridBagConstraints);

        mfeButtonGroup10.add(jToggleButton105);
        jToggleButton105.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton105, gridBagConstraints);

        mfeButtonGroup11.add(jToggleButton107);
        jToggleButton107.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton107, gridBagConstraints);

        mfeButtonGroup12.add(jToggleButton109);
        jToggleButton109.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton109, gridBagConstraints);

        mfeButtonGroup13.add(jToggleButton111);
        jToggleButton111.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton111, gridBagConstraints);

        jLabel117.setText("<html>Oblidar completament portar amb ell/a objectes que necessita (claus, ulleres,<br>moneder,...) o deixar-se objectes i haver de tornar a buscar-los.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mfeQPanel.add(jLabel117, gridBagConstraints);

        jLabel133.setText("<html>Oblidar una cosa que li van dir ahir o fa pocs dies, i potser veure's obligat a demanar<br>que l'hi repeteixin.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mfeQPanel.add(jLabel133, gridBagConstraints);

        jLabel136.setText("<html>No reconèixer, encara havent-se vist, a parents i amics quan es creua amb ells<br>pel carrer.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mfeQPanel.add(jLabel136, gridBagConstraints);

        jLabel115.setText("9");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        mfeQPanel.add(jLabel115, gridBagConstraints);

        jLabel134.setText("<html>Començar a llegir alguna cosa (un llibre o un article d'un diari o revista) sense<br> adonar-se que ja ho havia llegit anteriorment.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mfeQPanel.add(jLabel134, gridBagConstraints);

        jLabel135.setText("Divagar en una conversa i deixar-se portar cap a temes sense importància.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mfeQPanel.add(jLabel135, gridBagConstraints);

        mfeButtonGroup14.add(jToggleButton57);
        jToggleButton57.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton57, gridBagConstraints);

        mfeButtonGroup14.add(jToggleButton58);
        jToggleButton58.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton58, gridBagConstraints);

        mfeButtonGroup14.add(jToggleButton59);
        jToggleButton59.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton59, gridBagConstraints);

        jLabel137.setText("<html>Oblidar dir a algú alguna cosa important; per exemple, donar un avís o recordar<br>a algú alguna cosa.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mfeQPanel.add(jLabel137, gridBagConstraints);

        mfeButtonGroup15.add(jToggleButton61);
        jToggleButton61.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton61, gridBagConstraints);

        mfeButtonGroup15.add(jToggleButton62);
        jToggleButton62.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton62, gridBagConstraints);

        mfeButtonGroup15.add(jToggleButton63);
        jToggleButton63.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton63, gridBagConstraints);

        jLabel138.setText("Barrejar i confondre els detalls de coses que li han explicat altres persones.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mfeQPanel.add(jLabel138, gridBagConstraints);

        mfeButtonGroup16.add(jToggleButton65);
        jToggleButton65.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton65, gridBagConstraints);

        mfeButtonGroup16.add(jToggleButton66);
        jToggleButton66.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton66, gridBagConstraints);

        mfeButtonGroup16.add(jToggleButton67);
        jToggleButton67.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton67, gridBagConstraints);

        jLabel139.setText("<html>Oblidar detalls importants sobre si mateix; per exemple, el dia del seu aniversari<br>o el lloc on viu.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mfeQPanel.add(jLabel139, gridBagConstraints);

        jLabel157.setText("14");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 5);
        mfeQPanel.add(jLabel157, gridBagConstraints);

        jLabel158.setText("16");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 5);
        mfeQPanel.add(jLabel158, gridBagConstraints);

        jLabel159.setText("15");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 5);
        mfeQPanel.add(jLabel159, gridBagConstraints);

        jLabel160.setText("17");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 5);
        mfeQPanel.add(jLabel160, gridBagConstraints);

        jLabel161.setText("19");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 5);
        mfeQPanel.add(jLabel161, gridBagConstraints);

        jLabel162.setText("18");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 5);
        mfeQPanel.add(jLabel162, gridBagConstraints);

        jLabel163.setText("20");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 5);
        mfeQPanel.add(jLabel163, gridBagConstraints);

        jLabel164.setText("21");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 5);
        mfeQPanel.add(jLabel164, gridBagConstraints);

        jLabel174.setText("22");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 5);
        mfeQPanel.add(jLabel174, gridBagConstraints);

        jLabel175.setText("23");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 5);
        mfeQPanel.add(jLabel175, gridBagConstraints);

        jLabel176.setText("24");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 5);
        mfeQPanel.add(jLabel176, gridBagConstraints);

        jLabel177.setText("25");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 5);
        mfeQPanel.add(jLabel177, gridBagConstraints);

        jLabel178.setText("26");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 5);
        mfeQPanel.add(jLabel178, gridBagConstraints);

        jLabel179.setText("27");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 29;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 5);
        mfeQPanel.add(jLabel179, gridBagConstraints);

        jLabel180.setText("28");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 5);
        mfeQPanel.add(jLabel180, gridBagConstraints);

        jLabel181.setText("Explicar-li a algú una anècdota o un acudit que li havia explicat anteriorment.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mfeQPanel.add(jLabel181, gridBagConstraints);

        jLabel182.setText("<html>Oblidar detalls de coses que fa habitualment, ja sigui a casa oa la feina; per exemple<br>oblidar detalls sobre el que ha de fer o bé sobre l'hora en què ha de fer.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mfeQPanel.add(jLabel182, gridBagConstraints);

        jLabel183.setText("Oblidar on es guarden normalment les coses i buscar-les en un lloc equivocat.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mfeQPanel.add(jLabel183, gridBagConstraints);

        jLabel184.setText("<html>No reconèixer les cares de persones famoses que veu amb freqüència a la televisió<br>o en fotografia.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mfeQPanel.add(jLabel184, gridBagConstraints);

        jLabel185.setText("<html>Perdre's o seguir una adreça errònia en un viatge, en un passeig o en un edifici <br>on ha estat <b>moltes vegades.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 27;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mfeQPanel.add(jLabel185, gridBagConstraints);

        jLabel186.setText("<html>Realtizar una acció dos vegades per error. Per exemple, afegir dos vegades sal<br>al menjar o anar a pentinarse una altre vegada quan ja ho ha fet. ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 29;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mfeQPanel.add(jLabel186, gridBagConstraints);

        jLabel187.setText("<html>Perdre's o seguir una adreça errònia en un viatge, en un passeig o en un edifici <br>on ha estat només <b>una o dues vegades");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mfeQPanel.add(jLabel187, gridBagConstraints);

        jLabel188.setText("Repetir a algú el que acaba d'explicar-li o fer-li dues vegades la mateixa pregunta.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        mfeQPanel.add(jLabel188, gridBagConstraints);

        mfeButtonGroup17.add(jToggleButton69);
        jToggleButton69.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton69, gridBagConstraints);

        mfeButtonGroup17.add(jToggleButton70);
        jToggleButton70.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton70, gridBagConstraints);

        mfeButtonGroup17.add(jToggleButton71);
        jToggleButton71.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton71, gridBagConstraints);

        mfeButtonGroup18.add(jToggleButton73);
        jToggleButton73.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton73, gridBagConstraints);

        mfeButtonGroup18.add(jToggleButton74);
        jToggleButton74.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton74, gridBagConstraints);

        mfeButtonGroup18.add(jToggleButton75);
        jToggleButton75.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton75, gridBagConstraints);

        mfeButtonGroup19.add(jToggleButton77);
        jToggleButton77.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton77, gridBagConstraints);

        mfeButtonGroup19.add(jToggleButton78);
        jToggleButton78.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton78, gridBagConstraints);

        mfeButtonGroup19.add(jToggleButton79);
        jToggleButton79.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton79, gridBagConstraints);

        mfeButtonGroup20.add(jToggleButton81);
        jToggleButton81.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton81, gridBagConstraints);

        mfeButtonGroup20.add(jToggleButton82);
        jToggleButton82.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton82, gridBagConstraints);

        mfeButtonGroup20.add(jToggleButton113);
        jToggleButton113.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton113, gridBagConstraints);

        mfeButtonGroup21.add(jToggleButton115);
        jToggleButton115.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton115, gridBagConstraints);

        mfeButtonGroup21.add(jToggleButton116);
        jToggleButton116.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton116, gridBagConstraints);

        mfeButtonGroup21.add(jToggleButton117);
        jToggleButton117.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 23;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton117, gridBagConstraints);

        mfeButtonGroup22.add(jToggleButton119);
        jToggleButton119.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton119, gridBagConstraints);

        mfeButtonGroup22.add(jToggleButton120);
        jToggleButton120.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton120, gridBagConstraints);

        mfeButtonGroup22.add(jToggleButton121);
        jToggleButton121.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton121, gridBagConstraints);

        mfeButtonGroup23.add(jToggleButton123);
        jToggleButton123.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 25;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton123, gridBagConstraints);

        mfeButtonGroup23.add(jToggleButton124);
        jToggleButton124.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 25;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton124, gridBagConstraints);

        mfeButtonGroup23.add(jToggleButton125);
        jToggleButton125.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 25;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton125, gridBagConstraints);

        mfeButtonGroup24.add(jToggleButton127);
        jToggleButton127.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton127, gridBagConstraints);

        mfeButtonGroup24.add(jToggleButton128);
        jToggleButton128.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton128, gridBagConstraints);

        mfeButtonGroup24.add(jToggleButton129);
        jToggleButton129.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton129, gridBagConstraints);

        mfeButtonGroup25.add(jToggleButton131);
        jToggleButton131.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 27;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton131, gridBagConstraints);

        mfeButtonGroup25.add(jToggleButton132);
        jToggleButton132.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 27;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton132, gridBagConstraints);

        mfeButtonGroup25.add(jToggleButton133);
        jToggleButton133.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 27;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton133, gridBagConstraints);

        mfeButtonGroup26.add(jToggleButton135);
        jToggleButton135.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton135, gridBagConstraints);

        mfeButtonGroup26.add(jToggleButton136);
        jToggleButton136.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton136, gridBagConstraints);

        mfeButtonGroup26.add(jToggleButton137);
        jToggleButton137.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton137, gridBagConstraints);

        mfeButtonGroup27.add(jToggleButton139);
        jToggleButton139.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 29;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton139, gridBagConstraints);

        mfeButtonGroup27.add(jToggleButton140);
        jToggleButton140.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 29;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton140, gridBagConstraints);

        mfeButtonGroup27.add(jToggleButton141);
        jToggleButton141.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 29;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton141, gridBagConstraints);

        mfeButtonGroup28.add(jToggleButton143);
        jToggleButton143.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 30;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton143, gridBagConstraints);

        mfeButtonGroup28.add(jToggleButton144);
        jToggleButton144.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 30;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton144, gridBagConstraints);

        mfeButtonGroup28.add(jToggleButton145);
        jToggleButton145.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 30;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        mfeQPanel.add(jToggleButton145, gridBagConstraints);

        jLabel16.setText("ASSENYALI AMB QUINA FREQÜÈNCIA LI OCORREN A VOSTÈ ELS SEGÜENTS ERRORS DE MEMÒRIA");

        jLabel70.setText("Puntuació total:");

        mfeTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mfeTotal.setText("0");

        javax.swing.GroupLayout mfePanel2Layout = new javax.swing.GroupLayout(mfePanel2);
        mfePanel2.setLayout(mfePanel2Layout);
        mfePanel2Layout.setHorizontalGroup(
            mfePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mfePanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mfePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel109, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mfePanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(mfePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(mfePanel2Layout.createSequentialGroup()
                                .addComponent(mfeQPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel70)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mfeTotal)))))
                .addGap(81, 81, 81))
        );
        mfePanel2Layout.setVerticalGroup(
            mfePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mfePanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel109, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addGroup(mfePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mfePanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mfeQPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mfePanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(mfePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel70)
                            .addComponent(mfeTotal))))
                .addContainerGap())
        );

        mfeScroll1.setViewportView(mfePanel2);

        add(mfeScroll1, "card1");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton activitatsDBtn23;
    private javax.swing.JToggleButton activitatsDBtn24;
    private javax.swing.JToggleButton activitatsFBtn22;
    private javax.swing.JToggleButton activitatsFBtn23;
    private javax.swing.JToggleButton activitatsFBtn24;
    private javax.swing.JToggleButton cuidatBtn17;
    private javax.swing.JToggleButton cuidatBtn18;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel158;
    private javax.swing.JLabel jLabel159;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel160;
    private javax.swing.JLabel jLabel161;
    private javax.swing.JLabel jLabel162;
    private javax.swing.JLabel jLabel163;
    private javax.swing.JLabel jLabel164;
    private javax.swing.JLabel jLabel167;
    private javax.swing.JLabel jLabel168;
    private javax.swing.JLabel jLabel169;
    private javax.swing.JLabel jLabel170;
    private javax.swing.JLabel jLabel171;
    private javax.swing.JLabel jLabel172;
    private javax.swing.JLabel jLabel173;
    private javax.swing.JLabel jLabel174;
    private javax.swing.JLabel jLabel175;
    private javax.swing.JLabel jLabel176;
    private javax.swing.JLabel jLabel177;
    private javax.swing.JLabel jLabel178;
    private javax.swing.JLabel jLabel179;
    private javax.swing.JLabel jLabel180;
    private javax.swing.JLabel jLabel181;
    private javax.swing.JLabel jLabel182;
    private javax.swing.JLabel jLabel183;
    private javax.swing.JLabel jLabel184;
    private javax.swing.JLabel jLabel185;
    private javax.swing.JLabel jLabel186;
    private javax.swing.JLabel jLabel187;
    private javax.swing.JLabel jLabel188;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JToggleButton jToggleButton100;
    private javax.swing.JToggleButton jToggleButton101;
    private javax.swing.JToggleButton jToggleButton103;
    private javax.swing.JToggleButton jToggleButton104;
    private javax.swing.JToggleButton jToggleButton105;
    private javax.swing.JToggleButton jToggleButton107;
    private javax.swing.JToggleButton jToggleButton109;
    private javax.swing.JToggleButton jToggleButton111;
    private javax.swing.JToggleButton jToggleButton113;
    private javax.swing.JToggleButton jToggleButton115;
    private javax.swing.JToggleButton jToggleButton116;
    private javax.swing.JToggleButton jToggleButton117;
    private javax.swing.JToggleButton jToggleButton119;
    private javax.swing.JToggleButton jToggleButton120;
    private javax.swing.JToggleButton jToggleButton121;
    private javax.swing.JToggleButton jToggleButton123;
    private javax.swing.JToggleButton jToggleButton124;
    private javax.swing.JToggleButton jToggleButton125;
    private javax.swing.JToggleButton jToggleButton127;
    private javax.swing.JToggleButton jToggleButton128;
    private javax.swing.JToggleButton jToggleButton129;
    private javax.swing.JToggleButton jToggleButton131;
    private javax.swing.JToggleButton jToggleButton132;
    private javax.swing.JToggleButton jToggleButton133;
    private javax.swing.JToggleButton jToggleButton135;
    private javax.swing.JToggleButton jToggleButton136;
    private javax.swing.JToggleButton jToggleButton137;
    private javax.swing.JToggleButton jToggleButton139;
    private javax.swing.JToggleButton jToggleButton140;
    private javax.swing.JToggleButton jToggleButton141;
    private javax.swing.JToggleButton jToggleButton143;
    private javax.swing.JToggleButton jToggleButton144;
    private javax.swing.JToggleButton jToggleButton145;
    private javax.swing.JToggleButton jToggleButton57;
    private javax.swing.JToggleButton jToggleButton58;
    private javax.swing.JToggleButton jToggleButton59;
    private javax.swing.JToggleButton jToggleButton61;
    private javax.swing.JToggleButton jToggleButton62;
    private javax.swing.JToggleButton jToggleButton63;
    private javax.swing.JToggleButton jToggleButton65;
    private javax.swing.JToggleButton jToggleButton66;
    private javax.swing.JToggleButton jToggleButton67;
    private javax.swing.JToggleButton jToggleButton69;
    private javax.swing.JToggleButton jToggleButton70;
    private javax.swing.JToggleButton jToggleButton71;
    private javax.swing.JToggleButton jToggleButton73;
    private javax.swing.JToggleButton jToggleButton74;
    private javax.swing.JToggleButton jToggleButton75;
    private javax.swing.JToggleButton jToggleButton77;
    private javax.swing.JToggleButton jToggleButton78;
    private javax.swing.JToggleButton jToggleButton79;
    private javax.swing.JToggleButton jToggleButton81;
    private javax.swing.JToggleButton jToggleButton82;
    private javax.swing.JToggleButton jToggleButton83;
    private javax.swing.JToggleButton jToggleButton84;
    private javax.swing.JToggleButton jToggleButton85;
    private javax.swing.JToggleButton jToggleButton86;
    private javax.swing.JToggleButton jToggleButton87;
    private javax.swing.JToggleButton jToggleButton88;
    private javax.swing.JToggleButton jToggleButton89;
    private javax.swing.JToggleButton jToggleButton90;
    private javax.swing.JToggleButton jToggleButton92;
    private javax.swing.JToggleButton jToggleButton93;
    private javax.swing.JToggleButton jToggleButton94;
    private javax.swing.JToggleButton jToggleButton95;
    private javax.swing.JToggleButton jToggleButton96;
    private javax.swing.JToggleButton jToggleButton97;
    private javax.swing.JToggleButton jToggleButton99;
    private javax.swing.JToggleButton memoBtn22;
    private javax.swing.JToggleButton memoBtn23;
    private javax.swing.JToggleButton memoBtn24;
    private javax.swing.ButtonGroup mfeButtonGroup1;
    private javax.swing.ButtonGroup mfeButtonGroup10;
    private javax.swing.ButtonGroup mfeButtonGroup11;
    private javax.swing.ButtonGroup mfeButtonGroup12;
    private javax.swing.ButtonGroup mfeButtonGroup13;
    private javax.swing.ButtonGroup mfeButtonGroup14;
    private javax.swing.ButtonGroup mfeButtonGroup15;
    private javax.swing.ButtonGroup mfeButtonGroup16;
    private javax.swing.ButtonGroup mfeButtonGroup17;
    private javax.swing.ButtonGroup mfeButtonGroup18;
    private javax.swing.ButtonGroup mfeButtonGroup19;
    private javax.swing.ButtonGroup mfeButtonGroup2;
    private javax.swing.ButtonGroup mfeButtonGroup20;
    private javax.swing.ButtonGroup mfeButtonGroup21;
    private javax.swing.ButtonGroup mfeButtonGroup22;
    private javax.swing.ButtonGroup mfeButtonGroup23;
    private javax.swing.ButtonGroup mfeButtonGroup24;
    private javax.swing.ButtonGroup mfeButtonGroup25;
    private javax.swing.ButtonGroup mfeButtonGroup26;
    private javax.swing.ButtonGroup mfeButtonGroup27;
    private javax.swing.ButtonGroup mfeButtonGroup28;
    private javax.swing.ButtonGroup mfeButtonGroup3;
    private javax.swing.ButtonGroup mfeButtonGroup4;
    private javax.swing.ButtonGroup mfeButtonGroup5;
    private javax.swing.ButtonGroup mfeButtonGroup6;
    private javax.swing.ButtonGroup mfeButtonGroup7;
    private javax.swing.ButtonGroup mfeButtonGroup8;
    private javax.swing.ButtonGroup mfeButtonGroup9;
    private javax.swing.JPanel mfePanel2;
    private javax.swing.JPanel mfeQPanel;
    private javax.swing.JScrollPane mfeScroll1;
    private javax.swing.JLabel mfeTotal;
    private javax.swing.JToggleButton orientacioBtn22;
    private javax.swing.JToggleButton orientacioBtn23;
    private javax.swing.JToggleButton orientacioBtn24;
    private javax.swing.JToggleButton raoBtn22;
    private javax.swing.JToggleButton raoBtn24;
    private javax.swing.JToggleButton raoBtn25;
    // End of variables declaration//GEN-END:variables
}
