/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.tests;

import controlador.Utils;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import model.Pacient;

import java.util.Properties;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JToggleButton;

/**
 *
 * @author a630703
 */
public class MOS extends Test  {
    
    
    /**
     * Creates new form Test
     *
     * @param pacientActual
     */
    public MOS(Pacient pacientActual) {
        super(pacientActual);
        initComponents();

        label = "MOS";
        numPaginesTotal = this.getComponentCount();
        
        initTaula(PANASSPanel);
       // PANAS.initTaula(MOSPanel,AfectivoNegativo);
        //PANAS.initTaula(MOSPanel,PanasTotal);
    }
    
    
 


    @Override
    public void guardarResultats(Properties prop) {
        // MOS
        Utils.setProperty(prop,"MOSAmigos",MOSAmigos);
        Utils.setProperty(prop,"MOSFamilia",MOSFamilia);
        Utils.setProperty(prop,"ApoyoEmocional",ApoyoEmocional);
        Utils.setProperty(prop,"AyudaMaterial",AyudaMaterial);
        Utils.setProperty(prop,"SocialOcio",SocialOcio);
        Utils.setProperty(prop,"ApoyoAfectivo",ApoyoAfectivo);
        Utils.setProperty(prop,"MOSTotal",MOSTotal);
       
    }
     
    
    public void actualitzaResultatTaula(JPanel panel){ // static?
        int countTotal = 0;
        int countEmocional =0;
        int countMaterial =0;
        int countOcio =0;
        int countAfectivo =0;
        
        String name ="";
        for (Component com : panel.getComponents()){
            if (com instanceof JToggleButton){
                if(((JToggleButton)com).isSelected()){
                    
                    name = com.getName();
                    countTotal += Integer.parseInt(((JToggleButton)com).getText());
                    
                    if ( name=="emocional"){
                        countEmocional += Integer.parseInt(((JToggleButton)com).getText());
                    } else if (name == "material") {
                        countMaterial += Integer.parseInt(((JToggleButton)com).getText());
                    } else if (name == "ocio"){
                        countOcio += Integer.parseInt(((JToggleButton)com).getText());
                        
                    } else if (name == "afectivo"){
                        countAfectivo += Integer.parseInt(((JToggleButton)com).getText());
                    }
                    
                }
            }
        }
        MOSTotal.setText(countTotal+"");
        ApoyoEmocional.setText(countEmocional+"");
        AyudaMaterial.setText(countMaterial+"");
        SocialOcio.setText(countOcio+"");
        ApoyoAfectivo.setText(countAfectivo+"");
    }

    public void initTaula(final JPanel panel){ // static?
        for (Component com : panel.getComponents()){
            if (com instanceof JToggleButton){
                ((JToggleButton)com).addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        actualitzaResultatTaula(panel);
                    }
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        eptBtnGroup1 = new javax.swing.ButtonGroup();
        eptBtnGroup2 = new javax.swing.ButtonGroup();
        eptBtnGroup3 = new javax.swing.ButtonGroup();
        eptBtnGroup4 = new javax.swing.ButtonGroup();
        eptBtnGroup5 = new javax.swing.ButtonGroup();
        eptBtnGroup6 = new javax.swing.ButtonGroup();
        eptBtnGroup7 = new javax.swing.ButtonGroup();
        eptBtnGroup8 = new javax.swing.ButtonGroup();
        eptBtnGroup9 = new javax.swing.ButtonGroup();
        eptBtnGroup10 = new javax.swing.ButtonGroup();
        eptBtnGroup11 = new javax.swing.ButtonGroup();
        eptBtnGroup12 = new javax.swing.ButtonGroup();
        eptBtnGroup13 = new javax.swing.ButtonGroup();
        eptBtnGroup14 = new javax.swing.ButtonGroup();
        eptBtnGroup15 = new javax.swing.ButtonGroup();
        eptBtnGroup16 = new javax.swing.ButtonGroup();
        eptBtnGroup17 = new javax.swing.ButtonGroup();
        eptBtnGroup18 = new javax.swing.ButtonGroup();
        eptBtnGroup19 = new javax.swing.ButtonGroup();
        eptBtnGroup20 = new javax.swing.ButtonGroup();
        eptScroll = new javax.swing.JScrollPane();
        PANASPanel = new javax.swing.JPanel();
        PANASLabel33 = new javax.swing.JLabel();
        PANASSPanel = new javax.swing.JPanel();
        PANASBtn1411 = new javax.swing.JToggleButton();
        PANASBtn151 = new javax.swing.JToggleButton();
        PANASBtn161 = new javax.swing.JToggleButton();
        PANASBtn171 = new javax.swing.JToggleButton();
        PANASBtn141 = new javax.swing.JToggleButton();
        PANASBtn1511 = new javax.swing.JToggleButton();
        PANASBtn1611 = new javax.swing.JToggleButton();
        PANASBtn1711 = new javax.swing.JToggleButton();
        PANASFBtn14 = new javax.swing.JToggleButton();
        PANASFBtn15 = new javax.swing.JToggleButton();
        PANASFBtn16 = new javax.swing.JToggleButton();
        PANASFBtn17 = new javax.swing.JToggleButton();
        PANASDBtn14 = new javax.swing.JToggleButton();
        PANASDBtn15 = new javax.swing.JToggleButton();
        PANASDBtn16 = new javax.swing.JToggleButton();
        PANASDBtn17 = new javax.swing.JToggleButton();
        PANASLabel112 = new javax.swing.JLabel();
        PANASLabel11 = new javax.swing.JLabel();
        PANASLabel149 = new javax.swing.JLabel();
        PANASLabel150 = new javax.swing.JLabel();
        PANASLabel152 = new javax.swing.JLabel();
        PANASLabel153 = new javax.swing.JLabel();
        PANASLabel154 = new javax.swing.JLabel();
        PANASLabel155 = new javax.swing.JLabel();
        PANASLabel114 = new javax.swing.JLabel();
        PANASLabel54 = new javax.swing.JLabel();
        PANASLabel55 = new javax.swing.JLabel();
        PANASLabel56 = new javax.swing.JLabel();
        PANASLabel57 = new javax.swing.JLabel();
        PANASLabel58 = new javax.swing.JLabel();
        PANASToggleButton37 = new javax.swing.JToggleButton();
        PANASToggleButton38 = new javax.swing.JToggleButton();
        PANASToggleButton39 = new javax.swing.JToggleButton();
        PANASToggleButton40 = new javax.swing.JToggleButton();
        PANASToggleButton41 = new javax.swing.JToggleButton();
        PANASLabel156 = new javax.swing.JLabel();
        PANASBtn172 = new javax.swing.JToggleButton();
        PANASBtn1512 = new javax.swing.JToggleButton();
        PANASToggleButton42 = new javax.swing.JToggleButton();
        PANASDBtn18 = new javax.swing.JToggleButton();
        PANASFBtn18 = new javax.swing.JToggleButton();
        eptLabel157 = new javax.swing.JLabel();
        eptLabel59 = new javax.swing.JLabel();
        eptBtn18 = new javax.swing.JToggleButton();
        eptBtn20 = new javax.swing.JToggleButton();
        eptBtn21 = new javax.swing.JToggleButton();
        eptBtn22 = new javax.swing.JToggleButton();
        eptBtn23 = new javax.swing.JToggleButton();
        eptLabel158 = new javax.swing.JLabel();
        eptLabel60 = new javax.swing.JLabel();
        eptBtn24 = new javax.swing.JToggleButton();
        eptBtn25 = new javax.swing.JToggleButton();
        eptBtn26 = new javax.swing.JToggleButton();
        eptBtn27 = new javax.swing.JToggleButton();
        eptBtn28 = new javax.swing.JToggleButton();
        eptLabel159 = new javax.swing.JLabel();
        eptLabel61 = new javax.swing.JLabel();
        eptBtn29 = new javax.swing.JToggleButton();
        eptBtn30 = new javax.swing.JToggleButton();
        eptBtn31 = new javax.swing.JToggleButton();
        eptBtn32 = new javax.swing.JToggleButton();
        eptBtn33 = new javax.swing.JToggleButton();
        eptLabel160 = new javax.swing.JLabel();
        eptLabel62 = new javax.swing.JLabel();
        eptBtn34 = new javax.swing.JToggleButton();
        eptBtn35 = new javax.swing.JToggleButton();
        eptBtn36 = new javax.swing.JToggleButton();
        eptBtn37 = new javax.swing.JToggleButton();
        eptBtn38 = new javax.swing.JToggleButton();
        eptLabel63 = new javax.swing.JLabel();
        eptBtn39 = new javax.swing.JToggleButton();
        eptBtn40 = new javax.swing.JToggleButton();
        eptBtn41 = new javax.swing.JToggleButton();
        eptBtn42 = new javax.swing.JToggleButton();
        eptBtn43 = new javax.swing.JToggleButton();
        eptLabel162 = new javax.swing.JLabel();
        eptLabel64 = new javax.swing.JLabel();
        eptBtn44 = new javax.swing.JToggleButton();
        eptBtn45 = new javax.swing.JToggleButton();
        eptBtn46 = new javax.swing.JToggleButton();
        eptBtn47 = new javax.swing.JToggleButton();
        eptBtn48 = new javax.swing.JToggleButton();
        eptLabel163 = new javax.swing.JLabel();
        eptLabel164 = new javax.swing.JLabel();
        eptLabel66 = new javax.swing.JLabel();
        eptBtn54 = new javax.swing.JToggleButton();
        eptBtn55 = new javax.swing.JToggleButton();
        eptBtn56 = new javax.swing.JToggleButton();
        eptBtn57 = new javax.swing.JToggleButton();
        eptBtn58 = new javax.swing.JToggleButton();
        eptLabel165 = new javax.swing.JLabel();
        eptLabel67 = new javax.swing.JLabel();
        eptBtn59 = new javax.swing.JToggleButton();
        eptBtn60 = new javax.swing.JToggleButton();
        eptBtn61 = new javax.swing.JToggleButton();
        eptBtn62 = new javax.swing.JToggleButton();
        eptBtn63 = new javax.swing.JToggleButton();
        eptLabel166 = new javax.swing.JLabel();
        eptLabel68 = new javax.swing.JLabel();
        eptBtn64 = new javax.swing.JToggleButton();
        eptBtn65 = new javax.swing.JToggleButton();
        eptBtn66 = new javax.swing.JToggleButton();
        eptBtn67 = new javax.swing.JToggleButton();
        eptBtn68 = new javax.swing.JToggleButton();
        eptLabel167 = new javax.swing.JLabel();
        eptLabel69 = new javax.swing.JLabel();
        eptBtn69 = new javax.swing.JToggleButton();
        eptBtn70 = new javax.swing.JToggleButton();
        eptBtn71 = new javax.swing.JToggleButton();
        eptBtn72 = new javax.swing.JToggleButton();
        eptBtn73 = new javax.swing.JToggleButton();
        eptLabel168 = new javax.swing.JLabel();
        eptLabel70 = new javax.swing.JLabel();
        eptBtn74 = new javax.swing.JToggleButton();
        eptBtn75 = new javax.swing.JToggleButton();
        eptBtn76 = new javax.swing.JToggleButton();
        eptBtn77 = new javax.swing.JToggleButton();
        eptBtn78 = new javax.swing.JToggleButton();
        eptLabel169 = new javax.swing.JLabel();
        eptLabel71 = new javax.swing.JLabel();
        eptBtn79 = new javax.swing.JToggleButton();
        eptBtn80 = new javax.swing.JToggleButton();
        eptBtn81 = new javax.swing.JToggleButton();
        eptBtn82 = new javax.swing.JToggleButton();
        eptBtn83 = new javax.swing.JToggleButton();
        eptLabel170 = new javax.swing.JLabel();
        eptLabel72 = new javax.swing.JLabel();
        eptBtn84 = new javax.swing.JToggleButton();
        eptBtn85 = new javax.swing.JToggleButton();
        eptBtn86 = new javax.swing.JToggleButton();
        eptBtn87 = new javax.swing.JToggleButton();
        eptBtn88 = new javax.swing.JToggleButton();
        eptLabel171 = new javax.swing.JLabel();
        eptLabel73 = new javax.swing.JLabel();
        eptBtn89 = new javax.swing.JToggleButton();
        eptBtn90 = new javax.swing.JToggleButton();
        eptBtn91 = new javax.swing.JToggleButton();
        eptBtn92 = new javax.swing.JToggleButton();
        eptBtn93 = new javax.swing.JToggleButton();
        PANASLabel74 = new javax.swing.JLabel();
        PANASLabel32 = new javax.swing.JLabel();
        PANASLabel217 = new javax.swing.JLabel();
        ApoyoEmocional = new javax.swing.JLabel();
        PANASLabel218 = new javax.swing.JLabel();
        AyudaMaterial = new javax.swing.JLabel();
        PANASLabel219 = new javax.swing.JLabel();
        SocialOcio = new javax.swing.JLabel();
        PANASLabel34 = new javax.swing.JLabel();
        PANASLabel53 = new javax.swing.JLabel();
        MOSAmigos = new javax.swing.JTextField();
        MOSFamilia = new javax.swing.JTextField();
        PANASLabel220 = new javax.swing.JLabel();
        ApoyoAfectivo = new javax.swing.JLabel();
        PANASLabel221 = new javax.swing.JLabel();
        MOSTotal = new javax.swing.JLabel();
        PANASLabel65 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        PANASLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PANASLabel33.setText("Cuestionario MOS de apoyo social");

        PANASSPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        PANASSPanel.setLayout(new java.awt.GridBagLayout());

        eptBtnGroup2.add(PANASBtn1411);
        PANASBtn1411.setText("1");
        PANASBtn1411.setName("material"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(PANASBtn1411, gridBagConstraints);

        eptBtnGroup2.add(PANASBtn151);
        PANASBtn151.setText("2");
        PANASBtn151.setName("material"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(PANASBtn151, gridBagConstraints);

        eptBtnGroup2.add(PANASBtn161);
        PANASBtn161.setText("3");
        PANASBtn161.setName("material"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(PANASBtn161, gridBagConstraints);

        eptBtnGroup2.add(PANASBtn171);
        PANASBtn171.setText("5");
        PANASBtn171.setName("material"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASSPanel.add(PANASBtn171, gridBagConstraints);

        eptBtnGroup3.add(PANASBtn141);
        PANASBtn141.setText("1");
        PANASBtn141.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(PANASBtn141, gridBagConstraints);

        eptBtnGroup3.add(PANASBtn1511);
        PANASBtn1511.setText("5");
        PANASBtn1511.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASSPanel.add(PANASBtn1511, gridBagConstraints);

        eptBtnGroup5.add(PANASBtn1611);
        PANASBtn1611.setText("2");
        PANASBtn1611.setName("material"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(PANASBtn1611, gridBagConstraints);

        eptBtnGroup3.add(PANASBtn1711);
        PANASBtn1711.setText("3");
        PANASBtn1711.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(PANASBtn1711, gridBagConstraints);

        eptBtnGroup4.add(PANASFBtn14);
        PANASFBtn14.setText("1");
        PANASFBtn14.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(PANASFBtn14, gridBagConstraints);

        eptBtnGroup4.add(PANASFBtn15);
        PANASFBtn15.setText("2");
        PANASFBtn15.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(PANASFBtn15, gridBagConstraints);

        eptBtnGroup5.add(PANASFBtn16);
        PANASFBtn16.setText("3");
        PANASFBtn16.setName("material"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(PANASFBtn16, gridBagConstraints);

        eptBtnGroup5.add(PANASFBtn17);
        PANASFBtn17.setText("5");
        PANASFBtn17.setName("material"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASSPanel.add(PANASFBtn17, gridBagConstraints);

        eptBtnGroup6.add(PANASDBtn14);
        PANASDBtn14.setText("5");
        PANASDBtn14.setName("afectivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 2;
        PANASSPanel.add(PANASDBtn14, gridBagConstraints);

        eptBtnGroup6.add(PANASDBtn15);
        PANASDBtn15.setText("3");
        PANASDBtn15.setName("afectivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(PANASDBtn15, gridBagConstraints);

        eptBtnGroup5.add(PANASDBtn16);
        PANASDBtn16.setText("1");
        PANASDBtn16.setName("material"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(PANASDBtn16, gridBagConstraints);

        PANASDBtn17.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(PANASDBtn17, gridBagConstraints);

        PANASLabel112.setText("<html><center>Nunca<br>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 2);
        PANASSPanel.add(PANASLabel112, gridBagConstraints);

        PANASLabel11.setText("<html><center>Pocas<br>veces");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 2);
        PANASSPanel.add(PANASLabel11, gridBagConstraints);

        PANASLabel149.setText("<html><center>Siempre<br>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        PANASSPanel.add(PANASLabel149, gridBagConstraints);

        PANASLabel150.setText("<html><center>Algunas<br>veces");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 2);
        PANASSPanel.add(PANASLabel150, gridBagConstraints);

        PANASLabel152.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        PANASSPanel.add(PANASLabel152, gridBagConstraints);

        PANASLabel153.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        PANASSPanel.add(PANASLabel153, gridBagConstraints);

        PANASLabel154.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        PANASSPanel.add(PANASLabel154, gridBagConstraints);

        PANASLabel155.setText("6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        PANASSPanel.add(PANASLabel155, gridBagConstraints);

        PANASLabel114.setText("- Que le aconseje cuando tenga problemas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        PANASSPanel.add(PANASLabel114, gridBagConstraints);

        PANASLabel54.setText("- Que le ayude cuando tenga que estar en la cama");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 8);
        PANASSPanel.add(PANASLabel54, gridBagConstraints);

        PANASLabel55.setText("- Con quien pueda contar cuando necesite hablar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASSPanel.add(PANASLabel55, gridBagConstraints);

        PANASLabel56.setText("- Que le lleve al médico cuando lo necesite");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASSPanel.add(PANASLabel56, gridBagConstraints);

        PANASLabel57.setText("- Que le muestre amor y afecto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASSPanel.add(PANASLabel57, gridBagConstraints);

        PANASLabel58.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        PANASSPanel.add(PANASLabel58, gridBagConstraints);

        eptBtnGroup3.add(PANASToggleButton37);
        PANASToggleButton37.setText("2");
        PANASToggleButton37.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(PANASToggleButton37, gridBagConstraints);

        eptBtnGroup4.add(PANASToggleButton38);
        PANASToggleButton38.setText("3");
        PANASToggleButton38.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(PANASToggleButton38, gridBagConstraints);

        eptBtnGroup4.add(PANASToggleButton39);
        PANASToggleButton39.setText("5");
        PANASToggleButton39.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASSPanel.add(PANASToggleButton39, gridBagConstraints);

        eptBtnGroup6.add(PANASToggleButton40);
        PANASToggleButton40.setText("2");
        PANASToggleButton40.setName("afectivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(PANASToggleButton40, gridBagConstraints);

        eptBtnGroup6.add(PANASToggleButton41);
        PANASToggleButton41.setText("1");
        PANASToggleButton41.setName("afectivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(PANASToggleButton41, gridBagConstraints);

        PANASLabel156.setText("<html><center>La mayoría<br>de veces");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        PANASSPanel.add(PANASLabel156, gridBagConstraints);

        eptBtnGroup2.add(PANASBtn172);
        PANASBtn172.setText("4");
        PANASBtn172.setName("material"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(PANASBtn172, gridBagConstraints);

        eptBtnGroup3.add(PANASBtn1512);
        PANASBtn1512.setText("4");
        PANASBtn1512.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(PANASBtn1512, gridBagConstraints);

        eptBtnGroup4.add(PANASToggleButton42);
        PANASToggleButton42.setText("4");
        PANASToggleButton42.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(PANASToggleButton42, gridBagConstraints);

        eptBtnGroup6.add(PANASDBtn18);
        PANASDBtn18.setText("4");
        PANASDBtn18.setName("afectivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(PANASDBtn18, gridBagConstraints);

        eptBtnGroup5.add(PANASFBtn18);
        PANASFBtn18.setText("4");
        PANASFBtn18.setName("material"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(PANASFBtn18, gridBagConstraints);

        eptLabel157.setText("7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        PANASSPanel.add(eptLabel157, gridBagConstraints);

        eptLabel59.setText("- Con quien pasar un buen rato");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASSPanel.add(eptLabel59, gridBagConstraints);

        eptBtnGroup7.add(eptBtn18);
        eptBtn18.setText("1");
        eptBtn18.setName("ocio"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn18, gridBagConstraints);

        eptBtnGroup7.add(eptBtn20);
        eptBtn20.setText("2");
        eptBtn20.setName("ocio"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn20, gridBagConstraints);

        eptBtnGroup7.add(eptBtn21);
        eptBtn21.setText("3");
        eptBtn21.setName("ocio"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn21, gridBagConstraints);

        eptBtnGroup7.add(eptBtn22);
        eptBtn22.setText("4");
        eptBtn22.setName("ocio"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn22, gridBagConstraints);

        eptBtnGroup7.add(eptBtn23);
        eptBtn23.setText("5");
        eptBtn23.setName("ocio"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASSPanel.add(eptBtn23, gridBagConstraints);

        eptLabel158.setText("8");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        PANASSPanel.add(eptLabel158, gridBagConstraints);

        eptLabel60.setText("- Que le informe y ayude a entender la situación");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASSPanel.add(eptLabel60, gridBagConstraints);

        eptBtnGroup8.add(eptBtn24);
        eptBtn24.setText("1");
        eptBtn24.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn24, gridBagConstraints);

        eptBtnGroup8.add(eptBtn25);
        eptBtn25.setText("2");
        eptBtn25.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn25, gridBagConstraints);

        eptBtnGroup8.add(eptBtn26);
        eptBtn26.setText("3");
        eptBtn26.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn26, gridBagConstraints);

        eptBtnGroup8.add(eptBtn27);
        eptBtn27.setText("4");
        eptBtn27.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn27, gridBagConstraints);

        eptBtnGroup8.add(eptBtn28);
        eptBtn28.setText("5");
        eptBtn28.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASSPanel.add(eptBtn28, gridBagConstraints);

        eptLabel159.setText("9 - ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        PANASSPanel.add(eptLabel159, gridBagConstraints);

        eptLabel61.setText("<html> En quien confiar o con quién hablar de sí mismo<br> y sus preocupaciones");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASSPanel.add(eptLabel61, gridBagConstraints);

        eptBtnGroup9.add(eptBtn29);
        eptBtn29.setText("1");
        eptBtn29.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn29, gridBagConstraints);

        eptBtnGroup9.add(eptBtn30);
        eptBtn30.setText("2");
        eptBtn30.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn30, gridBagConstraints);

        eptBtnGroup9.add(eptBtn31);
        eptBtn31.setText("3");
        eptBtn31.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn31, gridBagConstraints);

        eptBtnGroup9.add(eptBtn32);
        eptBtn32.setText("4");
        eptBtn32.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn32, gridBagConstraints);

        eptBtnGroup9.add(eptBtn33);
        eptBtn33.setText("5");
        eptBtn33.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn33, gridBagConstraints);

        eptLabel160.setText("10 - ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        PANASSPanel.add(eptLabel160, gridBagConstraints);

        eptLabel62.setText("Que le abrace");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASSPanel.add(eptLabel62, gridBagConstraints);

        eptBtnGroup10.add(eptBtn34);
        eptBtn34.setText("1");
        eptBtn34.setName("afectivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn34, gridBagConstraints);

        eptBtnGroup10.add(eptBtn35);
        eptBtn35.setText("2");
        eptBtn35.setName("afectivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn35, gridBagConstraints);

        eptBtnGroup10.add(eptBtn36);
        eptBtn36.setText("3");
        eptBtn36.setName("afectivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn36, gridBagConstraints);

        eptBtnGroup10.add(eptBtn37);
        eptBtn37.setText("4");
        eptBtn37.setName("afectivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn37, gridBagConstraints);

        eptBtnGroup10.add(eptBtn38);
        eptBtn38.setText("5");
        eptBtn38.setName("afectivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASSPanel.add(eptBtn38, gridBagConstraints);

        eptLabel63.setText("Que le prepare la comida si no puede hacerlo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASSPanel.add(eptLabel63, gridBagConstraints);

        eptBtnGroup12.add(eptBtn39);
        eptBtn39.setText("1");
        eptBtn39.setName("material"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn39, gridBagConstraints);

        eptBtnGroup12.add(eptBtn40);
        eptBtn40.setText("2");
        eptBtn40.setName("material"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn40, gridBagConstraints);

        eptBtnGroup12.add(eptBtn41);
        eptBtn41.setText("3");
        eptBtn41.setName("material"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn41, gridBagConstraints);

        eptBtnGroup12.add(eptBtn42);
        eptBtn42.setText("4");
        eptBtn42.setName("material"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn42, gridBagConstraints);

        eptBtnGroup12.add(eptBtn43);
        eptBtn43.setText("5");
        eptBtn43.setName("material"); // NOI18N
        eptBtn43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eptBtn43ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASSPanel.add(eptBtn43, gridBagConstraints);

        eptLabel162.setText("11 - ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        PANASSPanel.add(eptLabel162, gridBagConstraints);

        eptLabel64.setText("Con quien pueda relajarse");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASSPanel.add(eptLabel64, gridBagConstraints);

        eptBtnGroup11.add(eptBtn44);
        eptBtn44.setText("1");
        eptBtn44.setName("ocio"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn44, gridBagConstraints);

        eptBtnGroup11.add(eptBtn45);
        eptBtn45.setText("2");
        eptBtn45.setName("ocio"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn45, gridBagConstraints);

        eptBtnGroup11.add(eptBtn46);
        eptBtn46.setText("3");
        eptBtn46.setName("ocio"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn46, gridBagConstraints);

        eptBtnGroup11.add(eptBtn47);
        eptBtn47.setText("4");
        eptBtn47.setName("ocio"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn47, gridBagConstraints);

        eptBtnGroup11.add(eptBtn48);
        eptBtn48.setText("5");
        eptBtn48.setName("ocio"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASSPanel.add(eptBtn48, gridBagConstraints);

        eptLabel163.setText("12 - ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        PANASSPanel.add(eptLabel163, gridBagConstraints);

        eptLabel164.setText("13 - ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        PANASSPanel.add(eptLabel164, gridBagConstraints);

        eptLabel66.setText("Cuyo consejo realmente desee");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASSPanel.add(eptLabel66, gridBagConstraints);

        eptBtnGroup13.add(eptBtn54);
        eptBtn54.setText("1");
        eptBtn54.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn54, gridBagConstraints);

        eptBtnGroup13.add(eptBtn55);
        eptBtn55.setText("2");
        eptBtn55.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn55, gridBagConstraints);

        eptBtnGroup13.add(eptBtn56);
        eptBtn56.setText("3");
        eptBtn56.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn56, gridBagConstraints);

        eptBtnGroup13.add(eptBtn57);
        eptBtn57.setText("4");
        eptBtn57.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn57, gridBagConstraints);

        eptBtnGroup13.add(eptBtn58);
        eptBtn58.setText("5");
        eptBtn58.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASSPanel.add(eptBtn58, gridBagConstraints);

        eptLabel165.setText("14 -");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        PANASSPanel.add(eptLabel165, gridBagConstraints);

        eptLabel67.setText("<html> Con quien hacer cosas que le sirvan para olvidar<br> sus problemas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASSPanel.add(eptLabel67, gridBagConstraints);

        eptBtnGroup14.add(eptBtn59);
        eptBtn59.setText("1");
        eptBtn59.setName("ocio"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn59, gridBagConstraints);

        eptBtnGroup14.add(eptBtn60);
        eptBtn60.setText("2");
        eptBtn60.setName("ocio"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn60, gridBagConstraints);

        eptBtnGroup14.add(eptBtn61);
        eptBtn61.setText("3");
        eptBtn61.setName("ocio"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn61, gridBagConstraints);

        eptBtnGroup14.add(eptBtn62);
        eptBtn62.setText("4");
        eptBtn62.setName("ocio"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn62, gridBagConstraints);

        eptBtnGroup14.add(eptBtn63);
        eptBtn63.setText("5");
        eptBtn63.setName("ocio"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn63, gridBagConstraints);

        eptLabel166.setText("15 -");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        PANASSPanel.add(eptLabel166, gridBagConstraints);

        eptLabel68.setText("<html>Que le ayude en sus tareas domésticas si<br> está enfermo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASSPanel.add(eptLabel68, gridBagConstraints);

        eptBtnGroup15.add(eptBtn64);
        eptBtn64.setText("1");
        eptBtn64.setName("material"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn64, gridBagConstraints);

        eptBtnGroup15.add(eptBtn65);
        eptBtn65.setText("2");
        eptBtn65.setName("material"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn65, gridBagConstraints);

        eptBtnGroup15.add(eptBtn66);
        eptBtn66.setText("3");
        eptBtn66.setName("material"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn66, gridBagConstraints);

        eptBtnGroup15.add(eptBtn67);
        eptBtn67.setText("4");
        eptBtn67.setName("material"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn67, gridBagConstraints);

        eptBtnGroup15.add(eptBtn68);
        eptBtn68.setText("5");
        eptBtn68.setName("material"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn68, gridBagConstraints);

        eptLabel167.setText("16 -");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        PANASSPanel.add(eptLabel167, gridBagConstraints);

        eptLabel69.setText("<html>Alguien con quien compartir sus temores y<br>problemas más íntimos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASSPanel.add(eptLabel69, gridBagConstraints);

        eptBtnGroup16.add(eptBtn69);
        eptBtn69.setText("1");
        eptBtn69.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn69, gridBagConstraints);

        eptBtnGroup16.add(eptBtn70);
        eptBtn70.setText("2");
        eptBtn70.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn70, gridBagConstraints);

        eptBtnGroup16.add(eptBtn71);
        eptBtn71.setText("3");
        eptBtn71.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn71, gridBagConstraints);

        eptBtnGroup16.add(eptBtn72);
        eptBtn72.setText("4");
        eptBtn72.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn72, gridBagConstraints);

        eptBtnGroup16.add(eptBtn73);
        eptBtn73.setText("5");
        eptBtn73.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn73, gridBagConstraints);

        eptLabel168.setText("17 -");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 19;
        PANASSPanel.add(eptLabel168, gridBagConstraints);

        eptLabel70.setText("<html>Que le aconseje cómo resolver sus problemas<br> personales");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASSPanel.add(eptLabel70, gridBagConstraints);

        eptBtnGroup17.add(eptBtn74);
        eptBtn74.setText("1");
        eptBtn74.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn74, gridBagConstraints);

        eptBtnGroup17.add(eptBtn75);
        eptBtn75.setText("2");
        eptBtn75.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn75, gridBagConstraints);

        eptBtnGroup17.add(eptBtn76);
        eptBtn76.setText("3");
        eptBtn76.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn76, gridBagConstraints);

        eptBtnGroup17.add(eptBtn77);
        eptBtn77.setText("4");
        eptBtn77.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn77, gridBagConstraints);

        eptBtnGroup17.add(eptBtn78);
        eptBtn78.setText("5");
        eptBtn78.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn78, gridBagConstraints);

        eptLabel169.setText("18 - ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        PANASSPanel.add(eptLabel169, gridBagConstraints);

        eptLabel71.setText("Con quien divertirse");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASSPanel.add(eptLabel71, gridBagConstraints);

        eptBtnGroup18.add(eptBtn79);
        eptBtn79.setText("1");
        eptBtn79.setName("ocio"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn79, gridBagConstraints);

        eptBtnGroup18.add(eptBtn80);
        eptBtn80.setText("2");
        eptBtn80.setName("ocio"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn80, gridBagConstraints);

        eptBtnGroup18.add(eptBtn81);
        eptBtn81.setText("3");
        eptBtn81.setName("ocio"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn81, gridBagConstraints);

        eptBtnGroup18.add(eptBtn82);
        eptBtn82.setText("4");
        eptBtn82.setName("ocio"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn82, gridBagConstraints);

        eptBtnGroup18.add(eptBtn83);
        eptBtn83.setText("5");
        eptBtn83.setName("ocio"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASSPanel.add(eptBtn83, gridBagConstraints);

        eptLabel170.setText("19 - ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 21;
        PANASSPanel.add(eptLabel170, gridBagConstraints);

        eptLabel72.setText("Que comprenda sus problemas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASSPanel.add(eptLabel72, gridBagConstraints);

        eptBtnGroup19.add(eptBtn84);
        eptBtn84.setText("1");
        eptBtn84.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn84, gridBagConstraints);

        eptBtnGroup19.add(eptBtn85);
        eptBtn85.setText("2");
        eptBtn85.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn85, gridBagConstraints);

        eptBtnGroup19.add(eptBtn86);
        eptBtn86.setText("3");
        eptBtn86.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn86, gridBagConstraints);

        eptBtnGroup19.add(eptBtn87);
        eptBtn87.setText("4");
        eptBtn87.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn87, gridBagConstraints);

        eptBtnGroup19.add(eptBtn88);
        eptBtn88.setText("5");
        eptBtn88.setName("emocional"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASSPanel.add(eptBtn88, gridBagConstraints);

        eptLabel171.setText("20 - ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        PANASSPanel.add(eptLabel171, gridBagConstraints);

        eptLabel73.setText("A quien amar y hacerle sentirse querido");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASSPanel.add(eptLabel73, gridBagConstraints);

        eptBtnGroup20.add(eptBtn89);
        eptBtn89.setText("1");
        eptBtn89.setName("afectivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn89, gridBagConstraints);

        eptBtnGroup20.add(eptBtn90);
        eptBtn90.setText("2");
        eptBtn90.setName("afectivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn90, gridBagConstraints);

        eptBtnGroup20.add(eptBtn91);
        eptBtn91.setText("3");
        eptBtn91.setName("afectivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn91, gridBagConstraints);

        eptBtnGroup20.add(eptBtn92);
        eptBtn92.setText("4");
        eptBtn92.setName("afectivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASSPanel.add(eptBtn92, gridBagConstraints);

        eptBtnGroup20.add(eptBtn93);
        eptBtn93.setText("5");
        eptBtn93.setName("afectivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASSPanel.add(eptBtn93, gridBagConstraints);

        PANASLabel74.setText("CUESTIONES: ¿Cuenta con ALGUIEN?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASSPanel.add(PANASLabel74, gridBagConstraints);

        PANASLabel32.setText("<html>La gente busca a otras personas para encontrar compañía, asistencia u otros tipos de ayuda. <br> ¿Con qué frecuencia Vd. dispone de cada uno de los siguientes tipos de apoyo cuando lo necesita? <br> (Seleccione los números de cada fila). <br></html>");

        PANASLabel217.setText("Apoyo Emocional:");

        ApoyoEmocional.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ApoyoEmocional.setText("0");

        PANASLabel218.setText("Ayuda Material:");

        AyudaMaterial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AyudaMaterial.setText("0");

        PANASLabel219.setText("<html> Relaciones sociales <br> de ocio y distracción:");

        SocialOcio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SocialOcio.setText("0");

        PANASLabel34.setText("<html>Las siguientes preguntas se refieren al apoyo o ayuda de que Vd. dispone: <br> 1. Aproximadamente, ¿cuántos amigos íntimos o familiares cercanos tiene Vd.? <br>(Personas con las que se encuentra a gusto y puede hablar de todo lo que se le ocurre). <br></html>");

        PANASLabel53.setText("<html><b>Escriba el Nº de amigos íntimos y familiares cercanos:");

        MOSFamilia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOSFamiliaActionPerformed(evt);
            }
        });

        PANASLabel220.setText("Apoyo Afectivo:");

        ApoyoAfectivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ApoyoAfectivo.setText("0");

        PANASLabel221.setText("<html> Indice global <br> de apoyo social:");

        MOSTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        MOSTotal.setText("0");

        PANASLabel65.setText("<html>Adaptado de: Revilla L, Luna J, Bailón E, Medina I. Validación de cuestonario MOS de apoyo social en Atención Primaria. <br> Medicina de Familia (And). 2005; 10(6): 10-18");

        javax.swing.GroupLayout PANASPanelLayout = new javax.swing.GroupLayout(PANASPanel);
        PANASPanel.setLayout(PANASPanelLayout);
        PANASPanelLayout.setHorizontalGroup(
            PANASPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANASPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PANASPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PANASLabel33)
                    .addGroup(PANASPanelLayout.createSequentialGroup()
                        .addGroup(PANASPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PANASPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(PANASPanelLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(PANASLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)
                                    .addComponent(MOSAmigos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(MOSFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(8, 8, 8))
                                .addComponent(PANASLabel34, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PANASLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(PANASPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PANASPanelLayout.createSequentialGroup()
                                .addComponent(PANASLabel217)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ApoyoEmocional))
                            .addGroup(PANASPanelLayout.createSequentialGroup()
                                .addComponent(PANASLabel218)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AyudaMaterial))
                            .addGroup(PANASPanelLayout.createSequentialGroup()
                                .addComponent(PANASLabel220)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ApoyoAfectivo))
                            .addGroup(PANASPanelLayout.createSequentialGroup()
                                .addComponent(PANASLabel221, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MOSTotal))
                            .addGroup(PANASPanelLayout.createSequentialGroup()
                                .addComponent(PANASLabel219, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SocialOcio))))
                    .addGroup(PANASPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(PANASPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PANASLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PANASSPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(47, 47, 47))
        );
        PANASPanelLayout.setVerticalGroup(
            PANASPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANASPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PANASLabel33)
                .addGroup(PANASPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANASPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PANASLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(PANASPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PANASLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MOSAmigos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MOSFamilia, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(PANASLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(PANASPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(PANASPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PANASLabel217)
                            .addComponent(ApoyoEmocional))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PANASPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PANASLabel218)
                            .addComponent(AyudaMaterial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PANASPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PANASLabel219, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SocialOcio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PANASPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PANASLabel220)
                            .addComponent(ApoyoAfectivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PANASPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PANASLabel221, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MOSTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(PANASSPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PANASLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        eptScroll.setViewportView(PANASPanel);

        add(eptScroll, "card1");
    }// </editor-fold>//GEN-END:initComponents

    private void MOSFamiliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOSFamiliaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MOSFamiliaActionPerformed

    private void eptBtn43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eptBtn43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eptBtn43ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApoyoAfectivo;
    private javax.swing.JLabel ApoyoEmocional;
    private javax.swing.JLabel AyudaMaterial;
    private javax.swing.JTextField MOSAmigos;
    private javax.swing.JTextField MOSFamilia;
    private javax.swing.JLabel MOSTotal;
    private javax.swing.JToggleButton PANASBtn141;
    private javax.swing.JToggleButton PANASBtn1411;
    private javax.swing.JToggleButton PANASBtn151;
    private javax.swing.JToggleButton PANASBtn1511;
    private javax.swing.JToggleButton PANASBtn1512;
    private javax.swing.JToggleButton PANASBtn161;
    private javax.swing.JToggleButton PANASBtn1611;
    private javax.swing.JToggleButton PANASBtn171;
    private javax.swing.JToggleButton PANASBtn1711;
    private javax.swing.JToggleButton PANASBtn172;
    private javax.swing.JToggleButton PANASDBtn14;
    private javax.swing.JToggleButton PANASDBtn15;
    private javax.swing.JToggleButton PANASDBtn16;
    private javax.swing.JToggleButton PANASDBtn17;
    private javax.swing.JToggleButton PANASDBtn18;
    private javax.swing.JToggleButton PANASFBtn14;
    private javax.swing.JToggleButton PANASFBtn15;
    private javax.swing.JToggleButton PANASFBtn16;
    private javax.swing.JToggleButton PANASFBtn17;
    private javax.swing.JToggleButton PANASFBtn18;
    private javax.swing.JLabel PANASLabel11;
    private javax.swing.JLabel PANASLabel112;
    private javax.swing.JLabel PANASLabel114;
    private javax.swing.JLabel PANASLabel149;
    private javax.swing.JLabel PANASLabel150;
    private javax.swing.JLabel PANASLabel152;
    private javax.swing.JLabel PANASLabel153;
    private javax.swing.JLabel PANASLabel154;
    private javax.swing.JLabel PANASLabel155;
    private javax.swing.JLabel PANASLabel156;
    private javax.swing.JLabel PANASLabel217;
    private javax.swing.JLabel PANASLabel218;
    private javax.swing.JLabel PANASLabel219;
    private javax.swing.JLabel PANASLabel220;
    private javax.swing.JLabel PANASLabel221;
    private javax.swing.JLabel PANASLabel32;
    private javax.swing.JLabel PANASLabel33;
    private javax.swing.JLabel PANASLabel34;
    private javax.swing.JLabel PANASLabel53;
    private javax.swing.JLabel PANASLabel54;
    private javax.swing.JLabel PANASLabel55;
    private javax.swing.JLabel PANASLabel56;
    private javax.swing.JLabel PANASLabel57;
    private javax.swing.JLabel PANASLabel58;
    private javax.swing.JLabel PANASLabel65;
    private javax.swing.JLabel PANASLabel74;
    private javax.swing.JPanel PANASPanel;
    private javax.swing.JPanel PANASSPanel;
    private javax.swing.JToggleButton PANASToggleButton37;
    private javax.swing.JToggleButton PANASToggleButton38;
    private javax.swing.JToggleButton PANASToggleButton39;
    private javax.swing.JToggleButton PANASToggleButton40;
    private javax.swing.JToggleButton PANASToggleButton41;
    private javax.swing.JToggleButton PANASToggleButton42;
    private javax.swing.JLabel SocialOcio;
    private javax.swing.JToggleButton eptBtn18;
    private javax.swing.JToggleButton eptBtn20;
    private javax.swing.JToggleButton eptBtn21;
    private javax.swing.JToggleButton eptBtn22;
    private javax.swing.JToggleButton eptBtn23;
    private javax.swing.JToggleButton eptBtn24;
    private javax.swing.JToggleButton eptBtn25;
    private javax.swing.JToggleButton eptBtn26;
    private javax.swing.JToggleButton eptBtn27;
    private javax.swing.JToggleButton eptBtn28;
    private javax.swing.JToggleButton eptBtn29;
    private javax.swing.JToggleButton eptBtn30;
    private javax.swing.JToggleButton eptBtn31;
    private javax.swing.JToggleButton eptBtn32;
    private javax.swing.JToggleButton eptBtn33;
    private javax.swing.JToggleButton eptBtn34;
    private javax.swing.JToggleButton eptBtn35;
    private javax.swing.JToggleButton eptBtn36;
    private javax.swing.JToggleButton eptBtn37;
    private javax.swing.JToggleButton eptBtn38;
    private javax.swing.JToggleButton eptBtn39;
    private javax.swing.JToggleButton eptBtn40;
    private javax.swing.JToggleButton eptBtn41;
    private javax.swing.JToggleButton eptBtn42;
    private javax.swing.JToggleButton eptBtn43;
    private javax.swing.JToggleButton eptBtn44;
    private javax.swing.JToggleButton eptBtn45;
    private javax.swing.JToggleButton eptBtn46;
    private javax.swing.JToggleButton eptBtn47;
    private javax.swing.JToggleButton eptBtn48;
    private javax.swing.JToggleButton eptBtn54;
    private javax.swing.JToggleButton eptBtn55;
    private javax.swing.JToggleButton eptBtn56;
    private javax.swing.JToggleButton eptBtn57;
    private javax.swing.JToggleButton eptBtn58;
    private javax.swing.JToggleButton eptBtn59;
    private javax.swing.JToggleButton eptBtn60;
    private javax.swing.JToggleButton eptBtn61;
    private javax.swing.JToggleButton eptBtn62;
    private javax.swing.JToggleButton eptBtn63;
    private javax.swing.JToggleButton eptBtn64;
    private javax.swing.JToggleButton eptBtn65;
    private javax.swing.JToggleButton eptBtn66;
    private javax.swing.JToggleButton eptBtn67;
    private javax.swing.JToggleButton eptBtn68;
    private javax.swing.JToggleButton eptBtn69;
    private javax.swing.JToggleButton eptBtn70;
    private javax.swing.JToggleButton eptBtn71;
    private javax.swing.JToggleButton eptBtn72;
    private javax.swing.JToggleButton eptBtn73;
    private javax.swing.JToggleButton eptBtn74;
    private javax.swing.JToggleButton eptBtn75;
    private javax.swing.JToggleButton eptBtn76;
    private javax.swing.JToggleButton eptBtn77;
    private javax.swing.JToggleButton eptBtn78;
    private javax.swing.JToggleButton eptBtn79;
    private javax.swing.JToggleButton eptBtn80;
    private javax.swing.JToggleButton eptBtn81;
    private javax.swing.JToggleButton eptBtn82;
    private javax.swing.JToggleButton eptBtn83;
    private javax.swing.JToggleButton eptBtn84;
    private javax.swing.JToggleButton eptBtn85;
    private javax.swing.JToggleButton eptBtn86;
    private javax.swing.JToggleButton eptBtn87;
    private javax.swing.JToggleButton eptBtn88;
    private javax.swing.JToggleButton eptBtn89;
    private javax.swing.JToggleButton eptBtn90;
    private javax.swing.JToggleButton eptBtn91;
    private javax.swing.JToggleButton eptBtn92;
    private javax.swing.JToggleButton eptBtn93;
    private javax.swing.ButtonGroup eptBtnGroup1;
    private javax.swing.ButtonGroup eptBtnGroup10;
    private javax.swing.ButtonGroup eptBtnGroup11;
    private javax.swing.ButtonGroup eptBtnGroup12;
    private javax.swing.ButtonGroup eptBtnGroup13;
    private javax.swing.ButtonGroup eptBtnGroup14;
    private javax.swing.ButtonGroup eptBtnGroup15;
    private javax.swing.ButtonGroup eptBtnGroup16;
    private javax.swing.ButtonGroup eptBtnGroup17;
    private javax.swing.ButtonGroup eptBtnGroup18;
    private javax.swing.ButtonGroup eptBtnGroup19;
    private javax.swing.ButtonGroup eptBtnGroup2;
    private javax.swing.ButtonGroup eptBtnGroup20;
    private javax.swing.ButtonGroup eptBtnGroup3;
    private javax.swing.ButtonGroup eptBtnGroup4;
    private javax.swing.ButtonGroup eptBtnGroup5;
    private javax.swing.ButtonGroup eptBtnGroup6;
    private javax.swing.ButtonGroup eptBtnGroup7;
    private javax.swing.ButtonGroup eptBtnGroup8;
    private javax.swing.ButtonGroup eptBtnGroup9;
    private javax.swing.JLabel eptLabel157;
    private javax.swing.JLabel eptLabel158;
    private javax.swing.JLabel eptLabel159;
    private javax.swing.JLabel eptLabel160;
    private javax.swing.JLabel eptLabel162;
    private javax.swing.JLabel eptLabel163;
    private javax.swing.JLabel eptLabel164;
    private javax.swing.JLabel eptLabel165;
    private javax.swing.JLabel eptLabel166;
    private javax.swing.JLabel eptLabel167;
    private javax.swing.JLabel eptLabel168;
    private javax.swing.JLabel eptLabel169;
    private javax.swing.JLabel eptLabel170;
    private javax.swing.JLabel eptLabel171;
    private javax.swing.JLabel eptLabel59;
    private javax.swing.JLabel eptLabel60;
    private javax.swing.JLabel eptLabel61;
    private javax.swing.JLabel eptLabel62;
    private javax.swing.JLabel eptLabel63;
    private javax.swing.JLabel eptLabel64;
    private javax.swing.JLabel eptLabel66;
    private javax.swing.JLabel eptLabel67;
    private javax.swing.JLabel eptLabel68;
    private javax.swing.JLabel eptLabel69;
    private javax.swing.JLabel eptLabel70;
    private javax.swing.JLabel eptLabel71;
    private javax.swing.JLabel eptLabel72;
    private javax.swing.JLabel eptLabel73;
    private javax.swing.JScrollPane eptScroll;
    // End of variables declaration//GEN-END:variables
}
