/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.tests;

import controlador.Utils;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Properties;
import javax.swing.AbstractButton;
import javax.swing.JCheckBox;
import javax.swing.JToggleButton;
import model.Pacient;

/**
 *
 * @author a630703
 */
public class NPI extends Test {

    /**
     * Creates new form Test
     *
     * @param pacientActual
     */
    public NPI(Pacient pacientActual) {
        super(pacientActual);
        initComponents();

        label = "NPI";
        numPaginesTotal = this.getComponentCount();
        
        initNPI();
        
        Utils.setActionCommands(npiPanel);
    }

    @Override
    public void guardarResultats(Properties prop) {
        // NPI
        Utils.setProperty(prop,"npiTotal",npiTotal);
    }

    private void initNPI() {

        for (Component com : npiPanel.getComponents()){
            if (com instanceof JCheckBox || com instanceof JToggleButton){
                ((AbstractButton)com).addActionListener(npiActionListener);
            }
        }
    }

    private ActionListener npiActionListener = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            actualitzaPuntuacioNpi();
        }
    };

    private void actualitzaPuntuacioNpi() {
        int count = 0;

        int tempPunt = Utils.getPunctuationFromButtonGroup(npiFreqBtnGroup1)*Utils.getPunctuationFromButtonGroup(npiGravBtnGroup1);
        npiTotal1.setText(tempPunt+"");
        if (!npiCheck1.isSelected()) count+=tempPunt;

        tempPunt = Utils.getPunctuationFromButtonGroup(npiFreqBtnGroup2)*Utils.getPunctuationFromButtonGroup(npiGravBtnGroup2);
        npiTotal2.setText(tempPunt+"");
        if (!npiCheck2.isSelected()) count+=tempPunt;

        tempPunt = Utils.getPunctuationFromButtonGroup(npiFreqBtnGroup3)*Utils.getPunctuationFromButtonGroup(npiGravBtnGroup3);
        npiTotal3.setText(tempPunt+"");
        if (!npiCheck3.isSelected()) count+=tempPunt;

        tempPunt = Utils.getPunctuationFromButtonGroup(npiFreqBtnGroup4)*Utils.getPunctuationFromButtonGroup(npiGravBtnGroup4);
        npiTotal4.setText(tempPunt+"");
        if (!npiCheck4.isSelected()) count+=tempPunt;

        tempPunt = Utils.getPunctuationFromButtonGroup(npiFreqBtnGroup5)*Utils.getPunctuationFromButtonGroup(npiGravBtnGroup5);
        npiTotal5.setText(tempPunt+"");
        if (!npiCheck5.isSelected()) count+=tempPunt;

        tempPunt = Utils.getPunctuationFromButtonGroup(npiFreqBtnGroup6)*Utils.getPunctuationFromButtonGroup(npiGravBtnGroup6);
        npiTotal6.setText(tempPunt+"");
        if (!npiCheck6.isSelected()) count+=tempPunt;

        tempPunt = Utils.getPunctuationFromButtonGroup(npiFreqBtnGroup7)*Utils.getPunctuationFromButtonGroup(npiGravBtnGroup7);
        npiTotal7.setText(tempPunt+"");
        if (!npiCheck7.isSelected()) count+=tempPunt;

        tempPunt = Utils.getPunctuationFromButtonGroup(npiFreqBtnGroup8)*Utils.getPunctuationFromButtonGroup(npiGravBtnGroup8);
        npiTotal8.setText(tempPunt+"");
        if (!npiCheck8.isSelected()) count+=tempPunt;

        tempPunt = Utils.getPunctuationFromButtonGroup(npiFreqBtnGroup9)*Utils.getPunctuationFromButtonGroup(npiGravBtnGroup9);
        npiTotal9.setText(tempPunt+"");
        if (!npiCheck9.isSelected()) count+=tempPunt;

        tempPunt = Utils.getPunctuationFromButtonGroup(npiFreqBtnGroup10)*Utils.getPunctuationFromButtonGroup(npiGravBtnGroup10);
        npiTotal10.setText(tempPunt+"");
        if (!npiCheck10.isSelected()) count+=tempPunt;

        npiTotal.setText(count+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        npiFreqBtnGroup1 = new javax.swing.ButtonGroup();
        npiFreqBtnGroup2 = new javax.swing.ButtonGroup();
        npiFreqBtnGroup3 = new javax.swing.ButtonGroup();
        npiFreqBtnGroup4 = new javax.swing.ButtonGroup();
        npiFreqBtnGroup5 = new javax.swing.ButtonGroup();
        npiFreqBtnGroup6 = new javax.swing.ButtonGroup();
        npiFreqBtnGroup7 = new javax.swing.ButtonGroup();
        npiFreqBtnGroup8 = new javax.swing.ButtonGroup();
        npiFreqBtnGroup9 = new javax.swing.ButtonGroup();
        npiFreqBtnGroup10 = new javax.swing.ButtonGroup();
        npiGravBtnGroup1 = new javax.swing.ButtonGroup();
        npiGravBtnGroup2 = new javax.swing.ButtonGroup();
        npiGravBtnGroup3 = new javax.swing.ButtonGroup();
        npiGravBtnGroup4 = new javax.swing.ButtonGroup();
        npiGravBtnGroup5 = new javax.swing.ButtonGroup();
        npiGravBtnGroup6 = new javax.swing.ButtonGroup();
        npiGravBtnGroup7 = new javax.swing.ButtonGroup();
        npiGravBtnGroup8 = new javax.swing.ButtonGroup();
        npiGravBtnGroup9 = new javax.swing.ButtonGroup();
        npiGravBtnGroup10 = new javax.swing.ButtonGroup();
        npiScroll = new javax.swing.JScrollPane();
        npi2Panel = new javax.swing.JPanel();
        jLabel106npi = new javax.swing.JLabel();
        npiPanel = new javax.swing.JPanel();
        orientacioBtn20npi = new javax.swing.JToggleButton();
        memoBtn20npi = new javax.swing.JToggleButton();
        raoBtn19npi = new javax.swing.JToggleButton();
        raoBtn21npi = new javax.swing.JToggleButton();
        activitatsDBtn22npi = new javax.swing.JToggleButton();
        cuidatBtn15npi = new javax.swing.JToggleButton();
        jLabel166npi = new javax.swing.JLabel();
        jLabel191npi = new javax.swing.JLabel();
        jLabel83npi = new javax.swing.JLabel();
        jLabel84npi = new javax.swing.JLabel();
        jLabel85npi = new javax.swing.JLabel();
        jLabel86npi = new javax.swing.JLabel();
        jLabel192npi = new javax.swing.JLabel();
        jLabel193npi = new javax.swing.JLabel();
        jLabel194npi = new javax.swing.JLabel();
        jLabel202npi = new javax.swing.JLabel();
        jToggleButton118npi = new javax.swing.JToggleButton();
        jToggleButton122npi = new javax.swing.JToggleButton();
        jToggleButton134npi = new javax.swing.JToggleButton();
        jToggleButton138npi = new javax.swing.JToggleButton();
        jToggleButton142npi = new javax.swing.JToggleButton();
        jToggleButton146npi = new javax.swing.JToggleButton();
        jToggleButton147npi = new javax.swing.JToggleButton();
        jLabel206npi = new javax.swing.JLabel();
        activitatsDBtn25npi = new javax.swing.JToggleButton();
        jToggleButton150npi = new javax.swing.JToggleButton();
        jToggleButton151npi = new javax.swing.JToggleButton();
        jToggleButton152npi = new javax.swing.JToggleButton();
        jToggleButton153npi = new javax.swing.JToggleButton();
        jLabel4npi = new javax.swing.JLabel();
        jLabel5npi = new javax.swing.JLabel();
        jLabel6npi = new javax.swing.JLabel();
        jLabel7npi = new javax.swing.JLabel();
        jLabel8npi = new javax.swing.JLabel();
        npiCheck9 = new javax.swing.JCheckBox();
        npiCheck1 = new javax.swing.JCheckBox();
        npiCheck2 = new javax.swing.JCheckBox();
        npiCheck3 = new javax.swing.JCheckBox();
        npiCheck4 = new javax.swing.JCheckBox();
        npiCheck5 = new javax.swing.JCheckBox();
        npiCheck6 = new javax.swing.JCheckBox();
        npiCheck7 = new javax.swing.JCheckBox();
        npiCheck8 = new javax.swing.JCheckBox();
        raoBtn27npi = new javax.swing.JToggleButton();
        jToggleButton158npi = new javax.swing.JToggleButton();
        jToggleButton159npi = new javax.swing.JToggleButton();
        cuidatBtn20npi = new javax.swing.JToggleButton();
        jToggleButton160npi = new javax.swing.JToggleButton();
        raoBtn28npi = new javax.swing.JToggleButton();
        jToggleButton161npi = new javax.swing.JToggleButton();
        jToggleButton162npi = new javax.swing.JToggleButton();
        cuidatBtn21npi = new javax.swing.JToggleButton();
        jToggleButton163npi = new javax.swing.JToggleButton();
        jToggleButton164npi = new javax.swing.JToggleButton();
        jToggleButton165npi = new javax.swing.JToggleButton();
        jToggleButton166npi = new javax.swing.JToggleButton();
        jToggleButton167npi = new javax.swing.JToggleButton();
        jToggleButton168npi = new javax.swing.JToggleButton();
        jToggleButton169npi = new javax.swing.JToggleButton();
        jToggleButton170npi = new javax.swing.JToggleButton();
        jToggleButton171npi = new javax.swing.JToggleButton();
        activitatsDBtn26npi = new javax.swing.JToggleButton();
        jToggleButton172npi = new javax.swing.JToggleButton();
        jToggleButton173npi = new javax.swing.JToggleButton();
        jToggleButton174npi = new javax.swing.JToggleButton();
        activitatsDBtn27npi = new javax.swing.JToggleButton();
        jToggleButton175npi = new javax.swing.JToggleButton();
        jToggleButton176npi = new javax.swing.JToggleButton();
        jToggleButton177npi = new javax.swing.JToggleButton();
        jToggleButton178npi = new javax.swing.JToggleButton();
        activitatsDBtn28npi = new javax.swing.JToggleButton();
        jToggleButton179npi = new javax.swing.JToggleButton();
        jToggleButton180npi = new javax.swing.JToggleButton();
        jToggleButton181npi = new javax.swing.JToggleButton();
        jToggleButton182npi = new javax.swing.JToggleButton();
        activitatsDBtn29npi = new javax.swing.JToggleButton();
        jToggleButton183npi = new javax.swing.JToggleButton();
        jToggleButton184npi = new javax.swing.JToggleButton();
        jToggleButton185npi = new javax.swing.JToggleButton();
        jToggleButton186npi = new javax.swing.JToggleButton();
        activitatsDBtn30npi = new javax.swing.JToggleButton();
        jToggleButton187npi = new javax.swing.JToggleButton();
        jToggleButton188npi = new javax.swing.JToggleButton();
        jToggleButton189npi = new javax.swing.JToggleButton();
        jToggleButton190npi = new javax.swing.JToggleButton();
        activitatsDBtn31npi = new javax.swing.JToggleButton();
        jToggleButton191npi = new javax.swing.JToggleButton();
        jToggleButton192npi = new javax.swing.JToggleButton();
        jToggleButton193npi = new javax.swing.JToggleButton();
        jToggleButton194npi = new javax.swing.JToggleButton();
        activitatsDBtn32npi = new javax.swing.JToggleButton();
        jToggleButton195npi = new javax.swing.JToggleButton();
        jToggleButton196npi = new javax.swing.JToggleButton();
        jToggleButton197npi = new javax.swing.JToggleButton();
        jToggleButton198npi = new javax.swing.JToggleButton();
        activitatsDBtn33npi = new javax.swing.JToggleButton();
        jToggleButton199npi = new javax.swing.JToggleButton();
        jToggleButton200npi = new javax.swing.JToggleButton();
        jToggleButton201npi = new javax.swing.JToggleButton();
        jToggleButton202npi = new javax.swing.JToggleButton();
        activitatsDBtn34npi = new javax.swing.JToggleButton();
        jToggleButton203npi = new javax.swing.JToggleButton();
        jToggleButton204npi = new javax.swing.JToggleButton();
        jToggleButton205npi = new javax.swing.JToggleButton();
        jToggleButton206npi = new javax.swing.JToggleButton();
        npiCheck10 = new javax.swing.JCheckBox();
        npiTotal1 = new javax.swing.JLabel();
        npiTotal = new javax.swing.JLabel();
        npiTotal3 = new javax.swing.JLabel();
        npiTotal2 = new javax.swing.JLabel();
        npiTotal4 = new javax.swing.JLabel();
        npiTotal5 = new javax.swing.JLabel();
        npiTotal6 = new javax.swing.JLabel();
        npiTotal8 = new javax.swing.JLabel();
        npiTotal9 = new javax.swing.JLabel();
        npiTotal10 = new javax.swing.JLabel();
        npiTotal7 = new javax.swing.JLabel();
        jLabel144npi = new javax.swing.JLabel();
        jLabel145npi = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        jLabel106npi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel106npi.setText("<html><center><b>INVENTARI NEUROPSIQUIÀTRIC DE CUMMINGS - NPI</b>");

        npiPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Trastorns neuropsiquiàtrics (màxima puntuació: 120)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        npiPanel.setLayout(new java.awt.GridBagLayout());

        npiFreqBtnGroup2.add(orientacioBtn20npi);
        orientacioBtn20npi.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(orientacioBtn20npi, gridBagConstraints);

        npiFreqBtnGroup1.add(memoBtn20npi);
        memoBtn20npi.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(memoBtn20npi, gridBagConstraints);

        npiFreqBtnGroup3.add(raoBtn19npi);
        raoBtn19npi.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(raoBtn19npi, gridBagConstraints);

        npiFreqBtnGroup7.add(raoBtn21npi);
        raoBtn21npi.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(raoBtn21npi, gridBagConstraints);

        npiFreqBtnGroup4.add(activitatsDBtn22npi);
        activitatsDBtn22npi.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(activitatsDBtn22npi, gridBagConstraints);

        npiFreqBtnGroup6.add(cuidatBtn15npi);
        cuidatBtn15npi.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(cuidatBtn15npi, gridBagConstraints);

        jLabel166npi.setText("Depressió/disfòria");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(jLabel166npi, gridBagConstraints);

        jLabel191npi.setText("<html><center><b>Total (Freqüència x<br>Gravetat)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 3, 1);
        npiPanel.add(jLabel191npi, gridBagConstraints);

        jLabel83npi.setText("Puntuació total");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(jLabel83npi, gridBagConstraints);

        jLabel84npi.setText("Deliris");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        npiPanel.add(jLabel84npi, gridBagConstraints);

        jLabel85npi.setText("Agitació");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        npiPanel.add(jLabel85npi, gridBagConstraints);

        jLabel86npi.setText("Ansietat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        npiPanel.add(jLabel86npi, gridBagConstraints);

        jLabel192npi.setText("Eufòr/alegria");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(jLabel192npi, gridBagConstraints);

        jLabel193npi.setText("Apatía/indiferència");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(jLabel193npi, gridBagConstraints);

        jLabel194npi.setText("Desinhibició");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(jLabel194npi, gridBagConstraints);

        jLabel202npi.setText("Irritabilitat/labilitat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(jLabel202npi, gridBagConstraints);

        npiGravBtnGroup8.add(jToggleButton118npi);
        jToggleButton118npi.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 0);
        npiPanel.add(jToggleButton118npi, gridBagConstraints);

        npiFreqBtnGroup5.add(jToggleButton122npi);
        jToggleButton122npi.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton122npi, gridBagConstraints);

        npiFreqBtnGroup6.add(jToggleButton134npi);
        jToggleButton134npi.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton134npi, gridBagConstraints);

        npiFreqBtnGroup7.add(jToggleButton138npi);
        jToggleButton138npi.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton138npi, gridBagConstraints);

        npiFreqBtnGroup5.add(jToggleButton142npi);
        jToggleButton142npi.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton142npi, gridBagConstraints);

        npiFreqBtnGroup10.add(jToggleButton146npi);
        jToggleButton146npi.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton146npi, gridBagConstraints);

        npiGravBtnGroup10.add(jToggleButton147npi);
        jToggleButton147npi.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 0);
        npiPanel.add(jToggleButton147npi, gridBagConstraints);

        jLabel206npi.setText("<html><b>No valorable<br>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(1, 3, 3, 3);
        npiPanel.add(jLabel206npi, gridBagConstraints);

        npiGravBtnGroup6.add(activitatsDBtn25npi);
        activitatsDBtn25npi.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(activitatsDBtn25npi, gridBagConstraints);

        npiGravBtnGroup7.add(jToggleButton150npi);
        jToggleButton150npi.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton150npi, gridBagConstraints);

        npiGravBtnGroup8.add(jToggleButton151npi);
        jToggleButton151npi.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton151npi, gridBagConstraints);

        npiGravBtnGroup9.add(jToggleButton152npi);
        jToggleButton152npi.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton152npi, gridBagConstraints);

        npiGravBtnGroup10.add(jToggleButton153npi);
        jToggleButton153npi.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton153npi, gridBagConstraints);

        jLabel4npi.setText("<html><b>Transtorn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(jLabel4npi, gridBagConstraints);

        jLabel5npi.setText("<html><b>Freqüència");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(jLabel5npi, gridBagConstraints);

        jLabel6npi.setText("Conducta motora sense finalitat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(jLabel6npi, gridBagConstraints);

        jLabel7npi.setText("<html><b>Gravetat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(jLabel7npi, gridBagConstraints);

        jLabel8npi.setText("Al·lucinacions");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(jLabel8npi, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(npiCheck9, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(npiCheck1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(npiCheck2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(npiCheck3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(npiCheck4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(npiCheck5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(npiCheck6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(npiCheck7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(npiCheck8, gridBagConstraints);

        npiGravBtnGroup7.add(raoBtn27npi);
        raoBtn27npi.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 0);
        npiPanel.add(raoBtn27npi, gridBagConstraints);

        npiGravBtnGroup5.add(jToggleButton158npi);
        jToggleButton158npi.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 0);
        npiPanel.add(jToggleButton158npi, gridBagConstraints);

        npiGravBtnGroup4.add(jToggleButton159npi);
        jToggleButton159npi.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 0);
        npiPanel.add(jToggleButton159npi, gridBagConstraints);

        npiGravBtnGroup2.add(cuidatBtn20npi);
        cuidatBtn20npi.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 0);
        npiPanel.add(cuidatBtn20npi, gridBagConstraints);

        npiGravBtnGroup3.add(jToggleButton160npi);
        jToggleButton160npi.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 0);
        npiPanel.add(jToggleButton160npi, gridBagConstraints);

        npiGravBtnGroup1.add(raoBtn28npi);
        raoBtn28npi.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 0);
        npiPanel.add(raoBtn28npi, gridBagConstraints);

        npiFreqBtnGroup3.add(jToggleButton161npi);
        jToggleButton161npi.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton161npi, gridBagConstraints);

        npiFreqBtnGroup2.add(jToggleButton162npi);
        jToggleButton162npi.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton162npi, gridBagConstraints);

        npiFreqBtnGroup1.add(cuidatBtn21npi);
        cuidatBtn21npi.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(cuidatBtn21npi, gridBagConstraints);

        npiGravBtnGroup6.add(jToggleButton163npi);
        jToggleButton163npi.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 0);
        npiPanel.add(jToggleButton163npi, gridBagConstraints);

        npiFreqBtnGroup4.add(jToggleButton164npi);
        jToggleButton164npi.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton164npi, gridBagConstraints);

        npiFreqBtnGroup8.add(jToggleButton165npi);
        jToggleButton165npi.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton165npi, gridBagConstraints);

        npiFreqBtnGroup10.add(jToggleButton166npi);
        jToggleButton166npi.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton166npi, gridBagConstraints);

        npiFreqBtnGroup8.add(jToggleButton167npi);
        jToggleButton167npi.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton167npi, gridBagConstraints);

        npiGravBtnGroup5.add(jToggleButton168npi);
        jToggleButton168npi.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton168npi, gridBagConstraints);

        npiGravBtnGroup4.add(jToggleButton169npi);
        jToggleButton169npi.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton169npi, gridBagConstraints);

        npiGravBtnGroup3.add(jToggleButton170npi);
        jToggleButton170npi.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton170npi, gridBagConstraints);

        npiGravBtnGroup2.add(jToggleButton171npi);
        jToggleButton171npi.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton171npi, gridBagConstraints);

        npiGravBtnGroup1.add(activitatsDBtn26npi);
        activitatsDBtn26npi.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(activitatsDBtn26npi, gridBagConstraints);

        npiFreqBtnGroup9.add(jToggleButton172npi);
        jToggleButton172npi.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton172npi, gridBagConstraints);

        npiFreqBtnGroup9.add(jToggleButton173npi);
        jToggleButton173npi.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton173npi, gridBagConstraints);

        npiGravBtnGroup9.add(jToggleButton174npi);
        jToggleButton174npi.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 0);
        npiPanel.add(jToggleButton174npi, gridBagConstraints);

        npiFreqBtnGroup1.add(activitatsDBtn27npi);
        activitatsDBtn27npi.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(activitatsDBtn27npi, gridBagConstraints);

        npiFreqBtnGroup2.add(jToggleButton175npi);
        jToggleButton175npi.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton175npi, gridBagConstraints);

        npiFreqBtnGroup3.add(jToggleButton176npi);
        jToggleButton176npi.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton176npi, gridBagConstraints);

        npiFreqBtnGroup4.add(jToggleButton177npi);
        jToggleButton177npi.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton177npi, gridBagConstraints);

        npiFreqBtnGroup5.add(jToggleButton178npi);
        jToggleButton178npi.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton178npi, gridBagConstraints);

        npiFreqBtnGroup6.add(activitatsDBtn28npi);
        activitatsDBtn28npi.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(activitatsDBtn28npi, gridBagConstraints);

        npiFreqBtnGroup7.add(jToggleButton179npi);
        jToggleButton179npi.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton179npi, gridBagConstraints);

        npiFreqBtnGroup8.add(jToggleButton180npi);
        jToggleButton180npi.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton180npi, gridBagConstraints);

        npiFreqBtnGroup9.add(jToggleButton181npi);
        jToggleButton181npi.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton181npi, gridBagConstraints);

        npiFreqBtnGroup10.add(jToggleButton182npi);
        jToggleButton182npi.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton182npi, gridBagConstraints);

        npiGravBtnGroup1.add(activitatsDBtn29npi);
        activitatsDBtn29npi.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(activitatsDBtn29npi, gridBagConstraints);

        npiGravBtnGroup2.add(jToggleButton183npi);
        jToggleButton183npi.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton183npi, gridBagConstraints);

        npiGravBtnGroup3.add(jToggleButton184npi);
        jToggleButton184npi.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton184npi, gridBagConstraints);

        npiGravBtnGroup4.add(jToggleButton185npi);
        jToggleButton185npi.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton185npi, gridBagConstraints);

        npiGravBtnGroup5.add(jToggleButton186npi);
        jToggleButton186npi.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton186npi, gridBagConstraints);

        npiGravBtnGroup6.add(activitatsDBtn30npi);
        activitatsDBtn30npi.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(activitatsDBtn30npi, gridBagConstraints);

        npiGravBtnGroup7.add(jToggleButton187npi);
        jToggleButton187npi.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton187npi, gridBagConstraints);

        npiGravBtnGroup8.add(jToggleButton188npi);
        jToggleButton188npi.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton188npi, gridBagConstraints);

        npiGravBtnGroup9.add(jToggleButton189npi);
        jToggleButton189npi.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton189npi, gridBagConstraints);

        npiGravBtnGroup10.add(jToggleButton190npi);
        jToggleButton190npi.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton190npi, gridBagConstraints);

        npiFreqBtnGroup1.add(activitatsDBtn31npi);
        activitatsDBtn31npi.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(activitatsDBtn31npi, gridBagConstraints);

        npiFreqBtnGroup2.add(jToggleButton191npi);
        jToggleButton191npi.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton191npi, gridBagConstraints);

        npiFreqBtnGroup3.add(jToggleButton192npi);
        jToggleButton192npi.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton192npi, gridBagConstraints);

        npiFreqBtnGroup4.add(jToggleButton193npi);
        jToggleButton193npi.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton193npi, gridBagConstraints);

        npiFreqBtnGroup5.add(jToggleButton194npi);
        jToggleButton194npi.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton194npi, gridBagConstraints);

        npiFreqBtnGroup6.add(activitatsDBtn32npi);
        activitatsDBtn32npi.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(activitatsDBtn32npi, gridBagConstraints);

        npiFreqBtnGroup7.add(jToggleButton195npi);
        jToggleButton195npi.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton195npi, gridBagConstraints);

        npiFreqBtnGroup8.add(jToggleButton196npi);
        jToggleButton196npi.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton196npi, gridBagConstraints);

        npiFreqBtnGroup9.add(jToggleButton197npi);
        jToggleButton197npi.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton197npi, gridBagConstraints);

        npiFreqBtnGroup10.add(jToggleButton198npi);
        jToggleButton198npi.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton198npi, gridBagConstraints);

        npiFreqBtnGroup1.add(activitatsDBtn33npi);
        activitatsDBtn33npi.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(activitatsDBtn33npi, gridBagConstraints);

        npiFreqBtnGroup2.add(jToggleButton199npi);
        jToggleButton199npi.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton199npi, gridBagConstraints);

        npiFreqBtnGroup3.add(jToggleButton200npi);
        jToggleButton200npi.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton200npi, gridBagConstraints);

        npiFreqBtnGroup4.add(jToggleButton201npi);
        jToggleButton201npi.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton201npi, gridBagConstraints);

        npiFreqBtnGroup5.add(jToggleButton202npi);
        jToggleButton202npi.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton202npi, gridBagConstraints);

        npiFreqBtnGroup6.add(activitatsDBtn34npi);
        activitatsDBtn34npi.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(activitatsDBtn34npi, gridBagConstraints);

        npiFreqBtnGroup7.add(jToggleButton203npi);
        jToggleButton203npi.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton203npi, gridBagConstraints);

        npiFreqBtnGroup8.add(jToggleButton204npi);
        jToggleButton204npi.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton204npi, gridBagConstraints);

        npiFreqBtnGroup9.add(jToggleButton205npi);
        jToggleButton205npi.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton205npi, gridBagConstraints);

        npiFreqBtnGroup10.add(jToggleButton206npi);
        jToggleButton206npi.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton206npi, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(npiCheck10, gridBagConstraints);

        npiTotal1.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 4;
        npiPanel.add(npiTotal1, gridBagConstraints);

        npiTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        npiTotal.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 3;
        npiPanel.add(npiTotal, gridBagConstraints);

        npiTotal3.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 6;
        npiPanel.add(npiTotal3, gridBagConstraints);

        npiTotal2.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 5;
        npiPanel.add(npiTotal2, gridBagConstraints);

        npiTotal4.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 7;
        npiPanel.add(npiTotal4, gridBagConstraints);

        npiTotal5.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 8;
        npiPanel.add(npiTotal5, gridBagConstraints);

        npiTotal6.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 9;
        npiPanel.add(npiTotal6, gridBagConstraints);

        npiTotal8.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 11;
        npiPanel.add(npiTotal8, gridBagConstraints);

        npiTotal9.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 12;
        npiPanel.add(npiTotal9, gridBagConstraints);

        npiTotal10.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 13;
        npiPanel.add(npiTotal10, gridBagConstraints);

        npiTotal7.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 10;
        npiPanel.add(npiTotal7, gridBagConstraints);

        jLabel144npi.setText("<html><u><b>Freqüència:</b></u> 0 = Absent; 1 = Ocasionalment (menys d'una vegada per setmana); 2 = Sovint (al voltant d'una vegada per setmana); 3 = Freqüentment (diverses vegades per setmana, però no diàriament); 4 = Molt freqüentment (diàriament o contínuament)");

        jLabel145npi.setText("<html><b><u>Gravetat:</b></u> 1 = Lleu (provoca poca molèsties al pacient); 2 = Moderada (més molest per al pacient, però pot es redirigit pel cuidador); 3 = Greu (molt molest per al pacient i difícil de redirigir)");

        javax.swing.GroupLayout npi2PanelLayout = new javax.swing.GroupLayout(npi2Panel);
        npi2Panel.setLayout(npi2PanelLayout);
        npi2PanelLayout.setHorizontalGroup(
            npi2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(npi2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(npi2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel106npi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(npiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(npi2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel145npi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                        .addComponent(jLabel144npi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        npi2PanelLayout.setVerticalGroup(
            npi2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(npi2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel106npi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(npiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel144npi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel145npi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        npiScroll.setViewportView(npi2Panel);

        add(npiScroll, "card1");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton activitatsDBtn22npi;
    private javax.swing.JToggleButton activitatsDBtn25npi;
    private javax.swing.JToggleButton activitatsDBtn26npi;
    private javax.swing.JToggleButton activitatsDBtn27npi;
    private javax.swing.JToggleButton activitatsDBtn28npi;
    private javax.swing.JToggleButton activitatsDBtn29npi;
    private javax.swing.JToggleButton activitatsDBtn30npi;
    private javax.swing.JToggleButton activitatsDBtn31npi;
    private javax.swing.JToggleButton activitatsDBtn32npi;
    private javax.swing.JToggleButton activitatsDBtn33npi;
    private javax.swing.JToggleButton activitatsDBtn34npi;
    private javax.swing.JToggleButton cuidatBtn15npi;
    private javax.swing.JToggleButton cuidatBtn20npi;
    private javax.swing.JToggleButton cuidatBtn21npi;
    private javax.swing.JLabel jLabel106npi;
    private javax.swing.JLabel jLabel144npi;
    private javax.swing.JLabel jLabel145npi;
    private javax.swing.JLabel jLabel166npi;
    private javax.swing.JLabel jLabel191npi;
    private javax.swing.JLabel jLabel192npi;
    private javax.swing.JLabel jLabel193npi;
    private javax.swing.JLabel jLabel194npi;
    private javax.swing.JLabel jLabel202npi;
    private javax.swing.JLabel jLabel206npi;
    private javax.swing.JLabel jLabel4npi;
    private javax.swing.JLabel jLabel5npi;
    private javax.swing.JLabel jLabel6npi;
    private javax.swing.JLabel jLabel7npi;
    private javax.swing.JLabel jLabel83npi;
    private javax.swing.JLabel jLabel84npi;
    private javax.swing.JLabel jLabel85npi;
    private javax.swing.JLabel jLabel86npi;
    private javax.swing.JLabel jLabel8npi;
    private javax.swing.JToggleButton jToggleButton118npi;
    private javax.swing.JToggleButton jToggleButton122npi;
    private javax.swing.JToggleButton jToggleButton134npi;
    private javax.swing.JToggleButton jToggleButton138npi;
    private javax.swing.JToggleButton jToggleButton142npi;
    private javax.swing.JToggleButton jToggleButton146npi;
    private javax.swing.JToggleButton jToggleButton147npi;
    private javax.swing.JToggleButton jToggleButton150npi;
    private javax.swing.JToggleButton jToggleButton151npi;
    private javax.swing.JToggleButton jToggleButton152npi;
    private javax.swing.JToggleButton jToggleButton153npi;
    private javax.swing.JToggleButton jToggleButton158npi;
    private javax.swing.JToggleButton jToggleButton159npi;
    private javax.swing.JToggleButton jToggleButton160npi;
    private javax.swing.JToggleButton jToggleButton161npi;
    private javax.swing.JToggleButton jToggleButton162npi;
    private javax.swing.JToggleButton jToggleButton163npi;
    private javax.swing.JToggleButton jToggleButton164npi;
    private javax.swing.JToggleButton jToggleButton165npi;
    private javax.swing.JToggleButton jToggleButton166npi;
    private javax.swing.JToggleButton jToggleButton167npi;
    private javax.swing.JToggleButton jToggleButton168npi;
    private javax.swing.JToggleButton jToggleButton169npi;
    private javax.swing.JToggleButton jToggleButton170npi;
    private javax.swing.JToggleButton jToggleButton171npi;
    private javax.swing.JToggleButton jToggleButton172npi;
    private javax.swing.JToggleButton jToggleButton173npi;
    private javax.swing.JToggleButton jToggleButton174npi;
    private javax.swing.JToggleButton jToggleButton175npi;
    private javax.swing.JToggleButton jToggleButton176npi;
    private javax.swing.JToggleButton jToggleButton177npi;
    private javax.swing.JToggleButton jToggleButton178npi;
    private javax.swing.JToggleButton jToggleButton179npi;
    private javax.swing.JToggleButton jToggleButton180npi;
    private javax.swing.JToggleButton jToggleButton181npi;
    private javax.swing.JToggleButton jToggleButton182npi;
    private javax.swing.JToggleButton jToggleButton183npi;
    private javax.swing.JToggleButton jToggleButton184npi;
    private javax.swing.JToggleButton jToggleButton185npi;
    private javax.swing.JToggleButton jToggleButton186npi;
    private javax.swing.JToggleButton jToggleButton187npi;
    private javax.swing.JToggleButton jToggleButton188npi;
    private javax.swing.JToggleButton jToggleButton189npi;
    private javax.swing.JToggleButton jToggleButton190npi;
    private javax.swing.JToggleButton jToggleButton191npi;
    private javax.swing.JToggleButton jToggleButton192npi;
    private javax.swing.JToggleButton jToggleButton193npi;
    private javax.swing.JToggleButton jToggleButton194npi;
    private javax.swing.JToggleButton jToggleButton195npi;
    private javax.swing.JToggleButton jToggleButton196npi;
    private javax.swing.JToggleButton jToggleButton197npi;
    private javax.swing.JToggleButton jToggleButton198npi;
    private javax.swing.JToggleButton jToggleButton199npi;
    private javax.swing.JToggleButton jToggleButton200npi;
    private javax.swing.JToggleButton jToggleButton201npi;
    private javax.swing.JToggleButton jToggleButton202npi;
    private javax.swing.JToggleButton jToggleButton203npi;
    private javax.swing.JToggleButton jToggleButton204npi;
    private javax.swing.JToggleButton jToggleButton205npi;
    private javax.swing.JToggleButton jToggleButton206npi;
    private javax.swing.JToggleButton memoBtn20npi;
    private javax.swing.JPanel npi2Panel;
    private javax.swing.JCheckBox npiCheck1;
    private javax.swing.JCheckBox npiCheck10;
    private javax.swing.JCheckBox npiCheck2;
    private javax.swing.JCheckBox npiCheck3;
    private javax.swing.JCheckBox npiCheck4;
    private javax.swing.JCheckBox npiCheck5;
    private javax.swing.JCheckBox npiCheck6;
    private javax.swing.JCheckBox npiCheck7;
    private javax.swing.JCheckBox npiCheck8;
    private javax.swing.JCheckBox npiCheck9;
    private javax.swing.ButtonGroup npiFreqBtnGroup1;
    private javax.swing.ButtonGroup npiFreqBtnGroup10;
    private javax.swing.ButtonGroup npiFreqBtnGroup2;
    private javax.swing.ButtonGroup npiFreqBtnGroup3;
    private javax.swing.ButtonGroup npiFreqBtnGroup4;
    private javax.swing.ButtonGroup npiFreqBtnGroup5;
    private javax.swing.ButtonGroup npiFreqBtnGroup6;
    private javax.swing.ButtonGroup npiFreqBtnGroup7;
    private javax.swing.ButtonGroup npiFreqBtnGroup8;
    private javax.swing.ButtonGroup npiFreqBtnGroup9;
    private javax.swing.ButtonGroup npiGravBtnGroup1;
    private javax.swing.ButtonGroup npiGravBtnGroup10;
    private javax.swing.ButtonGroup npiGravBtnGroup2;
    private javax.swing.ButtonGroup npiGravBtnGroup3;
    private javax.swing.ButtonGroup npiGravBtnGroup4;
    private javax.swing.ButtonGroup npiGravBtnGroup5;
    private javax.swing.ButtonGroup npiGravBtnGroup6;
    private javax.swing.ButtonGroup npiGravBtnGroup7;
    private javax.swing.ButtonGroup npiGravBtnGroup8;
    private javax.swing.ButtonGroup npiGravBtnGroup9;
    private javax.swing.JPanel npiPanel;
    private javax.swing.JScrollPane npiScroll;
    private javax.swing.JLabel npiTotal;
    private javax.swing.JLabel npiTotal1;
    private javax.swing.JLabel npiTotal10;
    private javax.swing.JLabel npiTotal2;
    private javax.swing.JLabel npiTotal3;
    private javax.swing.JLabel npiTotal4;
    private javax.swing.JLabel npiTotal5;
    private javax.swing.JLabel npiTotal6;
    private javax.swing.JLabel npiTotal7;
    private javax.swing.JLabel npiTotal8;
    private javax.swing.JLabel npiTotal9;
    private javax.swing.JToggleButton orientacioBtn20npi;
    private javax.swing.JToggleButton raoBtn19npi;
    private javax.swing.JToggleButton raoBtn21npi;
    private javax.swing.JToggleButton raoBtn27npi;
    private javax.swing.JToggleButton raoBtn28npi;
    // End of variables declaration//GEN-END:variables
}
