/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.tests;

import controlador.Utils;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Properties;
import javax.swing.AbstractButton;
import javax.swing.JCheckBox;
import javax.swing.JToggleButton;
import model.Pacient;

/**
 *
 * @author a630703
 */
public class NPI extends Test {

    /**
     * Creates new form Test
     *
     * @param pacientActual
     */
    public NPI(Pacient pacientActual) {
        super(pacientActual);
        initComponents();

        label = "NPI";
        numPaginesTotal = this.getComponentCount();
        
        initNPI();
        
        Utils.setActionCommands(npiPanel);
    }

    @Override
    public void guardarResultats(Properties prop) {
        // NPI
        Utils.setProperty(prop,"npiTotal",npiTotal);
    }

    private void initNPI() {

        for (Component com : npiPanel.getComponents()){
            if (com instanceof JCheckBox || com instanceof JToggleButton){
                ((AbstractButton)com).addActionListener(npiActionListener);
            }
        }
    }

    private ActionListener npiActionListener = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            actualitzaPuntuacioNpi();
        }
    };

    private void actualitzaPuntuacioNpi() {
        int count = 0;

        int tempPunt = Utils.getPunctuationFromButtonGroup(npiFreqBtnGroup1)*Utils.getPunctuationFromButtonGroup(npiGravBtnGroup1);
        npiTotal1.setText(tempPunt+"");
        if (!npiCheck1.isSelected()) count+=tempPunt;

        tempPunt = Utils.getPunctuationFromButtonGroup(npiFreqBtnGroup2)*Utils.getPunctuationFromButtonGroup(npiGravBtnGroup2);
        npiTotal2.setText(tempPunt+"");
        if (!npiCheck2.isSelected()) count+=tempPunt;

        tempPunt = Utils.getPunctuationFromButtonGroup(npiFreqBtnGroup3)*Utils.getPunctuationFromButtonGroup(npiGravBtnGroup3);
        npiTotal3.setText(tempPunt+"");
        if (!npiCheck3.isSelected()) count+=tempPunt;

        tempPunt = Utils.getPunctuationFromButtonGroup(npiFreqBtnGroup4)*Utils.getPunctuationFromButtonGroup(npiGravBtnGroup4);
        npiTotal4.setText(tempPunt+"");
        if (!npiCheck4.isSelected()) count+=tempPunt;

        tempPunt = Utils.getPunctuationFromButtonGroup(npiFreqBtnGroup5)*Utils.getPunctuationFromButtonGroup(npiGravBtnGroup5);
        npiTotal5.setText(tempPunt+"");
        if (!npiCheck5.isSelected()) count+=tempPunt;

        tempPunt = Utils.getPunctuationFromButtonGroup(npiFreqBtnGroup6)*Utils.getPunctuationFromButtonGroup(npiGravBtnGroup6);
        npiTotal6.setText(tempPunt+"");
        if (!npiCheck6.isSelected()) count+=tempPunt;

        tempPunt = Utils.getPunctuationFromButtonGroup(npiFreqBtnGroup7)*Utils.getPunctuationFromButtonGroup(npiGravBtnGroup7);
        npiTotal7.setText(tempPunt+"");
        if (!npiCheck7.isSelected()) count+=tempPunt;

        tempPunt = Utils.getPunctuationFromButtonGroup(npiFreqBtnGroup8)*Utils.getPunctuationFromButtonGroup(npiGravBtnGroup8);
        npiTotal8.setText(tempPunt+"");
        if (!npiCheck8.isSelected()) count+=tempPunt;

        tempPunt = Utils.getPunctuationFromButtonGroup(npiFreqBtnGroup9)*Utils.getPunctuationFromButtonGroup(npiGravBtnGroup9);
        npiTotal9.setText(tempPunt+"");
        if (!npiCheck9.isSelected()) count+=tempPunt;

        tempPunt = Utils.getPunctuationFromButtonGroup(npiFreqBtnGroup10)*Utils.getPunctuationFromButtonGroup(npiGravBtnGroup10);
        npiTotal10.setText(tempPunt+"");
        if (!npiCheck10.isSelected()) count+=tempPunt;

        npiTotal.setText(count+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        npiFreqBtnGroup1 = new javax.swing.ButtonGroup();
        npiFreqBtnGroup2 = new javax.swing.ButtonGroup();
        npiFreqBtnGroup3 = new javax.swing.ButtonGroup();
        npiFreqBtnGroup4 = new javax.swing.ButtonGroup();
        npiFreqBtnGroup5 = new javax.swing.ButtonGroup();
        npiFreqBtnGroup6 = new javax.swing.ButtonGroup();
        npiFreqBtnGroup7 = new javax.swing.ButtonGroup();
        npiFreqBtnGroup8 = new javax.swing.ButtonGroup();
        npiFreqBtnGroup9 = new javax.swing.ButtonGroup();
        npiFreqBtnGroup10 = new javax.swing.ButtonGroup();
        npiGravBtnGroup1 = new javax.swing.ButtonGroup();
        npiGravBtnGroup2 = new javax.swing.ButtonGroup();
        npiGravBtnGroup3 = new javax.swing.ButtonGroup();
        npiGravBtnGroup4 = new javax.swing.ButtonGroup();
        npiGravBtnGroup5 = new javax.swing.ButtonGroup();
        npiGravBtnGroup6 = new javax.swing.ButtonGroup();
        npiGravBtnGroup7 = new javax.swing.ButtonGroup();
        npiGravBtnGroup8 = new javax.swing.ButtonGroup();
        npiGravBtnGroup9 = new javax.swing.ButtonGroup();
        npiGravBtnGroup10 = new javax.swing.ButtonGroup();
        npiScroll = new javax.swing.JScrollPane();
        npi2Panel = new javax.swing.JPanel();
        jLabel106 = new javax.swing.JLabel();
        npiPanel = new javax.swing.JPanel();
        orientacioBtn20 = new javax.swing.JToggleButton();
        memoBtn20 = new javax.swing.JToggleButton();
        raoBtn19 = new javax.swing.JToggleButton();
        raoBtn21 = new javax.swing.JToggleButton();
        activitatsDBtn22 = new javax.swing.JToggleButton();
        cuidatBtn15 = new javax.swing.JToggleButton();
        jLabel166 = new javax.swing.JLabel();
        jLabel191 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel192 = new javax.swing.JLabel();
        jLabel193 = new javax.swing.JLabel();
        jLabel194 = new javax.swing.JLabel();
        jLabel202 = new javax.swing.JLabel();
        jToggleButton118 = new javax.swing.JToggleButton();
        jToggleButton122 = new javax.swing.JToggleButton();
        jToggleButton134 = new javax.swing.JToggleButton();
        jToggleButton138 = new javax.swing.JToggleButton();
        jToggleButton142 = new javax.swing.JToggleButton();
        jToggleButton146 = new javax.swing.JToggleButton();
        jToggleButton147 = new javax.swing.JToggleButton();
        jLabel206 = new javax.swing.JLabel();
        activitatsDBtn25 = new javax.swing.JToggleButton();
        jToggleButton150 = new javax.swing.JToggleButton();
        jToggleButton151 = new javax.swing.JToggleButton();
        jToggleButton152 = new javax.swing.JToggleButton();
        jToggleButton153 = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        npiCheck9 = new javax.swing.JCheckBox();
        npiCheck1 = new javax.swing.JCheckBox();
        npiCheck2 = new javax.swing.JCheckBox();
        npiCheck3 = new javax.swing.JCheckBox();
        npiCheck4 = new javax.swing.JCheckBox();
        npiCheck5 = new javax.swing.JCheckBox();
        npiCheck6 = new javax.swing.JCheckBox();
        npiCheck7 = new javax.swing.JCheckBox();
        npiCheck8 = new javax.swing.JCheckBox();
        raoBtn27 = new javax.swing.JToggleButton();
        jToggleButton158 = new javax.swing.JToggleButton();
        jToggleButton159 = new javax.swing.JToggleButton();
        cuidatBtn20 = new javax.swing.JToggleButton();
        jToggleButton160 = new javax.swing.JToggleButton();
        raoBtn28 = new javax.swing.JToggleButton();
        jToggleButton161 = new javax.swing.JToggleButton();
        jToggleButton162 = new javax.swing.JToggleButton();
        cuidatBtn21 = new javax.swing.JToggleButton();
        jToggleButton163 = new javax.swing.JToggleButton();
        jToggleButton164 = new javax.swing.JToggleButton();
        jToggleButton165 = new javax.swing.JToggleButton();
        jToggleButton166 = new javax.swing.JToggleButton();
        jToggleButton167 = new javax.swing.JToggleButton();
        jToggleButton168 = new javax.swing.JToggleButton();
        jToggleButton169 = new javax.swing.JToggleButton();
        jToggleButton170 = new javax.swing.JToggleButton();
        jToggleButton171 = new javax.swing.JToggleButton();
        activitatsDBtn26 = new javax.swing.JToggleButton();
        jToggleButton172 = new javax.swing.JToggleButton();
        jToggleButton173 = new javax.swing.JToggleButton();
        jToggleButton174 = new javax.swing.JToggleButton();
        activitatsDBtn27 = new javax.swing.JToggleButton();
        jToggleButton175 = new javax.swing.JToggleButton();
        jToggleButton176 = new javax.swing.JToggleButton();
        jToggleButton177 = new javax.swing.JToggleButton();
        jToggleButton178 = new javax.swing.JToggleButton();
        activitatsDBtn28 = new javax.swing.JToggleButton();
        jToggleButton179 = new javax.swing.JToggleButton();
        jToggleButton180 = new javax.swing.JToggleButton();
        jToggleButton181 = new javax.swing.JToggleButton();
        jToggleButton182 = new javax.swing.JToggleButton();
        activitatsDBtn29 = new javax.swing.JToggleButton();
        jToggleButton183 = new javax.swing.JToggleButton();
        jToggleButton184 = new javax.swing.JToggleButton();
        jToggleButton185 = new javax.swing.JToggleButton();
        jToggleButton186 = new javax.swing.JToggleButton();
        activitatsDBtn30 = new javax.swing.JToggleButton();
        jToggleButton187 = new javax.swing.JToggleButton();
        jToggleButton188 = new javax.swing.JToggleButton();
        jToggleButton189 = new javax.swing.JToggleButton();
        jToggleButton190 = new javax.swing.JToggleButton();
        activitatsDBtn31 = new javax.swing.JToggleButton();
        jToggleButton191 = new javax.swing.JToggleButton();
        jToggleButton192 = new javax.swing.JToggleButton();
        jToggleButton193 = new javax.swing.JToggleButton();
        jToggleButton194 = new javax.swing.JToggleButton();
        activitatsDBtn32 = new javax.swing.JToggleButton();
        jToggleButton195 = new javax.swing.JToggleButton();
        jToggleButton196 = new javax.swing.JToggleButton();
        jToggleButton197 = new javax.swing.JToggleButton();
        jToggleButton198 = new javax.swing.JToggleButton();
        activitatsDBtn33 = new javax.swing.JToggleButton();
        jToggleButton199 = new javax.swing.JToggleButton();
        jToggleButton200 = new javax.swing.JToggleButton();
        jToggleButton201 = new javax.swing.JToggleButton();
        jToggleButton202 = new javax.swing.JToggleButton();
        activitatsDBtn34 = new javax.swing.JToggleButton();
        jToggleButton203 = new javax.swing.JToggleButton();
        jToggleButton204 = new javax.swing.JToggleButton();
        jToggleButton205 = new javax.swing.JToggleButton();
        jToggleButton206 = new javax.swing.JToggleButton();
        npiCheck10 = new javax.swing.JCheckBox();
        npiTotal1 = new javax.swing.JLabel();
        npiTotal = new javax.swing.JLabel();
        npiTotal3 = new javax.swing.JLabel();
        npiTotal2 = new javax.swing.JLabel();
        npiTotal4 = new javax.swing.JLabel();
        npiTotal5 = new javax.swing.JLabel();
        npiTotal6 = new javax.swing.JLabel();
        npiTotal8 = new javax.swing.JLabel();
        npiTotal9 = new javax.swing.JLabel();
        npiTotal10 = new javax.swing.JLabel();
        npiTotal7 = new javax.swing.JLabel();
        jLabel144 = new javax.swing.JLabel();
        jLabel145 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        jLabel106.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel106.setText("<html><center><b>HABILITATS DE COMUNICACIÓ: Telèfon i carta</b>");

        npiPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Trastorns neuropsiquiàtrics (màxima puntuació: 120)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        npiPanel.setLayout(new java.awt.GridBagLayout());

        npiFreqBtnGroup2.add(orientacioBtn20);
        orientacioBtn20.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(orientacioBtn20, gridBagConstraints);

        npiFreqBtnGroup1.add(memoBtn20);
        memoBtn20.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(memoBtn20, gridBagConstraints);

        npiFreqBtnGroup3.add(raoBtn19);
        raoBtn19.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(raoBtn19, gridBagConstraints);

        npiFreqBtnGroup7.add(raoBtn21);
        raoBtn21.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(raoBtn21, gridBagConstraints);

        npiFreqBtnGroup4.add(activitatsDBtn22);
        activitatsDBtn22.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(activitatsDBtn22, gridBagConstraints);

        npiFreqBtnGroup6.add(cuidatBtn15);
        cuidatBtn15.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(cuidatBtn15, gridBagConstraints);

        jLabel166.setText("Depressió/disfòria");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(jLabel166, gridBagConstraints);

        jLabel191.setText("<html><center><b>Total (Freqüència x<br>Gravetat)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 3, 1);
        npiPanel.add(jLabel191, gridBagConstraints);

        jLabel83.setText("Puntuació total");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(jLabel83, gridBagConstraints);

        jLabel84.setText("Deliris");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        npiPanel.add(jLabel84, gridBagConstraints);

        jLabel85.setText("Agitació");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        npiPanel.add(jLabel85, gridBagConstraints);

        jLabel86.setText("Ansietat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        npiPanel.add(jLabel86, gridBagConstraints);

        jLabel192.setText("Eufòr/alegria");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(jLabel192, gridBagConstraints);

        jLabel193.setText("Apatía/indiferència");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(jLabel193, gridBagConstraints);

        jLabel194.setText("Desinhibició");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(jLabel194, gridBagConstraints);

        jLabel202.setText("Irritabilitat/labilitat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(jLabel202, gridBagConstraints);

        npiGravBtnGroup8.add(jToggleButton118);
        jToggleButton118.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 0);
        npiPanel.add(jToggleButton118, gridBagConstraints);

        npiFreqBtnGroup5.add(jToggleButton122);
        jToggleButton122.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton122, gridBagConstraints);

        npiFreqBtnGroup6.add(jToggleButton134);
        jToggleButton134.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton134, gridBagConstraints);

        npiFreqBtnGroup7.add(jToggleButton138);
        jToggleButton138.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton138, gridBagConstraints);

        npiFreqBtnGroup5.add(jToggleButton142);
        jToggleButton142.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton142, gridBagConstraints);

        npiFreqBtnGroup10.add(jToggleButton146);
        jToggleButton146.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton146, gridBagConstraints);

        npiGravBtnGroup10.add(jToggleButton147);
        jToggleButton147.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 0);
        npiPanel.add(jToggleButton147, gridBagConstraints);

        jLabel206.setText("<html><b>No valorable<br>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(1, 3, 3, 3);
        npiPanel.add(jLabel206, gridBagConstraints);

        npiGravBtnGroup6.add(activitatsDBtn25);
        activitatsDBtn25.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(activitatsDBtn25, gridBagConstraints);

        npiGravBtnGroup7.add(jToggleButton150);
        jToggleButton150.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton150, gridBagConstraints);

        npiGravBtnGroup8.add(jToggleButton151);
        jToggleButton151.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton151, gridBagConstraints);

        npiGravBtnGroup9.add(jToggleButton152);
        jToggleButton152.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton152, gridBagConstraints);

        npiGravBtnGroup10.add(jToggleButton153);
        jToggleButton153.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton153, gridBagConstraints);

        jLabel4.setText("<html><b>Transtorn");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(jLabel4, gridBagConstraints);

        jLabel5.setText("<html><b>Freqüència");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Conducta motora sense finalitat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(jLabel6, gridBagConstraints);

        jLabel7.setText("<html><b>Gravetat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(jLabel7, gridBagConstraints);

        jLabel8.setText("Al·lucinacions");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(jLabel8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(npiCheck9, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(npiCheck1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(npiCheck2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(npiCheck3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(npiCheck4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(npiCheck5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(npiCheck6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(npiCheck7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(npiCheck8, gridBagConstraints);

        npiGravBtnGroup7.add(raoBtn27);
        raoBtn27.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 0);
        npiPanel.add(raoBtn27, gridBagConstraints);

        npiGravBtnGroup5.add(jToggleButton158);
        jToggleButton158.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 0);
        npiPanel.add(jToggleButton158, gridBagConstraints);

        npiGravBtnGroup4.add(jToggleButton159);
        jToggleButton159.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 0);
        npiPanel.add(jToggleButton159, gridBagConstraints);

        npiGravBtnGroup2.add(cuidatBtn20);
        cuidatBtn20.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 0);
        npiPanel.add(cuidatBtn20, gridBagConstraints);

        npiGravBtnGroup3.add(jToggleButton160);
        jToggleButton160.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 0);
        npiPanel.add(jToggleButton160, gridBagConstraints);

        npiGravBtnGroup1.add(raoBtn28);
        raoBtn28.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 0);
        npiPanel.add(raoBtn28, gridBagConstraints);

        npiFreqBtnGroup3.add(jToggleButton161);
        jToggleButton161.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton161, gridBagConstraints);

        npiFreqBtnGroup2.add(jToggleButton162);
        jToggleButton162.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton162, gridBagConstraints);

        npiFreqBtnGroup1.add(cuidatBtn21);
        cuidatBtn21.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(cuidatBtn21, gridBagConstraints);

        npiGravBtnGroup6.add(jToggleButton163);
        jToggleButton163.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 0);
        npiPanel.add(jToggleButton163, gridBagConstraints);

        npiFreqBtnGroup4.add(jToggleButton164);
        jToggleButton164.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton164, gridBagConstraints);

        npiFreqBtnGroup8.add(jToggleButton165);
        jToggleButton165.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton165, gridBagConstraints);

        npiFreqBtnGroup10.add(jToggleButton166);
        jToggleButton166.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton166, gridBagConstraints);

        npiFreqBtnGroup8.add(jToggleButton167);
        jToggleButton167.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton167, gridBagConstraints);

        npiGravBtnGroup5.add(jToggleButton168);
        jToggleButton168.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton168, gridBagConstraints);

        npiGravBtnGroup4.add(jToggleButton169);
        jToggleButton169.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton169, gridBagConstraints);

        npiGravBtnGroup3.add(jToggleButton170);
        jToggleButton170.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton170, gridBagConstraints);

        npiGravBtnGroup2.add(jToggleButton171);
        jToggleButton171.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton171, gridBagConstraints);

        npiGravBtnGroup1.add(activitatsDBtn26);
        activitatsDBtn26.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(activitatsDBtn26, gridBagConstraints);

        npiFreqBtnGroup9.add(jToggleButton172);
        jToggleButton172.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton172, gridBagConstraints);

        npiFreqBtnGroup9.add(jToggleButton173);
        jToggleButton173.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton173, gridBagConstraints);

        npiGravBtnGroup9.add(jToggleButton174);
        jToggleButton174.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 6, 1, 0);
        npiPanel.add(jToggleButton174, gridBagConstraints);

        npiFreqBtnGroup1.add(activitatsDBtn27);
        activitatsDBtn27.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(activitatsDBtn27, gridBagConstraints);

        npiFreqBtnGroup2.add(jToggleButton175);
        jToggleButton175.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton175, gridBagConstraints);

        npiFreqBtnGroup3.add(jToggleButton176);
        jToggleButton176.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton176, gridBagConstraints);

        npiFreqBtnGroup4.add(jToggleButton177);
        jToggleButton177.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton177, gridBagConstraints);

        npiFreqBtnGroup5.add(jToggleButton178);
        jToggleButton178.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton178, gridBagConstraints);

        npiFreqBtnGroup6.add(activitatsDBtn28);
        activitatsDBtn28.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(activitatsDBtn28, gridBagConstraints);

        npiFreqBtnGroup7.add(jToggleButton179);
        jToggleButton179.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton179, gridBagConstraints);

        npiFreqBtnGroup8.add(jToggleButton180);
        jToggleButton180.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton180, gridBagConstraints);

        npiFreqBtnGroup9.add(jToggleButton181);
        jToggleButton181.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton181, gridBagConstraints);

        npiFreqBtnGroup10.add(jToggleButton182);
        jToggleButton182.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton182, gridBagConstraints);

        npiGravBtnGroup1.add(activitatsDBtn29);
        activitatsDBtn29.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(activitatsDBtn29, gridBagConstraints);

        npiGravBtnGroup2.add(jToggleButton183);
        jToggleButton183.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton183, gridBagConstraints);

        npiGravBtnGroup3.add(jToggleButton184);
        jToggleButton184.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton184, gridBagConstraints);

        npiGravBtnGroup4.add(jToggleButton185);
        jToggleButton185.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton185, gridBagConstraints);

        npiGravBtnGroup5.add(jToggleButton186);
        jToggleButton186.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton186, gridBagConstraints);

        npiGravBtnGroup6.add(activitatsDBtn30);
        activitatsDBtn30.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(activitatsDBtn30, gridBagConstraints);

        npiGravBtnGroup7.add(jToggleButton187);
        jToggleButton187.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton187, gridBagConstraints);

        npiGravBtnGroup8.add(jToggleButton188);
        jToggleButton188.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton188, gridBagConstraints);

        npiGravBtnGroup9.add(jToggleButton189);
        jToggleButton189.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton189, gridBagConstraints);

        npiGravBtnGroup10.add(jToggleButton190);
        jToggleButton190.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton190, gridBagConstraints);

        npiFreqBtnGroup1.add(activitatsDBtn31);
        activitatsDBtn31.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(activitatsDBtn31, gridBagConstraints);

        npiFreqBtnGroup2.add(jToggleButton191);
        jToggleButton191.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton191, gridBagConstraints);

        npiFreqBtnGroup3.add(jToggleButton192);
        jToggleButton192.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton192, gridBagConstraints);

        npiFreqBtnGroup4.add(jToggleButton193);
        jToggleButton193.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton193, gridBagConstraints);

        npiFreqBtnGroup5.add(jToggleButton194);
        jToggleButton194.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton194, gridBagConstraints);

        npiFreqBtnGroup6.add(activitatsDBtn32);
        activitatsDBtn32.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(activitatsDBtn32, gridBagConstraints);

        npiFreqBtnGroup7.add(jToggleButton195);
        jToggleButton195.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton195, gridBagConstraints);

        npiFreqBtnGroup8.add(jToggleButton196);
        jToggleButton196.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton196, gridBagConstraints);

        npiFreqBtnGroup9.add(jToggleButton197);
        jToggleButton197.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton197, gridBagConstraints);

        npiFreqBtnGroup10.add(jToggleButton198);
        jToggleButton198.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton198, gridBagConstraints);

        npiFreqBtnGroup1.add(activitatsDBtn33);
        activitatsDBtn33.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(activitatsDBtn33, gridBagConstraints);

        npiFreqBtnGroup2.add(jToggleButton199);
        jToggleButton199.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton199, gridBagConstraints);

        npiFreqBtnGroup3.add(jToggleButton200);
        jToggleButton200.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton200, gridBagConstraints);

        npiFreqBtnGroup4.add(jToggleButton201);
        jToggleButton201.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton201, gridBagConstraints);

        npiFreqBtnGroup5.add(jToggleButton202);
        jToggleButton202.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton202, gridBagConstraints);

        npiFreqBtnGroup6.add(activitatsDBtn34);
        activitatsDBtn34.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(activitatsDBtn34, gridBagConstraints);

        npiFreqBtnGroup7.add(jToggleButton203);
        jToggleButton203.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton203, gridBagConstraints);

        npiFreqBtnGroup8.add(jToggleButton204);
        jToggleButton204.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton204, gridBagConstraints);

        npiFreqBtnGroup9.add(jToggleButton205);
        jToggleButton205.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton205, gridBagConstraints);

        npiFreqBtnGroup10.add(jToggleButton206);
        jToggleButton206.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 0);
        npiPanel.add(jToggleButton206, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        npiPanel.add(npiCheck10, gridBagConstraints);

        npiTotal1.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 4;
        npiPanel.add(npiTotal1, gridBagConstraints);

        npiTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        npiTotal.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 3;
        npiPanel.add(npiTotal, gridBagConstraints);

        npiTotal3.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 6;
        npiPanel.add(npiTotal3, gridBagConstraints);

        npiTotal2.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 5;
        npiPanel.add(npiTotal2, gridBagConstraints);

        npiTotal4.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 7;
        npiPanel.add(npiTotal4, gridBagConstraints);

        npiTotal5.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 8;
        npiPanel.add(npiTotal5, gridBagConstraints);

        npiTotal6.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 9;
        npiPanel.add(npiTotal6, gridBagConstraints);

        npiTotal8.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 11;
        npiPanel.add(npiTotal8, gridBagConstraints);

        npiTotal9.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 12;
        npiPanel.add(npiTotal9, gridBagConstraints);

        npiTotal10.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 13;
        npiPanel.add(npiTotal10, gridBagConstraints);

        npiTotal7.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 10;
        npiPanel.add(npiTotal7, gridBagConstraints);

        jLabel144.setText("<html><u><b>Freqüència:</b></u> 0 = Absent; 1 = Ocasionalment (menys d'una vegada per setmana); 2 = Sovint (al voltant d'una vegada per setmana); 3 = Freqüentment (diverses vegades per setmana, però no diàriament); 4 = Molt freqüentment (diàriament o contínuament)");

        jLabel145.setText("<html><b><u>Gravetat:</b></u> 1 = Lleu (provoca poca molèsties al pacient); 2 = Moderada (més molest per al pacient, però pot es redirigit pel cuidador); 3 = Greu (molt molest per al pacient i difícil de redirigir)");

        javax.swing.GroupLayout npi2PanelLayout = new javax.swing.GroupLayout(npi2Panel);
        npi2Panel.setLayout(npi2PanelLayout);
        npi2PanelLayout.setHorizontalGroup(
            npi2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(npi2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(npi2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel106, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(npiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(npi2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel145, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                        .addComponent(jLabel144, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        npi2PanelLayout.setVerticalGroup(
            npi2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(npi2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel106, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(npiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel144, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel145, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        npiScroll.setViewportView(npi2Panel);

        add(npiScroll, "card1");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton activitatsDBtn22;
    private javax.swing.JToggleButton activitatsDBtn25;
    private javax.swing.JToggleButton activitatsDBtn26;
    private javax.swing.JToggleButton activitatsDBtn27;
    private javax.swing.JToggleButton activitatsDBtn28;
    private javax.swing.JToggleButton activitatsDBtn29;
    private javax.swing.JToggleButton activitatsDBtn30;
    private javax.swing.JToggleButton activitatsDBtn31;
    private javax.swing.JToggleButton activitatsDBtn32;
    private javax.swing.JToggleButton activitatsDBtn33;
    private javax.swing.JToggleButton activitatsDBtn34;
    private javax.swing.JToggleButton cuidatBtn15;
    private javax.swing.JToggleButton cuidatBtn20;
    private javax.swing.JToggleButton cuidatBtn21;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JLabel jLabel191;
    private javax.swing.JLabel jLabel192;
    private javax.swing.JLabel jLabel193;
    private javax.swing.JLabel jLabel194;
    private javax.swing.JLabel jLabel202;
    private javax.swing.JLabel jLabel206;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JToggleButton jToggleButton118;
    private javax.swing.JToggleButton jToggleButton122;
    private javax.swing.JToggleButton jToggleButton134;
    private javax.swing.JToggleButton jToggleButton138;
    private javax.swing.JToggleButton jToggleButton142;
    private javax.swing.JToggleButton jToggleButton146;
    private javax.swing.JToggleButton jToggleButton147;
    private javax.swing.JToggleButton jToggleButton150;
    private javax.swing.JToggleButton jToggleButton151;
    private javax.swing.JToggleButton jToggleButton152;
    private javax.swing.JToggleButton jToggleButton153;
    private javax.swing.JToggleButton jToggleButton158;
    private javax.swing.JToggleButton jToggleButton159;
    private javax.swing.JToggleButton jToggleButton160;
    private javax.swing.JToggleButton jToggleButton161;
    private javax.swing.JToggleButton jToggleButton162;
    private javax.swing.JToggleButton jToggleButton163;
    private javax.swing.JToggleButton jToggleButton164;
    private javax.swing.JToggleButton jToggleButton165;
    private javax.swing.JToggleButton jToggleButton166;
    private javax.swing.JToggleButton jToggleButton167;
    private javax.swing.JToggleButton jToggleButton168;
    private javax.swing.JToggleButton jToggleButton169;
    private javax.swing.JToggleButton jToggleButton170;
    private javax.swing.JToggleButton jToggleButton171;
    private javax.swing.JToggleButton jToggleButton172;
    private javax.swing.JToggleButton jToggleButton173;
    private javax.swing.JToggleButton jToggleButton174;
    private javax.swing.JToggleButton jToggleButton175;
    private javax.swing.JToggleButton jToggleButton176;
    private javax.swing.JToggleButton jToggleButton177;
    private javax.swing.JToggleButton jToggleButton178;
    private javax.swing.JToggleButton jToggleButton179;
    private javax.swing.JToggleButton jToggleButton180;
    private javax.swing.JToggleButton jToggleButton181;
    private javax.swing.JToggleButton jToggleButton182;
    private javax.swing.JToggleButton jToggleButton183;
    private javax.swing.JToggleButton jToggleButton184;
    private javax.swing.JToggleButton jToggleButton185;
    private javax.swing.JToggleButton jToggleButton186;
    private javax.swing.JToggleButton jToggleButton187;
    private javax.swing.JToggleButton jToggleButton188;
    private javax.swing.JToggleButton jToggleButton189;
    private javax.swing.JToggleButton jToggleButton190;
    private javax.swing.JToggleButton jToggleButton191;
    private javax.swing.JToggleButton jToggleButton192;
    private javax.swing.JToggleButton jToggleButton193;
    private javax.swing.JToggleButton jToggleButton194;
    private javax.swing.JToggleButton jToggleButton195;
    private javax.swing.JToggleButton jToggleButton196;
    private javax.swing.JToggleButton jToggleButton197;
    private javax.swing.JToggleButton jToggleButton198;
    private javax.swing.JToggleButton jToggleButton199;
    private javax.swing.JToggleButton jToggleButton200;
    private javax.swing.JToggleButton jToggleButton201;
    private javax.swing.JToggleButton jToggleButton202;
    private javax.swing.JToggleButton jToggleButton203;
    private javax.swing.JToggleButton jToggleButton204;
    private javax.swing.JToggleButton jToggleButton205;
    private javax.swing.JToggleButton jToggleButton206;
    private javax.swing.JToggleButton memoBtn20;
    private javax.swing.JPanel npi2Panel;
    private javax.swing.JCheckBox npiCheck1;
    private javax.swing.JCheckBox npiCheck10;
    private javax.swing.JCheckBox npiCheck2;
    private javax.swing.JCheckBox npiCheck3;
    private javax.swing.JCheckBox npiCheck4;
    private javax.swing.JCheckBox npiCheck5;
    private javax.swing.JCheckBox npiCheck6;
    private javax.swing.JCheckBox npiCheck7;
    private javax.swing.JCheckBox npiCheck8;
    private javax.swing.JCheckBox npiCheck9;
    private javax.swing.ButtonGroup npiFreqBtnGroup1;
    private javax.swing.ButtonGroup npiFreqBtnGroup10;
    private javax.swing.ButtonGroup npiFreqBtnGroup2;
    private javax.swing.ButtonGroup npiFreqBtnGroup3;
    private javax.swing.ButtonGroup npiFreqBtnGroup4;
    private javax.swing.ButtonGroup npiFreqBtnGroup5;
    private javax.swing.ButtonGroup npiFreqBtnGroup6;
    private javax.swing.ButtonGroup npiFreqBtnGroup7;
    private javax.swing.ButtonGroup npiFreqBtnGroup8;
    private javax.swing.ButtonGroup npiFreqBtnGroup9;
    private javax.swing.ButtonGroup npiGravBtnGroup1;
    private javax.swing.ButtonGroup npiGravBtnGroup10;
    private javax.swing.ButtonGroup npiGravBtnGroup2;
    private javax.swing.ButtonGroup npiGravBtnGroup3;
    private javax.swing.ButtonGroup npiGravBtnGroup4;
    private javax.swing.ButtonGroup npiGravBtnGroup5;
    private javax.swing.ButtonGroup npiGravBtnGroup6;
    private javax.swing.ButtonGroup npiGravBtnGroup7;
    private javax.swing.ButtonGroup npiGravBtnGroup8;
    private javax.swing.ButtonGroup npiGravBtnGroup9;
    private javax.swing.JPanel npiPanel;
    private javax.swing.JScrollPane npiScroll;
    private javax.swing.JLabel npiTotal;
    private javax.swing.JLabel npiTotal1;
    private javax.swing.JLabel npiTotal10;
    private javax.swing.JLabel npiTotal2;
    private javax.swing.JLabel npiTotal3;
    private javax.swing.JLabel npiTotal4;
    private javax.swing.JLabel npiTotal5;
    private javax.swing.JLabel npiTotal6;
    private javax.swing.JLabel npiTotal7;
    private javax.swing.JLabel npiTotal8;
    private javax.swing.JLabel npiTotal9;
    private javax.swing.JToggleButton orientacioBtn20;
    private javax.swing.JToggleButton raoBtn19;
    private javax.swing.JToggleButton raoBtn21;
    private javax.swing.JToggleButton raoBtn27;
    private javax.swing.JToggleButton raoBtn28;
    // End of variables declaration//GEN-END:variables
}
