/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.tests;

import controlador.Utils;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import model.Pacient;

import java.util.Properties;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JToggleButton;

/**
 *
 * @author a630703
 */
public class PANAS extends Test  {
    
    
    /**
     * Creates new form Test
     *
     * @param pacientActual
     */
    public PANAS(Pacient pacientActual) {
        super(pacientActual);
        initComponents();

        label = "PANAS";
        numPaginesTotal = this.getComponentCount();
        
        initTaula(PANASPanel);
       // PANAS.initTaula(PANASPanel,AfectivoNegativo);
        //PANAS.initTaula(PANASPanel,PanasTotal);
    }
    
    
 


    @Override
    public void guardarResultats(Properties prop) {
        // PANAS
        Utils.setProperty(prop,"AfectPositivo",AfectivoPositivo);
        Utils.setProperty(prop,"AfectNegativo",AfectivoNegativo);
        Utils.setProperty(prop,"PanasTotal",PanasTotal);
    }
    
    public void actualitzaResultatTaula(JPanel panel){ // static?
        int countTotal = 0;
        int countPositivo =0;
        int countNegativo =0;
        String name ="";
        for (Component com : panel.getComponents()){
            if (com instanceof JToggleButton){
                if(((JToggleButton)com).isSelected()){
                    
                    System.out.println(name);
                    name = com.getName();
                    countTotal += Integer.parseInt(((JToggleButton)com).getText());
                    
                    if ( name=="positivo"){
                        countPositivo += Integer.parseInt(((JToggleButton)com).getText());
                    } else {
                        countNegativo += Integer.parseInt(((JToggleButton)com).getText());
                    }
                    
                }
            }
        }
        PanasTotal.setText(countTotal+"");
        AfectivoPositivo.setText(countPositivo+"");
        AfectivoNegativo.setText(countNegativo+"");
    }

    public void initTaula(final JPanel panel){ // static?
        for (Component com : panel.getComponents()){
            if (com instanceof JToggleButton){
                ((JToggleButton)com).addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        actualitzaResultatTaula(panel);
                    }
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        eptBtnGroup1 = new javax.swing.ButtonGroup();
        eptBtnGroup2 = new javax.swing.ButtonGroup();
        eptBtnGroup3 = new javax.swing.ButtonGroup();
        eptBtnGroup4 = new javax.swing.ButtonGroup();
        eptBtnGroup5 = new javax.swing.ButtonGroup();
        eptBtnGroup6 = new javax.swing.ButtonGroup();
        eptBtnGroup7 = new javax.swing.ButtonGroup();
        eptBtnGroup8 = new javax.swing.ButtonGroup();
        eptBtnGroup9 = new javax.swing.ButtonGroup();
        eptBtnGroup10 = new javax.swing.ButtonGroup();
        eptBtnGroup11 = new javax.swing.ButtonGroup();
        eptBtnGroup12 = new javax.swing.ButtonGroup();
        eptBtnGroup13 = new javax.swing.ButtonGroup();
        eptBtnGroup14 = new javax.swing.ButtonGroup();
        eptBtnGroup15 = new javax.swing.ButtonGroup();
        eptBtnGroup16 = new javax.swing.ButtonGroup();
        eptBtnGroup17 = new javax.swing.ButtonGroup();
        eptBtnGroup18 = new javax.swing.ButtonGroup();
        eptBtnGroup19 = new javax.swing.ButtonGroup();
        eptBtnGroup20 = new javax.swing.ButtonGroup();
        eptScroll = new javax.swing.JScrollPane();
        eptPanel = new javax.swing.JPanel();
        MOSLabel33 = new javax.swing.JLabel();
        MOSLabel32 = new javax.swing.JLabel();
        PANASPanel = new javax.swing.JPanel();
        MOSBtn1411 = new javax.swing.JToggleButton();
        MOSBtn14 = new javax.swing.JToggleButton();
        MOSBtn151 = new javax.swing.JToggleButton();
        MOSBtn15 = new javax.swing.JToggleButton();
        MOSBtn161 = new javax.swing.JToggleButton();
        MOSBtn16 = new javax.swing.JToggleButton();
        MOSBtn17 = new javax.swing.JToggleButton();
        MOSBtn171 = new javax.swing.JToggleButton();
        MOSBtn141 = new javax.swing.JToggleButton();
        MOSBtn1511 = new javax.swing.JToggleButton();
        MOSBtn1611 = new javax.swing.JToggleButton();
        MOSBtn1711 = new javax.swing.JToggleButton();
        MOSFBtn14 = new javax.swing.JToggleButton();
        MOSFBtn15 = new javax.swing.JToggleButton();
        MOSFBtn16 = new javax.swing.JToggleButton();
        MOSFBtn17 = new javax.swing.JToggleButton();
        MOSDBtn14 = new javax.swing.JToggleButton();
        MOSDBtn15 = new javax.swing.JToggleButton();
        MOSDBtn16 = new javax.swing.JToggleButton();
        MOSDBtn17 = new javax.swing.JToggleButton();
        MOSLabel112 = new javax.swing.JLabel();
        MOSLabel11 = new javax.swing.JLabel();
        MOSLabel149 = new javax.swing.JLabel();
        MOSLabel150 = new javax.swing.JLabel();
        eptLabel151 = new javax.swing.JLabel();
        eptLabel152 = new javax.swing.JLabel();
        eptLabel153 = new javax.swing.JLabel();
        eptLabel154 = new javax.swing.JLabel();
        eptLabel155 = new javax.swing.JLabel();
        MOSLabel114 = new javax.swing.JLabel();
        MOSLabel53 = new javax.swing.JLabel();
        MOSLabel54 = new javax.swing.JLabel();
        MOSLabel55 = new javax.swing.JLabel();
        MOSLabel56 = new javax.swing.JLabel();
        MOSLabel57 = new javax.swing.JLabel();
        eptLabel58 = new javax.swing.JLabel();
        eptToggleButton37 = new javax.swing.JToggleButton();
        eptToggleButton38 = new javax.swing.JToggleButton();
        eptToggleButton39 = new javax.swing.JToggleButton();
        eptToggleButton40 = new javax.swing.JToggleButton();
        eptToggleButton41 = new javax.swing.JToggleButton();
        MOSLabel156 = new javax.swing.JLabel();
        eptBtn19 = new javax.swing.JToggleButton();
        eptBtn172 = new javax.swing.JToggleButton();
        eptBtn1512 = new javax.swing.JToggleButton();
        eptToggleButton42 = new javax.swing.JToggleButton();
        eptDBtn18 = new javax.swing.JToggleButton();
        eptFBtn18 = new javax.swing.JToggleButton();
        eptLabel157 = new javax.swing.JLabel();
        MOSLabel59 = new javax.swing.JLabel();
        eptBtn18 = new javax.swing.JToggleButton();
        eptBtn20 = new javax.swing.JToggleButton();
        eptBtn21 = new javax.swing.JToggleButton();
        eptBtn22 = new javax.swing.JToggleButton();
        eptBtn23 = new javax.swing.JToggleButton();
        eptLabel158 = new javax.swing.JLabel();
        eptLabel60 = new javax.swing.JLabel();
        eptBtn24 = new javax.swing.JToggleButton();
        eptBtn25 = new javax.swing.JToggleButton();
        eptBtn26 = new javax.swing.JToggleButton();
        eptBtn27 = new javax.swing.JToggleButton();
        eptBtn28 = new javax.swing.JToggleButton();
        eptLabel159 = new javax.swing.JLabel();
        MOSLabel60 = new javax.swing.JLabel();
        eptBtn29 = new javax.swing.JToggleButton();
        eptBtn30 = new javax.swing.JToggleButton();
        eptBtn31 = new javax.swing.JToggleButton();
        eptBtn32 = new javax.swing.JToggleButton();
        eptBtn33 = new javax.swing.JToggleButton();
        eptLabel160 = new javax.swing.JLabel();
        MOSLabel62 = new javax.swing.JLabel();
        eptBtn34 = new javax.swing.JToggleButton();
        eptBtn35 = new javax.swing.JToggleButton();
        eptBtn36 = new javax.swing.JToggleButton();
        eptBtn37 = new javax.swing.JToggleButton();
        eptBtn38 = new javax.swing.JToggleButton();
        MOSLabel63 = new javax.swing.JLabel();
        eptBtn39 = new javax.swing.JToggleButton();
        eptBtn40 = new javax.swing.JToggleButton();
        eptBtn41 = new javax.swing.JToggleButton();
        eptBtn42 = new javax.swing.JToggleButton();
        eptBtn43 = new javax.swing.JToggleButton();
        eptLabel162 = new javax.swing.JLabel();
        eptLabel64 = new javax.swing.JLabel();
        eptBtn44 = new javax.swing.JToggleButton();
        eptBtn45 = new javax.swing.JToggleButton();
        eptBtn46 = new javax.swing.JToggleButton();
        eptBtn47 = new javax.swing.JToggleButton();
        eptBtn48 = new javax.swing.JToggleButton();
        eptLabel163 = new javax.swing.JLabel();
        eptLabel164 = new javax.swing.JLabel();
        MOSLabel66 = new javax.swing.JLabel();
        eptBtn54 = new javax.swing.JToggleButton();
        eptBtn55 = new javax.swing.JToggleButton();
        eptBtn56 = new javax.swing.JToggleButton();
        eptBtn57 = new javax.swing.JToggleButton();
        eptBtn58 = new javax.swing.JToggleButton();
        eptLabel165 = new javax.swing.JLabel();
        MOSLabel67 = new javax.swing.JLabel();
        eptBtn59 = new javax.swing.JToggleButton();
        eptBtn60 = new javax.swing.JToggleButton();
        eptBtn61 = new javax.swing.JToggleButton();
        eptBtn62 = new javax.swing.JToggleButton();
        eptBtn63 = new javax.swing.JToggleButton();
        eptLabel166 = new javax.swing.JLabel();
        eptLabel68 = new javax.swing.JLabel();
        eptBtn64 = new javax.swing.JToggleButton();
        eptBtn65 = new javax.swing.JToggleButton();
        eptBtn66 = new javax.swing.JToggleButton();
        eptBtn67 = new javax.swing.JToggleButton();
        eptBtn68 = new javax.swing.JToggleButton();
        eptLabel167 = new javax.swing.JLabel();
        MOSLabel69 = new javax.swing.JLabel();
        eptBtn69 = new javax.swing.JToggleButton();
        eptBtn70 = new javax.swing.JToggleButton();
        eptBtn71 = new javax.swing.JToggleButton();
        eptBtn72 = new javax.swing.JToggleButton();
        eptBtn73 = new javax.swing.JToggleButton();
        eptLabel168 = new javax.swing.JLabel();
        MOSLabel70 = new javax.swing.JLabel();
        eptBtn74 = new javax.swing.JToggleButton();
        eptBtn75 = new javax.swing.JToggleButton();
        eptBtn76 = new javax.swing.JToggleButton();
        eptBtn77 = new javax.swing.JToggleButton();
        eptBtn78 = new javax.swing.JToggleButton();
        eptLabel169 = new javax.swing.JLabel();
        MOSLabel71 = new javax.swing.JLabel();
        eptBtn79 = new javax.swing.JToggleButton();
        eptBtn80 = new javax.swing.JToggleButton();
        eptBtn81 = new javax.swing.JToggleButton();
        eptBtn82 = new javax.swing.JToggleButton();
        eptBtn83 = new javax.swing.JToggleButton();
        eptLabel170 = new javax.swing.JLabel();
        MOSLabel72 = new javax.swing.JLabel();
        eptBtn84 = new javax.swing.JToggleButton();
        eptBtn85 = new javax.swing.JToggleButton();
        eptBtn86 = new javax.swing.JToggleButton();
        eptBtn87 = new javax.swing.JToggleButton();
        eptBtn88 = new javax.swing.JToggleButton();
        eptLabel171 = new javax.swing.JLabel();
        MOSLabel73 = new javax.swing.JLabel();
        eptBtn89 = new javax.swing.JToggleButton();
        eptBtn90 = new javax.swing.JToggleButton();
        eptBtn91 = new javax.swing.JToggleButton();
        eptBtn92 = new javax.swing.JToggleButton();
        eptBtn93 = new javax.swing.JToggleButton();
        MOSLabel217 = new javax.swing.JLabel();
        AfectivoPositivo = new javax.swing.JLabel();
        MOSLabel218 = new javax.swing.JLabel();
        AfectivoNegativo = new javax.swing.JLabel();
        MOSLabel219 = new javax.swing.JLabel();
        PanasTotal = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        MOSLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MOSLabel33.setText("PANAS");

        MOSLabel32.setText("<html>A continuación se indican diversos sentimientos y emociones que suele experimentar la gente.<br>  Lea cada uno de ellos y, refiriéndolo a usted, conteste indicando como se ha sentido <b>habitualmente</b>.<br><br><i>Habitualmente (en general) me he sentido:</i></html> ");

        PANASPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PANAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        PANASPanel.setLayout(new java.awt.GridBagLayout());

        eptBtnGroup2.add(MOSBtn1411);
        MOSBtn1411.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(MOSBtn1411, gridBagConstraints);

        eptBtnGroup1.add(MOSBtn14);
        MOSBtn14.setText("1");
        MOSBtn14.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(MOSBtn14, gridBagConstraints);

        eptBtnGroup2.add(MOSBtn151);
        MOSBtn151.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(MOSBtn151, gridBagConstraints);

        eptBtnGroup1.add(MOSBtn15);
        MOSBtn15.setText("2");
        MOSBtn15.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(MOSBtn15, gridBagConstraints);

        eptBtnGroup2.add(MOSBtn161);
        MOSBtn161.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(MOSBtn161, gridBagConstraints);

        eptBtnGroup1.add(MOSBtn16);
        MOSBtn16.setText("3");
        MOSBtn16.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(MOSBtn16, gridBagConstraints);

        eptBtnGroup1.add(MOSBtn17);
        MOSBtn17.setText("5");
        MOSBtn17.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASPanel.add(MOSBtn17, gridBagConstraints);

        eptBtnGroup2.add(MOSBtn171);
        MOSBtn171.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASPanel.add(MOSBtn171, gridBagConstraints);

        eptBtnGroup3.add(MOSBtn141);
        MOSBtn141.setText("1");
        MOSBtn141.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(MOSBtn141, gridBagConstraints);

        eptBtnGroup3.add(MOSBtn1511);
        MOSBtn1511.setText("5");
        MOSBtn1511.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASPanel.add(MOSBtn1511, gridBagConstraints);

        eptBtnGroup5.add(MOSBtn1611);
        MOSBtn1611.setText("2");
        MOSBtn1611.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(MOSBtn1611, gridBagConstraints);

        eptBtnGroup3.add(MOSBtn1711);
        MOSBtn1711.setText("3");
        MOSBtn1711.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(MOSBtn1711, gridBagConstraints);

        eptBtnGroup4.add(MOSFBtn14);
        MOSFBtn14.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(MOSFBtn14, gridBagConstraints);

        eptBtnGroup4.add(MOSFBtn15);
        MOSFBtn15.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(MOSFBtn15, gridBagConstraints);

        eptBtnGroup5.add(MOSFBtn16);
        MOSFBtn16.setText("3");
        MOSFBtn16.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(MOSFBtn16, gridBagConstraints);

        eptBtnGroup5.add(MOSFBtn17);
        MOSFBtn17.setText("5");
        MOSFBtn17.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASPanel.add(MOSFBtn17, gridBagConstraints);

        eptBtnGroup6.add(MOSDBtn14);
        MOSDBtn14.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 2;
        PANASPanel.add(MOSDBtn14, gridBagConstraints);

        eptBtnGroup6.add(MOSDBtn15);
        MOSDBtn15.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(MOSDBtn15, gridBagConstraints);

        eptBtnGroup5.add(MOSDBtn16);
        MOSDBtn16.setText("1");
        MOSDBtn16.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(MOSDBtn16, gridBagConstraints);

        MOSDBtn17.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(MOSDBtn17, gridBagConstraints);

        MOSLabel112.setText("<html><center>Nada<br>(1)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 2);
        PANASPanel.add(MOSLabel112, gridBagConstraints);

        MOSLabel11.setText("<html><center>Algo<br>(2)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 2);
        PANASPanel.add(MOSLabel11, gridBagConstraints);

        MOSLabel149.setText("<html><center>Muchísimo<br>(5)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        PANASPanel.add(MOSLabel149, gridBagConstraints);

        MOSLabel150.setText("<html><center>Moderado<br>(3)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 2);
        PANASPanel.add(MOSLabel150, gridBagConstraints);

        eptLabel151.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        PANASPanel.add(eptLabel151, gridBagConstraints);

        eptLabel152.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        PANASPanel.add(eptLabel152, gridBagConstraints);

        eptLabel153.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        PANASPanel.add(eptLabel153, gridBagConstraints);

        eptLabel154.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        PANASPanel.add(eptLabel154, gridBagConstraints);

        eptLabel155.setText("6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        PANASPanel.add(eptLabel155, gridBagConstraints);

        MOSLabel114.setText("- Disgustado/a, molesto/a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        PANASPanel.add(MOSLabel114, gridBagConstraints);

        MOSLabel53.setText("- Interesado/a (que muestra interés)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASPanel.add(MOSLabel53, gridBagConstraints);

        MOSLabel54.setText("- Estresado/a, con malestar emocional o agobio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 8);
        PANASPanel.add(MOSLabel54, gridBagConstraints);

        MOSLabel55.setText("- Emocionado/a, animado/a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASPanel.add(MOSLabel55, gridBagConstraints);

        MOSLabel56.setText("- Enérgico/a, con vitalidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASPanel.add(MOSLabel56, gridBagConstraints);

        MOSLabel57.setText("- Culpable");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASPanel.add(MOSLabel57, gridBagConstraints);

        eptLabel58.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        PANASPanel.add(eptLabel58, gridBagConstraints);

        eptBtnGroup3.add(eptToggleButton37);
        eptToggleButton37.setText("2");
        eptToggleButton37.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptToggleButton37, gridBagConstraints);

        eptBtnGroup4.add(eptToggleButton38);
        eptToggleButton38.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptToggleButton38, gridBagConstraints);

        eptBtnGroup4.add(eptToggleButton39);
        eptToggleButton39.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASPanel.add(eptToggleButton39, gridBagConstraints);

        eptBtnGroup6.add(eptToggleButton40);
        eptToggleButton40.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptToggleButton40, gridBagConstraints);

        eptBtnGroup6.add(eptToggleButton41);
        eptToggleButton41.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptToggleButton41, gridBagConstraints);

        MOSLabel156.setText("<html><center>Bastante<br>(4)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        PANASPanel.add(MOSLabel156, gridBagConstraints);

        eptBtnGroup1.add(eptBtn19);
        eptBtn19.setText("4");
        eptBtn19.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn19, gridBagConstraints);

        eptBtnGroup2.add(eptBtn172);
        eptBtn172.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn172, gridBagConstraints);

        eptBtnGroup3.add(eptBtn1512);
        eptBtn1512.setText("4");
        eptBtn1512.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn1512, gridBagConstraints);

        eptBtnGroup4.add(eptToggleButton42);
        eptToggleButton42.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptToggleButton42, gridBagConstraints);

        eptBtnGroup6.add(eptDBtn18);
        eptDBtn18.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptDBtn18, gridBagConstraints);

        eptBtnGroup5.add(eptFBtn18);
        eptFBtn18.setText("4");
        eptFBtn18.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptFBtn18, gridBagConstraints);

        eptLabel157.setText("7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        PANASPanel.add(eptLabel157, gridBagConstraints);

        MOSLabel59.setText("- Asustado/a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASPanel.add(MOSLabel59, gridBagConstraints);

        eptBtnGroup7.add(eptBtn18);
        eptBtn18.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn18, gridBagConstraints);

        eptBtnGroup7.add(eptBtn20);
        eptBtn20.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn20, gridBagConstraints);

        eptBtnGroup7.add(eptBtn21);
        eptBtn21.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn21, gridBagConstraints);

        eptBtnGroup7.add(eptBtn22);
        eptBtn22.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn22, gridBagConstraints);

        eptBtnGroup7.add(eptBtn23);
        eptBtn23.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASPanel.add(eptBtn23, gridBagConstraints);

        eptLabel158.setText("8");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        PANASPanel.add(eptLabel158, gridBagConstraints);

        eptLabel60.setText("- Enojado/a, hostil");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASPanel.add(eptLabel60, gridBagConstraints);

        eptBtnGroup8.add(eptBtn24);
        eptBtn24.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn24, gridBagConstraints);

        eptBtnGroup8.add(eptBtn25);
        eptBtn25.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn25, gridBagConstraints);

        eptBtnGroup8.add(eptBtn26);
        eptBtn26.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn26, gridBagConstraints);

        eptBtnGroup8.add(eptBtn27);
        eptBtn27.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn27, gridBagConstraints);

        eptBtnGroup8.add(eptBtn28);
        eptBtn28.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASPanel.add(eptBtn28, gridBagConstraints);

        eptLabel159.setText("9");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        PANASPanel.add(eptLabel159, gridBagConstraints);

        MOSLabel60.setText("- Entusiasmado/a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASPanel.add(MOSLabel60, gridBagConstraints);

        eptBtnGroup9.add(eptBtn29);
        eptBtn29.setText("1");
        eptBtn29.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn29, gridBagConstraints);

        eptBtnGroup9.add(eptBtn30);
        eptBtn30.setText("2");
        eptBtn30.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn30, gridBagConstraints);

        eptBtnGroup9.add(eptBtn31);
        eptBtn31.setText("3");
        eptBtn31.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn31, gridBagConstraints);

        eptBtnGroup9.add(eptBtn32);
        eptBtn32.setText("4");
        eptBtn32.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn32, gridBagConstraints);

        eptBtnGroup9.add(eptBtn33);
        eptBtn33.setText("5");
        eptBtn33.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASPanel.add(eptBtn33, gridBagConstraints);

        eptLabel160.setText("10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        PANASPanel.add(eptLabel160, gridBagConstraints);

        MOSLabel62.setText("- Orgulloso/a (de algo) satisfecho/a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASPanel.add(MOSLabel62, gridBagConstraints);

        eptBtnGroup10.add(eptBtn34);
        eptBtn34.setText("1");
        eptBtn34.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn34, gridBagConstraints);

        eptBtnGroup10.add(eptBtn35);
        eptBtn35.setText("2");
        eptBtn35.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn35, gridBagConstraints);

        eptBtnGroup10.add(eptBtn36);
        eptBtn36.setText("3");
        eptBtn36.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn36, gridBagConstraints);

        eptBtnGroup10.add(eptBtn37);
        eptBtn37.setText("4");
        eptBtn37.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn37, gridBagConstraints);

        eptBtnGroup10.add(eptBtn38);
        eptBtn38.setText("5");
        eptBtn38.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASPanel.add(eptBtn38, gridBagConstraints);

        MOSLabel63.setText("- Alerta (despierto/a), despejado/a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASPanel.add(MOSLabel63, gridBagConstraints);

        eptBtnGroup12.add(eptBtn39);
        eptBtn39.setText("1");
        eptBtn39.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn39, gridBagConstraints);

        eptBtnGroup12.add(eptBtn40);
        eptBtn40.setText("2");
        eptBtn40.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn40, gridBagConstraints);

        eptBtnGroup12.add(eptBtn41);
        eptBtn41.setText("3");
        eptBtn41.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn41, gridBagConstraints);

        eptBtnGroup12.add(eptBtn42);
        eptBtn42.setText("4");
        eptBtn42.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn42, gridBagConstraints);

        eptBtnGroup12.add(eptBtn43);
        eptBtn43.setText("5");
        eptBtn43.setName("positivo"); // NOI18N
        eptBtn43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eptBtn43ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASPanel.add(eptBtn43, gridBagConstraints);

        eptLabel162.setText("11");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        PANASPanel.add(eptLabel162, gridBagConstraints);

        eptLabel64.setText("- Irritable, malhumorado/a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASPanel.add(eptLabel64, gridBagConstraints);

        eptBtnGroup11.add(eptBtn44);
        eptBtn44.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn44, gridBagConstraints);

        eptBtnGroup11.add(eptBtn45);
        eptBtn45.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn45, gridBagConstraints);

        eptBtnGroup11.add(eptBtn46);
        eptBtn46.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn46, gridBagConstraints);

        eptBtnGroup11.add(eptBtn47);
        eptBtn47.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn47, gridBagConstraints);

        eptBtnGroup11.add(eptBtn48);
        eptBtn48.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASPanel.add(eptBtn48, gridBagConstraints);

        eptLabel163.setText("12");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        PANASPanel.add(eptLabel163, gridBagConstraints);

        eptLabel164.setText("13");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        PANASPanel.add(eptLabel164, gridBagConstraints);

        MOSLabel66.setText("- Avergonzado/a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASPanel.add(MOSLabel66, gridBagConstraints);

        eptBtnGroup13.add(eptBtn54);
        eptBtn54.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn54, gridBagConstraints);

        eptBtnGroup13.add(eptBtn55);
        eptBtn55.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn55, gridBagConstraints);

        eptBtnGroup13.add(eptBtn56);
        eptBtn56.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn56, gridBagConstraints);

        eptBtnGroup13.add(eptBtn57);
        eptBtn57.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn57, gridBagConstraints);

        eptBtnGroup13.add(eptBtn58);
        eptBtn58.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASPanel.add(eptBtn58, gridBagConstraints);

        eptLabel165.setText("14");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        PANASPanel.add(eptLabel165, gridBagConstraints);

        MOSLabel67.setText("- Inspirado/a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASPanel.add(MOSLabel67, gridBagConstraints);

        eptBtnGroup14.add(eptBtn59);
        eptBtn59.setText("1");
        eptBtn59.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn59, gridBagConstraints);

        eptBtnGroup14.add(eptBtn60);
        eptBtn60.setText("2");
        eptBtn60.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn60, gridBagConstraints);

        eptBtnGroup14.add(eptBtn61);
        eptBtn61.setText("3");
        eptBtn61.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn61, gridBagConstraints);

        eptBtnGroup14.add(eptBtn62);
        eptBtn62.setText("4");
        eptBtn62.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn62, gridBagConstraints);

        eptBtnGroup14.add(eptBtn63);
        eptBtn63.setText("5");
        eptBtn63.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASPanel.add(eptBtn63, gridBagConstraints);

        eptLabel166.setText("15");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        PANASPanel.add(eptLabel166, gridBagConstraints);

        eptLabel68.setText("- Nervioso/a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASPanel.add(eptLabel68, gridBagConstraints);

        eptBtnGroup15.add(eptBtn64);
        eptBtn64.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn64, gridBagConstraints);

        eptBtnGroup15.add(eptBtn65);
        eptBtn65.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn65, gridBagConstraints);

        eptBtnGroup15.add(eptBtn66);
        eptBtn66.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn66, gridBagConstraints);

        eptBtnGroup15.add(eptBtn67);
        eptBtn67.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn67, gridBagConstraints);

        eptBtnGroup15.add(eptBtn68);
        eptBtn68.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASPanel.add(eptBtn68, gridBagConstraints);

        eptLabel167.setText("16");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        PANASPanel.add(eptLabel167, gridBagConstraints);

        MOSLabel69.setText("- Decidido/a, atrevido/a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASPanel.add(MOSLabel69, gridBagConstraints);

        eptBtnGroup16.add(eptBtn69);
        eptBtn69.setText("1");
        eptBtn69.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn69, gridBagConstraints);

        eptBtnGroup16.add(eptBtn70);
        eptBtn70.setText("2");
        eptBtn70.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn70, gridBagConstraints);

        eptBtnGroup16.add(eptBtn71);
        eptBtn71.setText("3");
        eptBtn71.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn71, gridBagConstraints);

        eptBtnGroup16.add(eptBtn72);
        eptBtn72.setText("4");
        eptBtn72.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn72, gridBagConstraints);

        eptBtnGroup16.add(eptBtn73);
        eptBtn73.setText("5");
        eptBtn73.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASPanel.add(eptBtn73, gridBagConstraints);

        eptLabel168.setText("17");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 19;
        PANASPanel.add(eptLabel168, gridBagConstraints);

        MOSLabel70.setText("- Atento/a o consciente (pongo atención)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASPanel.add(MOSLabel70, gridBagConstraints);

        eptBtnGroup17.add(eptBtn74);
        eptBtn74.setText("1");
        eptBtn74.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn74, gridBagConstraints);

        eptBtnGroup17.add(eptBtn75);
        eptBtn75.setText("2");
        eptBtn75.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn75, gridBagConstraints);

        eptBtnGroup17.add(eptBtn76);
        eptBtn76.setText("3");
        eptBtn76.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn76, gridBagConstraints);

        eptBtnGroup17.add(eptBtn77);
        eptBtn77.setText("4");
        eptBtn77.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn77, gridBagConstraints);

        eptBtnGroup17.add(eptBtn78);
        eptBtn78.setText("5");
        eptBtn78.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASPanel.add(eptBtn78, gridBagConstraints);

        eptLabel169.setText("18");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        PANASPanel.add(eptLabel169, gridBagConstraints);

        MOSLabel71.setText("- Intranquilo/a o inquieto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASPanel.add(MOSLabel71, gridBagConstraints);

        eptBtnGroup18.add(eptBtn79);
        eptBtn79.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn79, gridBagConstraints);

        eptBtnGroup18.add(eptBtn80);
        eptBtn80.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn80, gridBagConstraints);

        eptBtnGroup18.add(eptBtn81);
        eptBtn81.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn81, gridBagConstraints);

        eptBtnGroup18.add(eptBtn82);
        eptBtn82.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn82, gridBagConstraints);

        eptBtnGroup18.add(eptBtn83);
        eptBtn83.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASPanel.add(eptBtn83, gridBagConstraints);

        eptLabel170.setText("19");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 21;
        PANASPanel.add(eptLabel170, gridBagConstraints);

        MOSLabel72.setText("- Activo/a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASPanel.add(MOSLabel72, gridBagConstraints);

        eptBtnGroup19.add(eptBtn84);
        eptBtn84.setText("1");
        eptBtn84.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn84, gridBagConstraints);

        eptBtnGroup19.add(eptBtn85);
        eptBtn85.setText("2");
        eptBtn85.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn85, gridBagConstraints);

        eptBtnGroup19.add(eptBtn86);
        eptBtn86.setText("3");
        eptBtn86.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn86, gridBagConstraints);

        eptBtnGroup19.add(eptBtn87);
        eptBtn87.setText("4");
        eptBtn87.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn87, gridBagConstraints);

        eptBtnGroup19.add(eptBtn88);
        eptBtn88.setText("5");
        eptBtn88.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASPanel.add(eptBtn88, gridBagConstraints);

        eptLabel171.setText("20");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        PANASPanel.add(eptLabel171, gridBagConstraints);

        MOSLabel73.setText("- Temeroso/a, con miedo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        PANASPanel.add(MOSLabel73, gridBagConstraints);

        eptBtnGroup20.add(eptBtn89);
        eptBtn89.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn89, gridBagConstraints);

        eptBtnGroup20.add(eptBtn90);
        eptBtn90.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn90, gridBagConstraints);

        eptBtnGroup20.add(eptBtn91);
        eptBtn91.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn91, gridBagConstraints);

        eptBtnGroup20.add(eptBtn92);
        eptBtn92.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        PANASPanel.add(eptBtn92, gridBagConstraints);

        eptBtnGroup20.add(eptBtn93);
        eptBtn93.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        PANASPanel.add(eptBtn93, gridBagConstraints);

        MOSLabel217.setText("Afectivo Positivo:");

        AfectivoPositivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AfectivoPositivo.setText("0");

        MOSLabel218.setText("Afectivo Negativo:");

        AfectivoNegativo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AfectivoNegativo.setText("0");

        MOSLabel219.setText("Total:");

        PanasTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PanasTotal.setText("0");

        javax.swing.GroupLayout eptPanelLayout = new javax.swing.GroupLayout(eptPanel);
        eptPanel.setLayout(eptPanelLayout);
        eptPanelLayout.setHorizontalGroup(
            eptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eptPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MOSLabel33)
                    .addGroup(eptPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(eptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MOSLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(eptPanelLayout.createSequentialGroup()
                                .addComponent(PANASPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(eptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(eptPanelLayout.createSequentialGroup()
                                        .addComponent(MOSLabel217)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AfectivoPositivo))
                                    .addGroup(eptPanelLayout.createSequentialGroup()
                                        .addComponent(MOSLabel218)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AfectivoNegativo))
                                    .addGroup(eptPanelLayout.createSequentialGroup()
                                        .addComponent(MOSLabel219)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PanasTotal)))))))
                .addGap(91, 91, 91))
        );
        eptPanelLayout.setVerticalGroup(
            eptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eptPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MOSLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MOSLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(eptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PANASPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(eptPanelLayout.createSequentialGroup()
                        .addGroup(eptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MOSLabel217)
                            .addComponent(AfectivoPositivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(eptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MOSLabel218)
                            .addComponent(AfectivoNegativo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(eptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MOSLabel219)
                            .addComponent(PanasTotal))))
                .addContainerGap())
        );

        eptScroll.setViewportView(eptPanel);

        add(eptScroll, "card1");
    }// </editor-fold>//GEN-END:initComponents

    private void eptBtn43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eptBtn43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eptBtn43ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AfectivoNegativo;
    private javax.swing.JLabel AfectivoPositivo;
    private javax.swing.JToggleButton MOSBtn14;
    private javax.swing.JToggleButton MOSBtn141;
    private javax.swing.JToggleButton MOSBtn1411;
    private javax.swing.JToggleButton MOSBtn15;
    private javax.swing.JToggleButton MOSBtn151;
    private javax.swing.JToggleButton MOSBtn1511;
    private javax.swing.JToggleButton MOSBtn16;
    private javax.swing.JToggleButton MOSBtn161;
    private javax.swing.JToggleButton MOSBtn1611;
    private javax.swing.JToggleButton MOSBtn17;
    private javax.swing.JToggleButton MOSBtn171;
    private javax.swing.JToggleButton MOSBtn1711;
    private javax.swing.JToggleButton MOSDBtn14;
    private javax.swing.JToggleButton MOSDBtn15;
    private javax.swing.JToggleButton MOSDBtn16;
    private javax.swing.JToggleButton MOSDBtn17;
    private javax.swing.JToggleButton MOSFBtn14;
    private javax.swing.JToggleButton MOSFBtn15;
    private javax.swing.JToggleButton MOSFBtn16;
    private javax.swing.JToggleButton MOSFBtn17;
    private javax.swing.JLabel MOSLabel11;
    private javax.swing.JLabel MOSLabel112;
    private javax.swing.JLabel MOSLabel114;
    private javax.swing.JLabel MOSLabel149;
    private javax.swing.JLabel MOSLabel150;
    private javax.swing.JLabel MOSLabel156;
    private javax.swing.JLabel MOSLabel217;
    private javax.swing.JLabel MOSLabel218;
    private javax.swing.JLabel MOSLabel219;
    private javax.swing.JLabel MOSLabel32;
    private javax.swing.JLabel MOSLabel33;
    private javax.swing.JLabel MOSLabel53;
    private javax.swing.JLabel MOSLabel54;
    private javax.swing.JLabel MOSLabel55;
    private javax.swing.JLabel MOSLabel56;
    private javax.swing.JLabel MOSLabel57;
    private javax.swing.JLabel MOSLabel59;
    private javax.swing.JLabel MOSLabel60;
    private javax.swing.JLabel MOSLabel62;
    private javax.swing.JLabel MOSLabel63;
    private javax.swing.JLabel MOSLabel66;
    private javax.swing.JLabel MOSLabel67;
    private javax.swing.JLabel MOSLabel69;
    private javax.swing.JLabel MOSLabel70;
    private javax.swing.JLabel MOSLabel71;
    private javax.swing.JLabel MOSLabel72;
    private javax.swing.JLabel MOSLabel73;
    private javax.swing.JPanel PANASPanel;
    private javax.swing.JLabel PanasTotal;
    private javax.swing.JToggleButton eptBtn1512;
    private javax.swing.JToggleButton eptBtn172;
    private javax.swing.JToggleButton eptBtn18;
    private javax.swing.JToggleButton eptBtn19;
    private javax.swing.JToggleButton eptBtn20;
    private javax.swing.JToggleButton eptBtn21;
    private javax.swing.JToggleButton eptBtn22;
    private javax.swing.JToggleButton eptBtn23;
    private javax.swing.JToggleButton eptBtn24;
    private javax.swing.JToggleButton eptBtn25;
    private javax.swing.JToggleButton eptBtn26;
    private javax.swing.JToggleButton eptBtn27;
    private javax.swing.JToggleButton eptBtn28;
    private javax.swing.JToggleButton eptBtn29;
    private javax.swing.JToggleButton eptBtn30;
    private javax.swing.JToggleButton eptBtn31;
    private javax.swing.JToggleButton eptBtn32;
    private javax.swing.JToggleButton eptBtn33;
    private javax.swing.JToggleButton eptBtn34;
    private javax.swing.JToggleButton eptBtn35;
    private javax.swing.JToggleButton eptBtn36;
    private javax.swing.JToggleButton eptBtn37;
    private javax.swing.JToggleButton eptBtn38;
    private javax.swing.JToggleButton eptBtn39;
    private javax.swing.JToggleButton eptBtn40;
    private javax.swing.JToggleButton eptBtn41;
    private javax.swing.JToggleButton eptBtn42;
    private javax.swing.JToggleButton eptBtn43;
    private javax.swing.JToggleButton eptBtn44;
    private javax.swing.JToggleButton eptBtn45;
    private javax.swing.JToggleButton eptBtn46;
    private javax.swing.JToggleButton eptBtn47;
    private javax.swing.JToggleButton eptBtn48;
    private javax.swing.JToggleButton eptBtn54;
    private javax.swing.JToggleButton eptBtn55;
    private javax.swing.JToggleButton eptBtn56;
    private javax.swing.JToggleButton eptBtn57;
    private javax.swing.JToggleButton eptBtn58;
    private javax.swing.JToggleButton eptBtn59;
    private javax.swing.JToggleButton eptBtn60;
    private javax.swing.JToggleButton eptBtn61;
    private javax.swing.JToggleButton eptBtn62;
    private javax.swing.JToggleButton eptBtn63;
    private javax.swing.JToggleButton eptBtn64;
    private javax.swing.JToggleButton eptBtn65;
    private javax.swing.JToggleButton eptBtn66;
    private javax.swing.JToggleButton eptBtn67;
    private javax.swing.JToggleButton eptBtn68;
    private javax.swing.JToggleButton eptBtn69;
    private javax.swing.JToggleButton eptBtn70;
    private javax.swing.JToggleButton eptBtn71;
    private javax.swing.JToggleButton eptBtn72;
    private javax.swing.JToggleButton eptBtn73;
    private javax.swing.JToggleButton eptBtn74;
    private javax.swing.JToggleButton eptBtn75;
    private javax.swing.JToggleButton eptBtn76;
    private javax.swing.JToggleButton eptBtn77;
    private javax.swing.JToggleButton eptBtn78;
    private javax.swing.JToggleButton eptBtn79;
    private javax.swing.JToggleButton eptBtn80;
    private javax.swing.JToggleButton eptBtn81;
    private javax.swing.JToggleButton eptBtn82;
    private javax.swing.JToggleButton eptBtn83;
    private javax.swing.JToggleButton eptBtn84;
    private javax.swing.JToggleButton eptBtn85;
    private javax.swing.JToggleButton eptBtn86;
    private javax.swing.JToggleButton eptBtn87;
    private javax.swing.JToggleButton eptBtn88;
    private javax.swing.JToggleButton eptBtn89;
    private javax.swing.JToggleButton eptBtn90;
    private javax.swing.JToggleButton eptBtn91;
    private javax.swing.JToggleButton eptBtn92;
    private javax.swing.JToggleButton eptBtn93;
    private javax.swing.ButtonGroup eptBtnGroup1;
    private javax.swing.ButtonGroup eptBtnGroup10;
    private javax.swing.ButtonGroup eptBtnGroup11;
    private javax.swing.ButtonGroup eptBtnGroup12;
    private javax.swing.ButtonGroup eptBtnGroup13;
    private javax.swing.ButtonGroup eptBtnGroup14;
    private javax.swing.ButtonGroup eptBtnGroup15;
    private javax.swing.ButtonGroup eptBtnGroup16;
    private javax.swing.ButtonGroup eptBtnGroup17;
    private javax.swing.ButtonGroup eptBtnGroup18;
    private javax.swing.ButtonGroup eptBtnGroup19;
    private javax.swing.ButtonGroup eptBtnGroup2;
    private javax.swing.ButtonGroup eptBtnGroup20;
    private javax.swing.ButtonGroup eptBtnGroup3;
    private javax.swing.ButtonGroup eptBtnGroup4;
    private javax.swing.ButtonGroup eptBtnGroup5;
    private javax.swing.ButtonGroup eptBtnGroup6;
    private javax.swing.ButtonGroup eptBtnGroup7;
    private javax.swing.ButtonGroup eptBtnGroup8;
    private javax.swing.ButtonGroup eptBtnGroup9;
    private javax.swing.JToggleButton eptDBtn18;
    private javax.swing.JToggleButton eptFBtn18;
    private javax.swing.JLabel eptLabel151;
    private javax.swing.JLabel eptLabel152;
    private javax.swing.JLabel eptLabel153;
    private javax.swing.JLabel eptLabel154;
    private javax.swing.JLabel eptLabel155;
    private javax.swing.JLabel eptLabel157;
    private javax.swing.JLabel eptLabel158;
    private javax.swing.JLabel eptLabel159;
    private javax.swing.JLabel eptLabel160;
    private javax.swing.JLabel eptLabel162;
    private javax.swing.JLabel eptLabel163;
    private javax.swing.JLabel eptLabel164;
    private javax.swing.JLabel eptLabel165;
    private javax.swing.JLabel eptLabel166;
    private javax.swing.JLabel eptLabel167;
    private javax.swing.JLabel eptLabel168;
    private javax.swing.JLabel eptLabel169;
    private javax.swing.JLabel eptLabel170;
    private javax.swing.JLabel eptLabel171;
    private javax.swing.JLabel eptLabel58;
    private javax.swing.JLabel eptLabel60;
    private javax.swing.JLabel eptLabel64;
    private javax.swing.JLabel eptLabel68;
    private javax.swing.JPanel eptPanel;
    private javax.swing.JScrollPane eptScroll;
    private javax.swing.JToggleButton eptToggleButton37;
    private javax.swing.JToggleButton eptToggleButton38;
    private javax.swing.JToggleButton eptToggleButton39;
    private javax.swing.JToggleButton eptToggleButton40;
    private javax.swing.JToggleButton eptToggleButton41;
    private javax.swing.JToggleButton eptToggleButton42;
    // End of variables declaration//GEN-END:variables
}
