/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.tests;

import controlador.Utils;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import model.Pacient;

import java.util.Properties;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JToggleButton;

/**
 *
 * @author a630703
 */
public class PANAS extends Test  {
    
    
    /**
     * Creates new form Test
     *
     * @param pacientActual
     */
    public PANAS(Pacient pacientActual) {
        super(pacientActual);
        initComponents();

        label = "PANAS";
        numPaginesTotal = this.getComponentCount();
        
        initTaula(MOSSSPanel);
       // PANAS.initTaula(PANASPanel,AfectivoNegativo);
        //PANAS.initTaula(PANASPanel,PanasTotal);
    }
    
    
 


    @Override
    public void guardarResultats(Properties prop) {
        // PANAS
        Utils.setProperty(prop,"AfectPositivo",AfectivoPositivo);
        Utils.setProperty(prop,"AfectNegativo",AfectivoNegativo);
        Utils.setProperty(prop,"PanasTotal",PanasTotal);
    }
    
    public void actualitzaResultatTaula(JPanel panel){ // static?
        int countTotal = 0;
        int countPositivo =0;
        int countNegativo =0;
        String name ="";
        for (Component com : panel.getComponents()){
            if (com instanceof JToggleButton){
                if(((JToggleButton)com).isSelected()){
                    
                    System.out.println(name);
                    name = com.getName();
                    countTotal += Integer.parseInt(((JToggleButton)com).getText());
                    
                    if ( name=="positivo"){
                        countPositivo += Integer.parseInt(((JToggleButton)com).getText());
                    } else {
                        countNegativo += Integer.parseInt(((JToggleButton)com).getText());
                    }
                    
                }
            }
        }
        PanasTotal.setText(countTotal+"");
        AfectivoPositivo.setText(countPositivo+"");
        AfectivoNegativo.setText(countNegativo+"");
    }

    public void initTaula(final JPanel panel){ // static?
        for (Component com : panel.getComponents()){
            if (com instanceof JToggleButton){
                ((JToggleButton)com).addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        actualitzaResultatTaula(panel);
                    }
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        eptBtnGroup1 = new javax.swing.ButtonGroup();
        eptBtnGroup2 = new javax.swing.ButtonGroup();
        eptBtnGroup3 = new javax.swing.ButtonGroup();
        eptBtnGroup4 = new javax.swing.ButtonGroup();
        eptBtnGroup5 = new javax.swing.ButtonGroup();
        eptBtnGroup6 = new javax.swing.ButtonGroup();
        eptBtnGroup7 = new javax.swing.ButtonGroup();
        eptBtnGroup8 = new javax.swing.ButtonGroup();
        eptBtnGroup9 = new javax.swing.ButtonGroup();
        eptBtnGroup10 = new javax.swing.ButtonGroup();
        eptBtnGroup11 = new javax.swing.ButtonGroup();
        eptBtnGroup12 = new javax.swing.ButtonGroup();
        eptBtnGroup13 = new javax.swing.ButtonGroup();
        eptBtnGroup14 = new javax.swing.ButtonGroup();
        eptBtnGroup15 = new javax.swing.ButtonGroup();
        eptBtnGroup16 = new javax.swing.ButtonGroup();
        eptBtnGroup17 = new javax.swing.ButtonGroup();
        eptBtnGroup18 = new javax.swing.ButtonGroup();
        eptBtnGroup19 = new javax.swing.ButtonGroup();
        eptBtnGroup20 = new javax.swing.ButtonGroup();
        MOSScroll = new javax.swing.JScrollPane();
        MOSPanel = new javax.swing.JPanel();
        MOSLabel33 = new javax.swing.JLabel();
        MOSLabel32 = new javax.swing.JLabel();
        MOSSSPanel = new javax.swing.JPanel();
        MOSBtn1411 = new javax.swing.JToggleButton();
        MOSBtn14 = new javax.swing.JToggleButton();
        MOSBtn151 = new javax.swing.JToggleButton();
        MOSBtn15 = new javax.swing.JToggleButton();
        MOSBtn161 = new javax.swing.JToggleButton();
        MOSBtn16 = new javax.swing.JToggleButton();
        MOSBtn17 = new javax.swing.JToggleButton();
        MOSBtn171 = new javax.swing.JToggleButton();
        MOSBtn141 = new javax.swing.JToggleButton();
        MOSBtn1511 = new javax.swing.JToggleButton();
        MOSBtn1611 = new javax.swing.JToggleButton();
        MOSBtn1711 = new javax.swing.JToggleButton();
        MOSFBtn14 = new javax.swing.JToggleButton();
        MOSFBtn15 = new javax.swing.JToggleButton();
        MOSFBtn16 = new javax.swing.JToggleButton();
        MOSFBtn17 = new javax.swing.JToggleButton();
        MOSDBtn14 = new javax.swing.JToggleButton();
        MOSDBtn15 = new javax.swing.JToggleButton();
        MOSDBtn16 = new javax.swing.JToggleButton();
        MOSDBtn17 = new javax.swing.JToggleButton();
        MOSLabel112 = new javax.swing.JLabel();
        MOSLabel11 = new javax.swing.JLabel();
        MOSLabel149 = new javax.swing.JLabel();
        MOSLabel150 = new javax.swing.JLabel();
        MOSLabel151 = new javax.swing.JLabel();
        MOSLabel152 = new javax.swing.JLabel();
        MOSLabel153 = new javax.swing.JLabel();
        MOSLabel154 = new javax.swing.JLabel();
        MOSLabel155 = new javax.swing.JLabel();
        MOSLabel114 = new javax.swing.JLabel();
        MOSLabel53 = new javax.swing.JLabel();
        MOSLabel54 = new javax.swing.JLabel();
        MOSLabel55 = new javax.swing.JLabel();
        MOSLabel56 = new javax.swing.JLabel();
        MOSLabel57 = new javax.swing.JLabel();
        MOSLabel58 = new javax.swing.JLabel();
        MOSToggleButton37 = new javax.swing.JToggleButton();
        MOSToggleButton38 = new javax.swing.JToggleButton();
        MOSToggleButton39 = new javax.swing.JToggleButton();
        MOSToggleButton40 = new javax.swing.JToggleButton();
        MOSToggleButton41 = new javax.swing.JToggleButton();
        MOSLabel156 = new javax.swing.JLabel();
        MOSBtn19 = new javax.swing.JToggleButton();
        MOSBtn172 = new javax.swing.JToggleButton();
        MOSBtn1512 = new javax.swing.JToggleButton();
        MOSToggleButton42 = new javax.swing.JToggleButton();
        MOSDBtn18 = new javax.swing.JToggleButton();
        MOSFBtn18 = new javax.swing.JToggleButton();
        MOSLabel157 = new javax.swing.JLabel();
        MOSLabel59 = new javax.swing.JLabel();
        MOSBtn18 = new javax.swing.JToggleButton();
        MOSBtn20 = new javax.swing.JToggleButton();
        MOSBtn21 = new javax.swing.JToggleButton();
        MOSBtn22 = new javax.swing.JToggleButton();
        MOSBtn23 = new javax.swing.JToggleButton();
        MOSLabel158 = new javax.swing.JLabel();
        MOSSLabel60 = new javax.swing.JLabel();
        MOSBtn24 = new javax.swing.JToggleButton();
        MOSBtn25 = new javax.swing.JToggleButton();
        MOSBtn26 = new javax.swing.JToggleButton();
        MOSBtn27 = new javax.swing.JToggleButton();
        MOSBtn28 = new javax.swing.JToggleButton();
        MOSLabel159 = new javax.swing.JLabel();
        MOSLabel60 = new javax.swing.JLabel();
        MOSBtn29 = new javax.swing.JToggleButton();
        MOSBtn30 = new javax.swing.JToggleButton();
        MOSBtn31 = new javax.swing.JToggleButton();
        MOSBtn32 = new javax.swing.JToggleButton();
        MOSBtn33 = new javax.swing.JToggleButton();
        MOSLabel160 = new javax.swing.JLabel();
        MOSLabel62 = new javax.swing.JLabel();
        MOSBtn34 = new javax.swing.JToggleButton();
        MOSBtn35 = new javax.swing.JToggleButton();
        MOSBtn36 = new javax.swing.JToggleButton();
        MOSBtn37 = new javax.swing.JToggleButton();
        MOSBtn38 = new javax.swing.JToggleButton();
        MOSLabel63 = new javax.swing.JLabel();
        MOSBtn39 = new javax.swing.JToggleButton();
        MOSBtn40 = new javax.swing.JToggleButton();
        MOSBtn41 = new javax.swing.JToggleButton();
        MOSBtn42 = new javax.swing.JToggleButton();
        MOSBtn43 = new javax.swing.JToggleButton();
        MOSLabel162 = new javax.swing.JLabel();
        MOSLabel64 = new javax.swing.JLabel();
        MOSBtn44 = new javax.swing.JToggleButton();
        MOSBtn45 = new javax.swing.JToggleButton();
        MOSBtn46 = new javax.swing.JToggleButton();
        MOSBtn47 = new javax.swing.JToggleButton();
        MOSBtn48 = new javax.swing.JToggleButton();
        MOSLabel163 = new javax.swing.JLabel();
        MOSLabel164 = new javax.swing.JLabel();
        MOSLabel66 = new javax.swing.JLabel();
        MOSBtn54 = new javax.swing.JToggleButton();
        MOSBtn55 = new javax.swing.JToggleButton();
        MOSBtn56 = new javax.swing.JToggleButton();
        MOSBtn57 = new javax.swing.JToggleButton();
        MOSBtn58 = new javax.swing.JToggleButton();
        MOSLabel165 = new javax.swing.JLabel();
        MOSLabel67 = new javax.swing.JLabel();
        MOSBtn59 = new javax.swing.JToggleButton();
        MOSBtn60 = new javax.swing.JToggleButton();
        MOSBtn61 = new javax.swing.JToggleButton();
        MOSBtn62 = new javax.swing.JToggleButton();
        MOSBtn63 = new javax.swing.JToggleButton();
        MOSLabel166 = new javax.swing.JLabel();
        MOSLabel68 = new javax.swing.JLabel();
        MOSBtn64 = new javax.swing.JToggleButton();
        MOSBtn65 = new javax.swing.JToggleButton();
        MOSBtn66 = new javax.swing.JToggleButton();
        MOSBtn67 = new javax.swing.JToggleButton();
        MOSBtn68 = new javax.swing.JToggleButton();
        MOSLabel167 = new javax.swing.JLabel();
        MOSLabel69 = new javax.swing.JLabel();
        MOSBtn69 = new javax.swing.JToggleButton();
        MOSBtn70 = new javax.swing.JToggleButton();
        MOSBtn71 = new javax.swing.JToggleButton();
        MOSBtn72 = new javax.swing.JToggleButton();
        MOSBtn73 = new javax.swing.JToggleButton();
        MOSLabel168 = new javax.swing.JLabel();
        MOSLabel70 = new javax.swing.JLabel();
        MOSBtn74 = new javax.swing.JToggleButton();
        MOSBtn75 = new javax.swing.JToggleButton();
        MOSBtn76 = new javax.swing.JToggleButton();
        MOSBtn77 = new javax.swing.JToggleButton();
        MOSBtn78 = new javax.swing.JToggleButton();
        MOSLabel169 = new javax.swing.JLabel();
        MOSLabel71 = new javax.swing.JLabel();
        MOSBtn79 = new javax.swing.JToggleButton();
        MOSBtn80 = new javax.swing.JToggleButton();
        MOSBtn81 = new javax.swing.JToggleButton();
        MOSBtn82 = new javax.swing.JToggleButton();
        MOSBtn83 = new javax.swing.JToggleButton();
        MOSLabel170 = new javax.swing.JLabel();
        MOSLabel72 = new javax.swing.JLabel();
        MOSBtn84 = new javax.swing.JToggleButton();
        MOSBtn85 = new javax.swing.JToggleButton();
        MOSBtn86 = new javax.swing.JToggleButton();
        MOSBtn87 = new javax.swing.JToggleButton();
        MOSBtn88 = new javax.swing.JToggleButton();
        MOSLabel171 = new javax.swing.JLabel();
        MOSLabel73 = new javax.swing.JLabel();
        MOSBtn89 = new javax.swing.JToggleButton();
        MOSBtn90 = new javax.swing.JToggleButton();
        MOSBtn91 = new javax.swing.JToggleButton();
        MOSBtn92 = new javax.swing.JToggleButton();
        MOSBtn93 = new javax.swing.JToggleButton();
        MOSLabel217 = new javax.swing.JLabel();
        AfectivoPositivo = new javax.swing.JLabel();
        MOSLabel218 = new javax.swing.JLabel();
        AfectivoNegativo = new javax.swing.JLabel();
        MOSLabel219 = new javax.swing.JLabel();
        PanasTotal = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        MOSLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MOSLabel33.setText("PANAS");

        MOSLabel32.setText("<html>A continuación se indican diversos sentimientos y emociones que suele experimentar la gente.<br>  Lea cada uno de ellos y, refiriéndolo a usted, conteste indicando como se ha sentido <b>habitualmente</b>.<br><br><i>Habitualmente (en general) me he sentido:</i></html> ");

        MOSSSPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PANAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        MOSSSPanel.setLayout(new java.awt.GridBagLayout());

        eptBtnGroup2.add(MOSBtn1411);
        MOSBtn1411.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn1411, gridBagConstraints);

        eptBtnGroup1.add(MOSBtn14);
        MOSBtn14.setText("1");
        MOSBtn14.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn14, gridBagConstraints);

        eptBtnGroup2.add(MOSBtn151);
        MOSBtn151.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn151, gridBagConstraints);

        eptBtnGroup1.add(MOSBtn15);
        MOSBtn15.setText("2");
        MOSBtn15.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn15, gridBagConstraints);

        eptBtnGroup2.add(MOSBtn161);
        MOSBtn161.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn161, gridBagConstraints);

        eptBtnGroup1.add(MOSBtn16);
        MOSBtn16.setText("3");
        MOSBtn16.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn16, gridBagConstraints);

        eptBtnGroup1.add(MOSBtn17);
        MOSBtn17.setText("5");
        MOSBtn17.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        MOSSSPanel.add(MOSBtn17, gridBagConstraints);

        eptBtnGroup2.add(MOSBtn171);
        MOSBtn171.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        MOSSSPanel.add(MOSBtn171, gridBagConstraints);

        eptBtnGroup3.add(MOSBtn141);
        MOSBtn141.setText("1");
        MOSBtn141.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn141, gridBagConstraints);

        eptBtnGroup3.add(MOSBtn1511);
        MOSBtn1511.setText("5");
        MOSBtn1511.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        MOSSSPanel.add(MOSBtn1511, gridBagConstraints);

        eptBtnGroup5.add(MOSBtn1611);
        MOSBtn1611.setText("2");
        MOSBtn1611.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn1611, gridBagConstraints);

        eptBtnGroup3.add(MOSBtn1711);
        MOSBtn1711.setText("3");
        MOSBtn1711.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn1711, gridBagConstraints);

        eptBtnGroup4.add(MOSFBtn14);
        MOSFBtn14.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSFBtn14, gridBagConstraints);

        eptBtnGroup4.add(MOSFBtn15);
        MOSFBtn15.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSFBtn15, gridBagConstraints);

        eptBtnGroup5.add(MOSFBtn16);
        MOSFBtn16.setText("3");
        MOSFBtn16.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSFBtn16, gridBagConstraints);

        eptBtnGroup5.add(MOSFBtn17);
        MOSFBtn17.setText("5");
        MOSFBtn17.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        MOSSSPanel.add(MOSFBtn17, gridBagConstraints);

        eptBtnGroup6.add(MOSDBtn14);
        MOSDBtn14.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 2;
        MOSSSPanel.add(MOSDBtn14, gridBagConstraints);

        eptBtnGroup6.add(MOSDBtn15);
        MOSDBtn15.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSDBtn15, gridBagConstraints);

        eptBtnGroup5.add(MOSDBtn16);
        MOSDBtn16.setText("1");
        MOSDBtn16.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSDBtn16, gridBagConstraints);

        MOSDBtn17.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSDBtn17, gridBagConstraints);

        MOSLabel112.setText("<html><center>Nada<br>(1)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 2);
        MOSSSPanel.add(MOSLabel112, gridBagConstraints);

        MOSLabel11.setText("<html><center>Algo<br>(2)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 2);
        MOSSSPanel.add(MOSLabel11, gridBagConstraints);

        MOSLabel149.setText("<html><center>Muchísimo<br>(5)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        MOSSSPanel.add(MOSLabel149, gridBagConstraints);

        MOSLabel150.setText("<html><center>Moderado<br>(3)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 2);
        MOSSSPanel.add(MOSLabel150, gridBagConstraints);

        MOSLabel151.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        MOSSSPanel.add(MOSLabel151, gridBagConstraints);

        MOSLabel152.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        MOSSSPanel.add(MOSLabel152, gridBagConstraints);

        MOSLabel153.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        MOSSSPanel.add(MOSLabel153, gridBagConstraints);

        MOSLabel154.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        MOSSSPanel.add(MOSLabel154, gridBagConstraints);

        MOSLabel155.setText("6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        MOSSSPanel.add(MOSLabel155, gridBagConstraints);

        MOSLabel114.setText("- Disgustado/a, molesto/a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        MOSSSPanel.add(MOSLabel114, gridBagConstraints);

        MOSLabel53.setText("- Interesado/a (que muestra interés)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MOSSSPanel.add(MOSLabel53, gridBagConstraints);

        MOSLabel54.setText("- Estresado/a, con malestar emocional o agobio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 8);
        MOSSSPanel.add(MOSLabel54, gridBagConstraints);

        MOSLabel55.setText("- Emocionado/a, animado/a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MOSSSPanel.add(MOSLabel55, gridBagConstraints);

        MOSLabel56.setText("- Enérgico/a, con vitalidad");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MOSSSPanel.add(MOSLabel56, gridBagConstraints);

        MOSLabel57.setText("- Culpable");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MOSSSPanel.add(MOSLabel57, gridBagConstraints);

        MOSLabel58.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        MOSSSPanel.add(MOSLabel58, gridBagConstraints);

        eptBtnGroup3.add(MOSToggleButton37);
        MOSToggleButton37.setText("2");
        MOSToggleButton37.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSToggleButton37, gridBagConstraints);

        eptBtnGroup4.add(MOSToggleButton38);
        MOSToggleButton38.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSToggleButton38, gridBagConstraints);

        eptBtnGroup4.add(MOSToggleButton39);
        MOSToggleButton39.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        MOSSSPanel.add(MOSToggleButton39, gridBagConstraints);

        eptBtnGroup6.add(MOSToggleButton40);
        MOSToggleButton40.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSToggleButton40, gridBagConstraints);

        eptBtnGroup6.add(MOSToggleButton41);
        MOSToggleButton41.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSToggleButton41, gridBagConstraints);

        MOSLabel156.setText("<html><center>Bastante<br>(4)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        MOSSSPanel.add(MOSLabel156, gridBagConstraints);

        eptBtnGroup1.add(MOSBtn19);
        MOSBtn19.setText("4");
        MOSBtn19.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn19, gridBagConstraints);

        eptBtnGroup2.add(MOSBtn172);
        MOSBtn172.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn172, gridBagConstraints);

        eptBtnGroup3.add(MOSBtn1512);
        MOSBtn1512.setText("4");
        MOSBtn1512.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn1512, gridBagConstraints);

        eptBtnGroup4.add(MOSToggleButton42);
        MOSToggleButton42.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSToggleButton42, gridBagConstraints);

        eptBtnGroup6.add(MOSDBtn18);
        MOSDBtn18.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSDBtn18, gridBagConstraints);

        eptBtnGroup5.add(MOSFBtn18);
        MOSFBtn18.setText("4");
        MOSFBtn18.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSFBtn18, gridBagConstraints);

        MOSLabel157.setText("7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        MOSSSPanel.add(MOSLabel157, gridBagConstraints);

        MOSLabel59.setText("- Asustado/a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MOSSSPanel.add(MOSLabel59, gridBagConstraints);

        eptBtnGroup7.add(MOSBtn18);
        MOSBtn18.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn18, gridBagConstraints);

        eptBtnGroup7.add(MOSBtn20);
        MOSBtn20.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn20, gridBagConstraints);

        eptBtnGroup7.add(MOSBtn21);
        MOSBtn21.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn21, gridBagConstraints);

        eptBtnGroup7.add(MOSBtn22);
        MOSBtn22.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn22, gridBagConstraints);

        eptBtnGroup7.add(MOSBtn23);
        MOSBtn23.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        MOSSSPanel.add(MOSBtn23, gridBagConstraints);

        MOSLabel158.setText("8");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        MOSSSPanel.add(MOSLabel158, gridBagConstraints);

        MOSSLabel60.setText("- Enojado/a, hostil");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MOSSSPanel.add(MOSSLabel60, gridBagConstraints);

        eptBtnGroup8.add(MOSBtn24);
        MOSBtn24.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn24, gridBagConstraints);

        eptBtnGroup8.add(MOSBtn25);
        MOSBtn25.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn25, gridBagConstraints);

        eptBtnGroup8.add(MOSBtn26);
        MOSBtn26.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn26, gridBagConstraints);

        eptBtnGroup8.add(MOSBtn27);
        MOSBtn27.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn27, gridBagConstraints);

        eptBtnGroup8.add(MOSBtn28);
        MOSBtn28.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        MOSSSPanel.add(MOSBtn28, gridBagConstraints);

        MOSLabel159.setText("9");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        MOSSSPanel.add(MOSLabel159, gridBagConstraints);

        MOSLabel60.setText("- Entusiasmado/a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MOSSSPanel.add(MOSLabel60, gridBagConstraints);

        eptBtnGroup9.add(MOSBtn29);
        MOSBtn29.setText("1");
        MOSBtn29.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn29, gridBagConstraints);

        eptBtnGroup9.add(MOSBtn30);
        MOSBtn30.setText("2");
        MOSBtn30.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn30, gridBagConstraints);

        eptBtnGroup9.add(MOSBtn31);
        MOSBtn31.setText("3");
        MOSBtn31.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn31, gridBagConstraints);

        eptBtnGroup9.add(MOSBtn32);
        MOSBtn32.setText("4");
        MOSBtn32.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn32, gridBagConstraints);

        eptBtnGroup9.add(MOSBtn33);
        MOSBtn33.setText("5");
        MOSBtn33.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        MOSSSPanel.add(MOSBtn33, gridBagConstraints);

        MOSLabel160.setText("10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        MOSSSPanel.add(MOSLabel160, gridBagConstraints);

        MOSLabel62.setText("- Orgulloso/a (de algo) satisfecho/a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MOSSSPanel.add(MOSLabel62, gridBagConstraints);

        eptBtnGroup10.add(MOSBtn34);
        MOSBtn34.setText("1");
        MOSBtn34.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn34, gridBagConstraints);

        eptBtnGroup10.add(MOSBtn35);
        MOSBtn35.setText("2");
        MOSBtn35.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn35, gridBagConstraints);

        eptBtnGroup10.add(MOSBtn36);
        MOSBtn36.setText("3");
        MOSBtn36.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn36, gridBagConstraints);

        eptBtnGroup10.add(MOSBtn37);
        MOSBtn37.setText("4");
        MOSBtn37.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn37, gridBagConstraints);

        eptBtnGroup10.add(MOSBtn38);
        MOSBtn38.setText("5");
        MOSBtn38.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        MOSSSPanel.add(MOSBtn38, gridBagConstraints);

        MOSLabel63.setText("- Alerta (despierto/a), despejado/a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MOSSSPanel.add(MOSLabel63, gridBagConstraints);

        eptBtnGroup12.add(MOSBtn39);
        MOSBtn39.setText("1");
        MOSBtn39.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn39, gridBagConstraints);

        eptBtnGroup12.add(MOSBtn40);
        MOSBtn40.setText("2");
        MOSBtn40.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn40, gridBagConstraints);

        eptBtnGroup12.add(MOSBtn41);
        MOSBtn41.setText("3");
        MOSBtn41.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn41, gridBagConstraints);

        eptBtnGroup12.add(MOSBtn42);
        MOSBtn42.setText("4");
        MOSBtn42.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn42, gridBagConstraints);

        eptBtnGroup12.add(MOSBtn43);
        MOSBtn43.setText("5");
        MOSBtn43.setName("positivo"); // NOI18N
        MOSBtn43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOSBtn43ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        MOSSSPanel.add(MOSBtn43, gridBagConstraints);

        MOSLabel162.setText("11");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        MOSSSPanel.add(MOSLabel162, gridBagConstraints);

        MOSLabel64.setText("- Irritable, malhumorado/a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MOSSSPanel.add(MOSLabel64, gridBagConstraints);

        eptBtnGroup11.add(MOSBtn44);
        MOSBtn44.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn44, gridBagConstraints);

        eptBtnGroup11.add(MOSBtn45);
        MOSBtn45.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn45, gridBagConstraints);

        eptBtnGroup11.add(MOSBtn46);
        MOSBtn46.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn46, gridBagConstraints);

        eptBtnGroup11.add(MOSBtn47);
        MOSBtn47.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn47, gridBagConstraints);

        eptBtnGroup11.add(MOSBtn48);
        MOSBtn48.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        MOSSSPanel.add(MOSBtn48, gridBagConstraints);

        MOSLabel163.setText("12");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        MOSSSPanel.add(MOSLabel163, gridBagConstraints);

        MOSLabel164.setText("13");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        MOSSSPanel.add(MOSLabel164, gridBagConstraints);

        MOSLabel66.setText("- Avergonzado/a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MOSSSPanel.add(MOSLabel66, gridBagConstraints);

        eptBtnGroup13.add(MOSBtn54);
        MOSBtn54.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn54, gridBagConstraints);

        eptBtnGroup13.add(MOSBtn55);
        MOSBtn55.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn55, gridBagConstraints);

        eptBtnGroup13.add(MOSBtn56);
        MOSBtn56.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn56, gridBagConstraints);

        eptBtnGroup13.add(MOSBtn57);
        MOSBtn57.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn57, gridBagConstraints);

        eptBtnGroup13.add(MOSBtn58);
        MOSBtn58.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        MOSSSPanel.add(MOSBtn58, gridBagConstraints);

        MOSLabel165.setText("14");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        MOSSSPanel.add(MOSLabel165, gridBagConstraints);

        MOSLabel67.setText("- Inspirado/a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MOSSSPanel.add(MOSLabel67, gridBagConstraints);

        eptBtnGroup14.add(MOSBtn59);
        MOSBtn59.setText("1");
        MOSBtn59.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn59, gridBagConstraints);

        eptBtnGroup14.add(MOSBtn60);
        MOSBtn60.setText("2");
        MOSBtn60.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn60, gridBagConstraints);

        eptBtnGroup14.add(MOSBtn61);
        MOSBtn61.setText("3");
        MOSBtn61.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn61, gridBagConstraints);

        eptBtnGroup14.add(MOSBtn62);
        MOSBtn62.setText("4");
        MOSBtn62.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn62, gridBagConstraints);

        eptBtnGroup14.add(MOSBtn63);
        MOSBtn63.setText("5");
        MOSBtn63.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        MOSSSPanel.add(MOSBtn63, gridBagConstraints);

        MOSLabel166.setText("15");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        MOSSSPanel.add(MOSLabel166, gridBagConstraints);

        MOSLabel68.setText("- Nervioso/a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MOSSSPanel.add(MOSLabel68, gridBagConstraints);

        eptBtnGroup15.add(MOSBtn64);
        MOSBtn64.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn64, gridBagConstraints);

        eptBtnGroup15.add(MOSBtn65);
        MOSBtn65.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn65, gridBagConstraints);

        eptBtnGroup15.add(MOSBtn66);
        MOSBtn66.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn66, gridBagConstraints);

        eptBtnGroup15.add(MOSBtn67);
        MOSBtn67.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn67, gridBagConstraints);

        eptBtnGroup15.add(MOSBtn68);
        MOSBtn68.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        MOSSSPanel.add(MOSBtn68, gridBagConstraints);

        MOSLabel167.setText("16");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        MOSSSPanel.add(MOSLabel167, gridBagConstraints);

        MOSLabel69.setText("- Decidido/a, atrevido/a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MOSSSPanel.add(MOSLabel69, gridBagConstraints);

        eptBtnGroup16.add(MOSBtn69);
        MOSBtn69.setText("1");
        MOSBtn69.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn69, gridBagConstraints);

        eptBtnGroup16.add(MOSBtn70);
        MOSBtn70.setText("2");
        MOSBtn70.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn70, gridBagConstraints);

        eptBtnGroup16.add(MOSBtn71);
        MOSBtn71.setText("3");
        MOSBtn71.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn71, gridBagConstraints);

        eptBtnGroup16.add(MOSBtn72);
        MOSBtn72.setText("4");
        MOSBtn72.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn72, gridBagConstraints);

        eptBtnGroup16.add(MOSBtn73);
        MOSBtn73.setText("5");
        MOSBtn73.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        MOSSSPanel.add(MOSBtn73, gridBagConstraints);

        MOSLabel168.setText("17");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 19;
        MOSSSPanel.add(MOSLabel168, gridBagConstraints);

        MOSLabel70.setText("- Atento/a o consciente (pongo atención)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MOSSSPanel.add(MOSLabel70, gridBagConstraints);

        eptBtnGroup17.add(MOSBtn74);
        MOSBtn74.setText("1");
        MOSBtn74.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn74, gridBagConstraints);

        eptBtnGroup17.add(MOSBtn75);
        MOSBtn75.setText("2");
        MOSBtn75.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn75, gridBagConstraints);

        eptBtnGroup17.add(MOSBtn76);
        MOSBtn76.setText("3");
        MOSBtn76.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn76, gridBagConstraints);

        eptBtnGroup17.add(MOSBtn77);
        MOSBtn77.setText("4");
        MOSBtn77.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn77, gridBagConstraints);

        eptBtnGroup17.add(MOSBtn78);
        MOSBtn78.setText("5");
        MOSBtn78.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        MOSSSPanel.add(MOSBtn78, gridBagConstraints);

        MOSLabel169.setText("18");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        MOSSSPanel.add(MOSLabel169, gridBagConstraints);

        MOSLabel71.setText("- Intranquilo/a o inquieto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MOSSSPanel.add(MOSLabel71, gridBagConstraints);

        eptBtnGroup18.add(MOSBtn79);
        MOSBtn79.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn79, gridBagConstraints);

        eptBtnGroup18.add(MOSBtn80);
        MOSBtn80.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn80, gridBagConstraints);

        eptBtnGroup18.add(MOSBtn81);
        MOSBtn81.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn81, gridBagConstraints);

        eptBtnGroup18.add(MOSBtn82);
        MOSBtn82.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn82, gridBagConstraints);

        eptBtnGroup18.add(MOSBtn83);
        MOSBtn83.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        MOSSSPanel.add(MOSBtn83, gridBagConstraints);

        MOSLabel170.setText("19");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 21;
        MOSSSPanel.add(MOSLabel170, gridBagConstraints);

        MOSLabel72.setText("- Activo/a");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MOSSSPanel.add(MOSLabel72, gridBagConstraints);

        eptBtnGroup19.add(MOSBtn84);
        MOSBtn84.setText("1");
        MOSBtn84.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn84, gridBagConstraints);

        eptBtnGroup19.add(MOSBtn85);
        MOSBtn85.setText("2");
        MOSBtn85.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn85, gridBagConstraints);

        eptBtnGroup19.add(MOSBtn86);
        MOSBtn86.setText("3");
        MOSBtn86.setName("positivo"); // NOI18N
        MOSBtn86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOSBtn86ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn86, gridBagConstraints);

        eptBtnGroup19.add(MOSBtn87);
        MOSBtn87.setText("4");
        MOSBtn87.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn87, gridBagConstraints);

        eptBtnGroup19.add(MOSBtn88);
        MOSBtn88.setText("5");
        MOSBtn88.setName("positivo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        MOSSSPanel.add(MOSBtn88, gridBagConstraints);

        MOSLabel171.setText("20");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        MOSSSPanel.add(MOSLabel171, gridBagConstraints);

        MOSLabel73.setText("- Temeroso/a, con miedo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        MOSSSPanel.add(MOSLabel73, gridBagConstraints);

        eptBtnGroup20.add(MOSBtn89);
        MOSBtn89.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn89, gridBagConstraints);

        eptBtnGroup20.add(MOSBtn90);
        MOSBtn90.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn90, gridBagConstraints);

        eptBtnGroup20.add(MOSBtn91);
        MOSBtn91.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn91, gridBagConstraints);

        eptBtnGroup20.add(MOSBtn92);
        MOSBtn92.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        MOSSSPanel.add(MOSBtn92, gridBagConstraints);

        eptBtnGroup20.add(MOSBtn93);
        MOSBtn93.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        MOSSSPanel.add(MOSBtn93, gridBagConstraints);

        MOSLabel217.setText("Afectivo Positivo:");

        AfectivoPositivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AfectivoPositivo.setText("0");

        MOSLabel218.setText("Afectivo Negativo:");

        AfectivoNegativo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AfectivoNegativo.setText("0");

        MOSLabel219.setText("Total:");

        PanasTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PanasTotal.setText("0");

        javax.swing.GroupLayout MOSPanelLayout = new javax.swing.GroupLayout(MOSPanel);
        MOSPanel.setLayout(MOSPanelLayout);
        MOSPanelLayout.setHorizontalGroup(
            MOSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MOSPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MOSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MOSLabel33)
                    .addGroup(MOSPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(MOSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MOSLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MOSPanelLayout.createSequentialGroup()
                                .addComponent(MOSSSPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MOSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MOSPanelLayout.createSequentialGroup()
                                        .addComponent(MOSLabel217)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AfectivoPositivo))
                                    .addGroup(MOSPanelLayout.createSequentialGroup()
                                        .addComponent(MOSLabel218)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AfectivoNegativo))
                                    .addGroup(MOSPanelLayout.createSequentialGroup()
                                        .addComponent(MOSLabel219)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PanasTotal)))))))
                .addGap(91, 91, 91))
        );
        MOSPanelLayout.setVerticalGroup(
            MOSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MOSPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MOSLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MOSLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MOSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MOSSSPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MOSPanelLayout.createSequentialGroup()
                        .addGroup(MOSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MOSLabel217)
                            .addComponent(AfectivoPositivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MOSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MOSLabel218)
                            .addComponent(AfectivoNegativo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MOSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MOSLabel219)
                            .addComponent(PanasTotal))))
                .addContainerGap())
        );

        MOSScroll.setViewportView(MOSPanel);

        add(MOSScroll, "card1");
    }// </editor-fold>//GEN-END:initComponents

    private void MOSBtn43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOSBtn43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MOSBtn43ActionPerformed

    private void MOSBtn86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOSBtn86ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MOSBtn86ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AfectivoNegativo;
    private javax.swing.JLabel AfectivoPositivo;
    private javax.swing.JToggleButton MOSBtn14;
    private javax.swing.JToggleButton MOSBtn141;
    private javax.swing.JToggleButton MOSBtn1411;
    private javax.swing.JToggleButton MOSBtn15;
    private javax.swing.JToggleButton MOSBtn151;
    private javax.swing.JToggleButton MOSBtn1511;
    private javax.swing.JToggleButton MOSBtn1512;
    private javax.swing.JToggleButton MOSBtn16;
    private javax.swing.JToggleButton MOSBtn161;
    private javax.swing.JToggleButton MOSBtn1611;
    private javax.swing.JToggleButton MOSBtn17;
    private javax.swing.JToggleButton MOSBtn171;
    private javax.swing.JToggleButton MOSBtn1711;
    private javax.swing.JToggleButton MOSBtn172;
    private javax.swing.JToggleButton MOSBtn18;
    private javax.swing.JToggleButton MOSBtn19;
    private javax.swing.JToggleButton MOSBtn20;
    private javax.swing.JToggleButton MOSBtn21;
    private javax.swing.JToggleButton MOSBtn22;
    private javax.swing.JToggleButton MOSBtn23;
    private javax.swing.JToggleButton MOSBtn24;
    private javax.swing.JToggleButton MOSBtn25;
    private javax.swing.JToggleButton MOSBtn26;
    private javax.swing.JToggleButton MOSBtn27;
    private javax.swing.JToggleButton MOSBtn28;
    private javax.swing.JToggleButton MOSBtn29;
    private javax.swing.JToggleButton MOSBtn30;
    private javax.swing.JToggleButton MOSBtn31;
    private javax.swing.JToggleButton MOSBtn32;
    private javax.swing.JToggleButton MOSBtn33;
    private javax.swing.JToggleButton MOSBtn34;
    private javax.swing.JToggleButton MOSBtn35;
    private javax.swing.JToggleButton MOSBtn36;
    private javax.swing.JToggleButton MOSBtn37;
    private javax.swing.JToggleButton MOSBtn38;
    private javax.swing.JToggleButton MOSBtn39;
    private javax.swing.JToggleButton MOSBtn40;
    private javax.swing.JToggleButton MOSBtn41;
    private javax.swing.JToggleButton MOSBtn42;
    private javax.swing.JToggleButton MOSBtn43;
    private javax.swing.JToggleButton MOSBtn44;
    private javax.swing.JToggleButton MOSBtn45;
    private javax.swing.JToggleButton MOSBtn46;
    private javax.swing.JToggleButton MOSBtn47;
    private javax.swing.JToggleButton MOSBtn48;
    private javax.swing.JToggleButton MOSBtn54;
    private javax.swing.JToggleButton MOSBtn55;
    private javax.swing.JToggleButton MOSBtn56;
    private javax.swing.JToggleButton MOSBtn57;
    private javax.swing.JToggleButton MOSBtn58;
    private javax.swing.JToggleButton MOSBtn59;
    private javax.swing.JToggleButton MOSBtn60;
    private javax.swing.JToggleButton MOSBtn61;
    private javax.swing.JToggleButton MOSBtn62;
    private javax.swing.JToggleButton MOSBtn63;
    private javax.swing.JToggleButton MOSBtn64;
    private javax.swing.JToggleButton MOSBtn65;
    private javax.swing.JToggleButton MOSBtn66;
    private javax.swing.JToggleButton MOSBtn67;
    private javax.swing.JToggleButton MOSBtn68;
    private javax.swing.JToggleButton MOSBtn69;
    private javax.swing.JToggleButton MOSBtn70;
    private javax.swing.JToggleButton MOSBtn71;
    private javax.swing.JToggleButton MOSBtn72;
    private javax.swing.JToggleButton MOSBtn73;
    private javax.swing.JToggleButton MOSBtn74;
    private javax.swing.JToggleButton MOSBtn75;
    private javax.swing.JToggleButton MOSBtn76;
    private javax.swing.JToggleButton MOSBtn77;
    private javax.swing.JToggleButton MOSBtn78;
    private javax.swing.JToggleButton MOSBtn79;
    private javax.swing.JToggleButton MOSBtn80;
    private javax.swing.JToggleButton MOSBtn81;
    private javax.swing.JToggleButton MOSBtn82;
    private javax.swing.JToggleButton MOSBtn83;
    private javax.swing.JToggleButton MOSBtn84;
    private javax.swing.JToggleButton MOSBtn85;
    private javax.swing.JToggleButton MOSBtn86;
    private javax.swing.JToggleButton MOSBtn87;
    private javax.swing.JToggleButton MOSBtn88;
    private javax.swing.JToggleButton MOSBtn89;
    private javax.swing.JToggleButton MOSBtn90;
    private javax.swing.JToggleButton MOSBtn91;
    private javax.swing.JToggleButton MOSBtn92;
    private javax.swing.JToggleButton MOSBtn93;
    private javax.swing.JToggleButton MOSDBtn14;
    private javax.swing.JToggleButton MOSDBtn15;
    private javax.swing.JToggleButton MOSDBtn16;
    private javax.swing.JToggleButton MOSDBtn17;
    private javax.swing.JToggleButton MOSDBtn18;
    private javax.swing.JToggleButton MOSFBtn14;
    private javax.swing.JToggleButton MOSFBtn15;
    private javax.swing.JToggleButton MOSFBtn16;
    private javax.swing.JToggleButton MOSFBtn17;
    private javax.swing.JToggleButton MOSFBtn18;
    private javax.swing.JLabel MOSLabel11;
    private javax.swing.JLabel MOSLabel112;
    private javax.swing.JLabel MOSLabel114;
    private javax.swing.JLabel MOSLabel149;
    private javax.swing.JLabel MOSLabel150;
    private javax.swing.JLabel MOSLabel151;
    private javax.swing.JLabel MOSLabel152;
    private javax.swing.JLabel MOSLabel153;
    private javax.swing.JLabel MOSLabel154;
    private javax.swing.JLabel MOSLabel155;
    private javax.swing.JLabel MOSLabel156;
    private javax.swing.JLabel MOSLabel157;
    private javax.swing.JLabel MOSLabel158;
    private javax.swing.JLabel MOSLabel159;
    private javax.swing.JLabel MOSLabel160;
    private javax.swing.JLabel MOSLabel162;
    private javax.swing.JLabel MOSLabel163;
    private javax.swing.JLabel MOSLabel164;
    private javax.swing.JLabel MOSLabel165;
    private javax.swing.JLabel MOSLabel166;
    private javax.swing.JLabel MOSLabel167;
    private javax.swing.JLabel MOSLabel168;
    private javax.swing.JLabel MOSLabel169;
    private javax.swing.JLabel MOSLabel170;
    private javax.swing.JLabel MOSLabel171;
    private javax.swing.JLabel MOSLabel217;
    private javax.swing.JLabel MOSLabel218;
    private javax.swing.JLabel MOSLabel219;
    private javax.swing.JLabel MOSLabel32;
    private javax.swing.JLabel MOSLabel33;
    private javax.swing.JLabel MOSLabel53;
    private javax.swing.JLabel MOSLabel54;
    private javax.swing.JLabel MOSLabel55;
    private javax.swing.JLabel MOSLabel56;
    private javax.swing.JLabel MOSLabel57;
    private javax.swing.JLabel MOSLabel58;
    private javax.swing.JLabel MOSLabel59;
    private javax.swing.JLabel MOSLabel60;
    private javax.swing.JLabel MOSLabel62;
    private javax.swing.JLabel MOSLabel63;
    private javax.swing.JLabel MOSLabel64;
    private javax.swing.JLabel MOSLabel66;
    private javax.swing.JLabel MOSLabel67;
    private javax.swing.JLabel MOSLabel68;
    private javax.swing.JLabel MOSLabel69;
    private javax.swing.JLabel MOSLabel70;
    private javax.swing.JLabel MOSLabel71;
    private javax.swing.JLabel MOSLabel72;
    private javax.swing.JLabel MOSLabel73;
    private javax.swing.JPanel MOSPanel;
    private javax.swing.JLabel MOSSLabel60;
    private javax.swing.JPanel MOSSSPanel;
    private javax.swing.JScrollPane MOSScroll;
    private javax.swing.JToggleButton MOSToggleButton37;
    private javax.swing.JToggleButton MOSToggleButton38;
    private javax.swing.JToggleButton MOSToggleButton39;
    private javax.swing.JToggleButton MOSToggleButton40;
    private javax.swing.JToggleButton MOSToggleButton41;
    private javax.swing.JToggleButton MOSToggleButton42;
    private javax.swing.JLabel PanasTotal;
    private javax.swing.ButtonGroup eptBtnGroup1;
    private javax.swing.ButtonGroup eptBtnGroup10;
    private javax.swing.ButtonGroup eptBtnGroup11;
    private javax.swing.ButtonGroup eptBtnGroup12;
    private javax.swing.ButtonGroup eptBtnGroup13;
    private javax.swing.ButtonGroup eptBtnGroup14;
    private javax.swing.ButtonGroup eptBtnGroup15;
    private javax.swing.ButtonGroup eptBtnGroup16;
    private javax.swing.ButtonGroup eptBtnGroup17;
    private javax.swing.ButtonGroup eptBtnGroup18;
    private javax.swing.ButtonGroup eptBtnGroup19;
    private javax.swing.ButtonGroup eptBtnGroup2;
    private javax.swing.ButtonGroup eptBtnGroup20;
    private javax.swing.ButtonGroup eptBtnGroup3;
    private javax.swing.ButtonGroup eptBtnGroup4;
    private javax.swing.ButtonGroup eptBtnGroup5;
    private javax.swing.ButtonGroup eptBtnGroup6;
    private javax.swing.ButtonGroup eptBtnGroup7;
    private javax.swing.ButtonGroup eptBtnGroup8;
    private javax.swing.ButtonGroup eptBtnGroup9;
    // End of variables declaration//GEN-END:variables
}
