/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.tests;

import controlador.Utils;
import model.Pacient;

import java.util.Properties;

/**
 *
 * @author a630703
 */
public class RSE extends Test {

    /**
     * Creates new form Test
     *
     * @param pacientActual
     */
    public RSE(Pacient pacientActual) {
        super(pacientActual);
        initComponents();

        label = "RSE";
        numPaginesTotal = this.getComponentCount();
        
        Utils.initTaula(rseQPanel,rseTotal);
    }

    @Override
    public void guardarResultats(Properties prop) {
        // RSE
        Utils.setProperty(prop,"rseTotal",rseTotal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        rseButtonGroup1 = new javax.swing.ButtonGroup();
        rseButtonGroup2 = new javax.swing.ButtonGroup();
        rseButtonGroup3 = new javax.swing.ButtonGroup();
        rseButtonGroup4 = new javax.swing.ButtonGroup();
        rseButtonGroup5 = new javax.swing.ButtonGroup();
        rseButtonGroup6 = new javax.swing.ButtonGroup();
        rseButtonGroup7 = new javax.swing.ButtonGroup();
        rseButtonGroup8 = new javax.swing.ButtonGroup();
        rseButtonGroup9 = new javax.swing.ButtonGroup();
        rseButtonGroup10 = new javax.swing.ButtonGroup();
        rseScroll = new javax.swing.JScrollPane();
        rsePanel = new javax.swing.JPanel();
        rseQPanel = new javax.swing.JPanel();
        orientacioBtn2 = new javax.swing.JToggleButton();
        memoBtn2 = new javax.swing.JToggleButton();
        orientacioBtn3 = new javax.swing.JToggleButton();
        memoBtn3 = new javax.swing.JToggleButton();
        orientacioBtn4 = new javax.swing.JToggleButton();
        memoBtn4 = new javax.swing.JToggleButton();
        memoBtn5 = new javax.swing.JToggleButton();
        orientacioBtn5 = new javax.swing.JToggleButton();
        raoBtn2 = new javax.swing.JToggleButton();
        raoBtn5 = new javax.swing.JToggleButton();
        raoBtn3 = new javax.swing.JToggleButton();
        raoBtn4 = new javax.swing.JToggleButton();
        activitatsFBtn2 = new javax.swing.JToggleButton();
        activitatsFBtn3 = new javax.swing.JToggleButton();
        activitatsFBtn4 = new javax.swing.JToggleButton();
        activitatsFBtn5 = new javax.swing.JToggleButton();
        activitatsDBtn5 = new javax.swing.JToggleButton();
        activitatsDBtn4 = new javax.swing.JToggleButton();
        activitatsDBtn2 = new javax.swing.JToggleButton();
        activitatsDBtn3 = new javax.swing.JToggleButton();
        cuidatBtn2 = new javax.swing.JToggleButton();
        cuidatBtn3 = new javax.swing.JToggleButton();
        cuidatBtn4 = new javax.swing.JToggleButton();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        orientacioBtn6 = new javax.swing.JToggleButton();
        raoBtn6 = new javax.swing.JToggleButton();
        raoBtn7 = new javax.swing.JToggleButton();
        activitatsDBtn6 = new javax.swing.JToggleButton();
        raoBtn8 = new javax.swing.JToggleButton();
        activitatsDBtn7 = new javax.swing.JToggleButton();
        activitatsDBtn8 = new javax.swing.JToggleButton();
        cuidatBtn5 = new javax.swing.JToggleButton();
        cuidatBtn6 = new javax.swing.JToggleButton();
        cuidatBtn7 = new javax.swing.JToggleButton();
        activitatsDBtn9 = new javax.swing.JToggleButton();
        cuidatBtn14 = new javax.swing.JToggleButton();
        cuidatBtn16 = new javax.swing.JToggleButton();
        cuidatBtn19 = new javax.swing.JToggleButton();
        activitatsDBtn18 = new javax.swing.JToggleButton();
        cuidatBtn20 = new javax.swing.JToggleButton();
        cuidatBtn21 = new javax.swing.JToggleButton();
        cuidatBtn22 = new javax.swing.JToggleButton();
        jLabel220 = new javax.swing.JLabel();
        rseTotal = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        rseQPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Escala d'autoestima de Rosemberg", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        rseQPanel.setLayout(new java.awt.GridBagLayout());

        rseButtonGroup2.add(orientacioBtn2);
        orientacioBtn2.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(orientacioBtn2, gridBagConstraints);

        rseButtonGroup1.add(memoBtn2);
        memoBtn2.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(memoBtn2, gridBagConstraints);

        rseButtonGroup3.add(orientacioBtn3);
        orientacioBtn3.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(orientacioBtn3, gridBagConstraints);

        rseButtonGroup1.add(memoBtn3);
        memoBtn3.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(memoBtn3, gridBagConstraints);

        rseButtonGroup2.add(orientacioBtn4);
        orientacioBtn4.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(orientacioBtn4, gridBagConstraints);

        rseButtonGroup1.add(memoBtn4);
        memoBtn4.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(memoBtn4, gridBagConstraints);

        rseButtonGroup1.add(memoBtn5);
        memoBtn5.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(memoBtn5, gridBagConstraints);

        rseButtonGroup2.add(orientacioBtn5);
        orientacioBtn5.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(orientacioBtn5, gridBagConstraints);

        rseButtonGroup3.add(raoBtn2);
        raoBtn2.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(raoBtn2, gridBagConstraints);

        rseButtonGroup4.add(raoBtn5);
        raoBtn5.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(raoBtn5, gridBagConstraints);

        rseButtonGroup6.add(raoBtn3);
        raoBtn3.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(raoBtn3, gridBagConstraints);

        rseButtonGroup4.add(raoBtn4);
        raoBtn4.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(raoBtn4, gridBagConstraints);

        rseButtonGroup4.add(activitatsFBtn2);
        activitatsFBtn2.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(activitatsFBtn2, gridBagConstraints);

        rseButtonGroup4.add(activitatsFBtn3);
        activitatsFBtn3.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(activitatsFBtn3, gridBagConstraints);

        rseButtonGroup5.add(activitatsFBtn4);
        activitatsFBtn4.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(activitatsFBtn4, gridBagConstraints);

        rseButtonGroup5.add(activitatsFBtn5);
        activitatsFBtn5.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(activitatsFBtn5, gridBagConstraints);

        rseButtonGroup6.add(activitatsDBtn5);
        activitatsDBtn5.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(activitatsDBtn5, gridBagConstraints);

        rseButtonGroup6.add(activitatsDBtn4);
        activitatsDBtn4.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(activitatsDBtn4, gridBagConstraints);

        rseButtonGroup9.add(activitatsDBtn2);
        activitatsDBtn2.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(activitatsDBtn2, gridBagConstraints);

        activitatsDBtn3.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(activitatsDBtn3, gridBagConstraints);

        rseButtonGroup9.add(cuidatBtn2);
        cuidatBtn2.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(cuidatBtn2, gridBagConstraints);

        rseButtonGroup9.add(cuidatBtn3);
        cuidatBtn3.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(cuidatBtn3, gridBagConstraints);

        rseButtonGroup9.add(cuidatBtn4);
        cuidatBtn4.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(cuidatBtn4, gridBagConstraints);

        jLabel99.setText("<html><center>Molt en<br>desacord");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 2);
        rseQPanel.add(jLabel99, gridBagConstraints);

        jLabel100.setText("<html><center>En<br>desacord");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 2);
        rseQPanel.add(jLabel100, gridBagConstraints);

        jLabel125.setText("<html><center>Molt<br>d'acord");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        rseQPanel.add(jLabel125, gridBagConstraints);

        jLabel126.setText("<html><center>D'acord<br>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 2, 2);
        rseQPanel.add(jLabel126, gridBagConstraints);

        jLabel127.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        rseQPanel.add(jLabel127, gridBagConstraints);

        jLabel128.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        rseQPanel.add(jLabel128, gridBagConstraints);

        jLabel129.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        rseQPanel.add(jLabel129, gridBagConstraints);

        jLabel130.setText("5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        rseQPanel.add(jLabel130, gridBagConstraints);

        jLabel131.setText("6");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        rseQPanel.add(jLabel131, gridBagConstraints);

        jLabel132.setText("7");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        rseQPanel.add(jLabel132, gridBagConstraints);

        jLabel101.setText("Sóc capaç de fer les coses tan bé com els demés");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        rseQPanel.add(jLabel101, gridBagConstraints);

        jLabel1.setText("Em sento una persona tan valiosa com les altres");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        rseQPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Generalment m'inclino a pensar que soc un fracàs");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 8);
        rseQPanel.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Crec que tinc algunes qualitats bones");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        rseQPanel.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Crec que tinc molt del que estar orgullós");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        rseQPanel.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Tinc una actitud positiva cap a mi mateix");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        rseQPanel.add(jLabel5, gridBagConstraints);

        jLabel6.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        rseQPanel.add(jLabel6, gridBagConstraints);

        jLabel7.setText("8");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        rseQPanel.add(jLabel7, gridBagConstraints);

        jLabel8.setText("9");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        rseQPanel.add(jLabel8, gridBagConstraints);

        jLabel9.setText("10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 5);
        rseQPanel.add(jLabel9, gridBagConstraints);

        jLabel10.setText("En general em sento satisfet amb mi mateix");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        rseQPanel.add(jLabel10, gridBagConstraints);

        jLabel11.setText("M'agradaria tenir més respecte per mi mateix");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        rseQPanel.add(jLabel11, gridBagConstraints);

        jLabel12.setText("Realment em sento inútil en algunes ocasions");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        rseQPanel.add(jLabel12, gridBagConstraints);

        jLabel13.setText("De vegades penso que no serveixo per res");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        rseQPanel.add(jLabel13, gridBagConstraints);

        rseButtonGroup2.add(orientacioBtn6);
        orientacioBtn6.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(orientacioBtn6, gridBagConstraints);

        rseButtonGroup3.add(raoBtn6);
        raoBtn6.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(raoBtn6, gridBagConstraints);

        rseButtonGroup3.add(raoBtn7);
        raoBtn7.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(raoBtn7, gridBagConstraints);

        rseButtonGroup5.add(activitatsDBtn6);
        activitatsDBtn6.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(activitatsDBtn6, gridBagConstraints);

        rseButtonGroup5.add(raoBtn8);
        raoBtn8.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(raoBtn8, gridBagConstraints);

        rseButtonGroup6.add(activitatsDBtn7);
        activitatsDBtn7.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(activitatsDBtn7, gridBagConstraints);

        rseButtonGroup7.add(activitatsDBtn8);
        activitatsDBtn8.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(activitatsDBtn8, gridBagConstraints);

        rseButtonGroup7.add(cuidatBtn5);
        cuidatBtn5.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(cuidatBtn5, gridBagConstraints);

        rseButtonGroup7.add(cuidatBtn6);
        cuidatBtn6.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(cuidatBtn6, gridBagConstraints);

        rseButtonGroup7.add(cuidatBtn7);
        cuidatBtn7.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(cuidatBtn7, gridBagConstraints);

        rseButtonGroup10.add(activitatsDBtn9);
        activitatsDBtn9.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(activitatsDBtn9, gridBagConstraints);

        rseButtonGroup10.add(cuidatBtn14);
        cuidatBtn14.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(cuidatBtn14, gridBagConstraints);

        rseButtonGroup10.add(cuidatBtn16);
        cuidatBtn16.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(cuidatBtn16, gridBagConstraints);

        rseButtonGroup10.add(cuidatBtn19);
        cuidatBtn19.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(cuidatBtn19, gridBagConstraints);

        rseButtonGroup8.add(activitatsDBtn18);
        activitatsDBtn18.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(activitatsDBtn18, gridBagConstraints);

        rseButtonGroup8.add(cuidatBtn20);
        cuidatBtn20.setText("2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(cuidatBtn20, gridBagConstraints);

        rseButtonGroup8.add(cuidatBtn21);
        cuidatBtn21.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(cuidatBtn21, gridBagConstraints);

        rseButtonGroup8.add(cuidatBtn22);
        cuidatBtn22.setText("4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        rseQPanel.add(cuidatBtn22, gridBagConstraints);

        jLabel220.setText("Puntuació total:");

        rseTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rseTotal.setText("0");

        javax.swing.GroupLayout rsePanelLayout = new javax.swing.GroupLayout(rsePanel);
        rsePanel.setLayout(rsePanelLayout);
        rsePanelLayout.setHorizontalGroup(
            rsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rsePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(rsePanelLayout.createSequentialGroup()
                        .addComponent(jLabel220)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rseTotal)
                        .addGap(81, 81, 81))
                    .addComponent(rseQPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        rsePanelLayout.setVerticalGroup(
            rsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rsePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rseQPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel220)
                    .addComponent(rseTotal))
                .addContainerGap())
        );

        rseScroll.setViewportView(rsePanel);

        add(rseScroll, "card1");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton activitatsDBtn18;
    private javax.swing.JToggleButton activitatsDBtn2;
    private javax.swing.JToggleButton activitatsDBtn3;
    private javax.swing.JToggleButton activitatsDBtn4;
    private javax.swing.JToggleButton activitatsDBtn5;
    private javax.swing.JToggleButton activitatsDBtn6;
    private javax.swing.JToggleButton activitatsDBtn7;
    private javax.swing.JToggleButton activitatsDBtn8;
    private javax.swing.JToggleButton activitatsDBtn9;
    private javax.swing.JToggleButton activitatsFBtn2;
    private javax.swing.JToggleButton activitatsFBtn3;
    private javax.swing.JToggleButton activitatsFBtn4;
    private javax.swing.JToggleButton activitatsFBtn5;
    private javax.swing.JToggleButton cuidatBtn14;
    private javax.swing.JToggleButton cuidatBtn16;
    private javax.swing.JToggleButton cuidatBtn19;
    private javax.swing.JToggleButton cuidatBtn2;
    private javax.swing.JToggleButton cuidatBtn20;
    private javax.swing.JToggleButton cuidatBtn21;
    private javax.swing.JToggleButton cuidatBtn22;
    private javax.swing.JToggleButton cuidatBtn3;
    private javax.swing.JToggleButton cuidatBtn4;
    private javax.swing.JToggleButton cuidatBtn5;
    private javax.swing.JToggleButton cuidatBtn6;
    private javax.swing.JToggleButton cuidatBtn7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel220;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JToggleButton memoBtn2;
    private javax.swing.JToggleButton memoBtn3;
    private javax.swing.JToggleButton memoBtn4;
    private javax.swing.JToggleButton memoBtn5;
    private javax.swing.JToggleButton orientacioBtn2;
    private javax.swing.JToggleButton orientacioBtn3;
    private javax.swing.JToggleButton orientacioBtn4;
    private javax.swing.JToggleButton orientacioBtn5;
    private javax.swing.JToggleButton orientacioBtn6;
    private javax.swing.JToggleButton raoBtn2;
    private javax.swing.JToggleButton raoBtn3;
    private javax.swing.JToggleButton raoBtn4;
    private javax.swing.JToggleButton raoBtn5;
    private javax.swing.JToggleButton raoBtn6;
    private javax.swing.JToggleButton raoBtn7;
    private javax.swing.JToggleButton raoBtn8;
    private javax.swing.ButtonGroup rseButtonGroup1;
    private javax.swing.ButtonGroup rseButtonGroup10;
    private javax.swing.ButtonGroup rseButtonGroup2;
    private javax.swing.ButtonGroup rseButtonGroup3;
    private javax.swing.ButtonGroup rseButtonGroup4;
    private javax.swing.ButtonGroup rseButtonGroup5;
    private javax.swing.ButtonGroup rseButtonGroup6;
    private javax.swing.ButtonGroup rseButtonGroup7;
    private javax.swing.ButtonGroup rseButtonGroup8;
    private javax.swing.ButtonGroup rseButtonGroup9;
    private javax.swing.JPanel rsePanel;
    private javax.swing.JPanel rseQPanel;
    private javax.swing.JScrollPane rseScroll;
    private javax.swing.JLabel rseTotal;
    // End of variables declaration//GEN-END:variables
}
