/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.tests;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Properties;
import javax.swing.JRadioButton;

import controlador.Utils;
import model.Pacient;

/**
 *
 * @author a630703
 */
public class SF12 extends Test {

    /**
     * Creates new form Test
     *
     * @param pacientActual
     */
    public SF12(Pacient pacientActual) {
        super(pacientActual);
        initComponents();

        label = "SF-12";
        numPaginesTotal = this.getComponentCount();
        
        initSF12();
    }

    @Override
    public void guardarResultats(Properties prop) {
        // SF12
        Utils.setProperty(prop,"sf12Total",sf12Total);
    }

    private void initSF12() {
        for (Component com : sf12Panel.getComponents()){
            if (com instanceof JRadioButton){
                ((JRadioButton)com).addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        actualitzaPuntuacioSf12();
                    }
                });
            }
        }
    }

    private void actualitzaPuntuacioSf12() {
        int count = 0;
        for (Component com : sf12Panel.getComponents()){
            if (com instanceof JRadioButton){
                if (((JRadioButton)com).isSelected()){
                    count += Integer.parseInt(((JRadioButton)com).getActionCommand());
                }
            }
        }
        sf12Total.setText(count+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sf12BtnGroup1 = new javax.swing.ButtonGroup();
        sf12BtnGroup2 = new javax.swing.ButtonGroup();
        sf12BtnGroup3 = new javax.swing.ButtonGroup();
        sf12BtnGroup4 = new javax.swing.ButtonGroup();
        sf12BtnGroup5 = new javax.swing.ButtonGroup();
        sf12BtnGroup6 = new javax.swing.ButtonGroup();
        sf12BtnGroup7 = new javax.swing.ButtonGroup();
        sf12BtnGroup8 = new javax.swing.ButtonGroup();
        sf12BtnGroup9 = new javax.swing.ButtonGroup();
        sf12BtnGroup10 = new javax.swing.ButtonGroup();
        sf12BtnGroup11 = new javax.swing.ButtonGroup();
        sf12BtnGroup12 = new javax.swing.ButtonGroup();
        sf12Scroll = new javax.swing.JScrollPane();
        sf12Panel = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        jLabel146 = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();
        jLabel148 = new javax.swing.JLabel();
        jLabel175 = new javax.swing.JLabel();
        jLabel176 = new javax.swing.JLabel();
        sf12Total = new javax.swing.JLabel();
        jRadioButton53 = new javax.swing.JRadioButton();
        jRadioButton54 = new javax.swing.JRadioButton();
        jRadioButton55 = new javax.swing.JRadioButton();
        jRadioButton56 = new javax.swing.JRadioButton();
        jRadioButton57 = new javax.swing.JRadioButton();
        jRadioButton58 = new javax.swing.JRadioButton();
        jRadioButton59 = new javax.swing.JRadioButton();
        jRadioButton60 = new javax.swing.JRadioButton();
        jRadioButton65 = new javax.swing.JRadioButton();
        jRadioButton66 = new javax.swing.JRadioButton();
        jRadioButton67 = new javax.swing.JRadioButton();
        jRadioButton68 = new javax.swing.JRadioButton();
        jRadioButton69 = new javax.swing.JRadioButton();
        jRadioButton70 = new javax.swing.JRadioButton();
        jRadioButton71 = new javax.swing.JRadioButton();
        jRadioButton72 = new javax.swing.JRadioButton();
        jRadioButton73 = new javax.swing.JRadioButton();
        jRadioButton74 = new javax.swing.JRadioButton();
        jRadioButton75 = new javax.swing.JRadioButton();
        jRadioButton76 = new javax.swing.JRadioButton();
        jRadioButton77 = new javax.swing.JRadioButton();
        jRadioButton78 = new javax.swing.JRadioButton();
        jRadioButton79 = new javax.swing.JRadioButton();
        jRadioButton80 = new javax.swing.JRadioButton();
        jRadioButton81 = new javax.swing.JRadioButton();
        jRadioButton82 = new javax.swing.JRadioButton();
        jRadioButton83 = new javax.swing.JRadioButton();
        jRadioButton84 = new javax.swing.JRadioButton();
        jRadioButton85 = new javax.swing.JRadioButton();
        jRadioButton86 = new javax.swing.JRadioButton();
        jRadioButton87 = new javax.swing.JRadioButton();
        jRadioButton88 = new javax.swing.JRadioButton();
        jRadioButton89 = new javax.swing.JRadioButton();
        jRadioButton90 = new javax.swing.JRadioButton();
        jRadioButton91 = new javax.swing.JRadioButton();
        jRadioButton92 = new javax.swing.JRadioButton();
        jRadioButton93 = new javax.swing.JRadioButton();
        jRadioButton94 = new javax.swing.JRadioButton();
        jRadioButton95 = new javax.swing.JRadioButton();
        jRadioButton96 = new javax.swing.JRadioButton();
        jRadioButton97 = new javax.swing.JRadioButton();
        jRadioButton98 = new javax.swing.JRadioButton();
        jRadioButton99 = new javax.swing.JRadioButton();
        jRadioButton100 = new javax.swing.JRadioButton();
        jRadioButton101 = new javax.swing.JRadioButton();
        jRadioButton102 = new javax.swing.JRadioButton();
        jRadioButton103 = new javax.swing.JRadioButton();
        jRadioButton104 = new javax.swing.JRadioButton();

        setLayout(new java.awt.BorderLayout());

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("Qüestionari SF-12 sobre l'Estat de Salut");

        jLabel14.setText("<html><b>INSTRUCCIONS:</b> Les preguntes que segueixen es refereixen al que vostè pensa sobre la seva salut. <br> Les seves respostes permetran saber com es troba vostè i fins a quin punt és capaç de fer les seves activitats habituals. <br> Si us plau, contesti cada pregunta marcant una casella. Si no està segur/a  de com respondre una pregunta, si us plau, contesti el que li sembli més cert.");

        jLabel15.setText("<html><b>1.</b> En general, vostè diria que la seva salut és:");

        jLabel34.setText("<html><b>Les següents preguntes es refereixen a activitats o coses que vostè podria fer en un dia normal.<br>La seva salut el limita per fer aquestes activitats o coses? Si és així, quant?");

        jLabel35.setText("<html><b>2.</b> Esforços moderats, com moure una taula, passar<br>l'aspiradora, jugar a bitlles o caminar més d'una hora");

        jLabel12.setText("<html><center>Sí, em limita<br>molt");

        jLabel13.setText("<html><center>Sí, em limita<br>una mica");

        jLabel36.setText("<html><center>no, no em<br>limita gens");

        jLabel37.setText("<html><b>3.</b> Pujar diversos pisos per l'escala");

        jLabel38.setText("<html><b>Durant les 4 últimes setmanes, ha tingut algun dels següents problemes a la seva feina o en les seves activitats<br>quotidianes a causa de la seva salut física?");

        jLabel39.setText("<html><b>4.</b> Va fer menys del que hauria volgut fer?");

        jLabel40.setText("Sí");

        jLabel41.setText("No");

        jLabel42.setText("<html><b>5.</b> Va haver de deixar de fer algunes tasques a la feina<br>o en les seves activitat quotidianes?");

        jLabel43.setText("<html><b>Durant les 4 últimes setmanes, ha tingut algun dels següents problemes a la seva feina o en les seves activitats<br>quotidianes a causa d'algun problema emocional (com estar trist, deprimit o nerviós)?");

        jLabel44.setText("<html><b>6.</b> Va fer menys del que hauria volgut fer per algun problema emocional?");

        jLabel45.setText("<html><b>7.</b> No va fer la seva feina o les seves activitats quotidianes tan cuidadosament<br>com de costum per algun problema emocional?");

        jLabel46.setText("<html><b>8.</b> Durant les 4 últimes setmanes, fins a quin punt el mal li ha dificultat<br>fer la seva feina (inclòs la feina fora de casa i tasques quotidianes)?");

        jLabel47.setText("Sí");

        jLabel48.setText("No");

        jLabel49.setText("Res");

        jLabel50.setText("Una mica");

        jLabel51.setText("Regular");

        jLabel52.setText("Bastant");

        jLabel78.setText("Molt");

        jLabel79.setText("<html><b>Les preguntes que segueixen es refereixen a com s'ha sentit i com li han anat les coses durant les últimes 4 setmanes.<br>En cada pregunta respongui el que se sembli més a com s'ha sentit vosté. Durant les últimes 4 setmanes, quant temps...");

        jLabel80.setText("<html><b>9.</b> ... es va sentir calmat i tranquil?");

        jLabel81.setText("<html><b>10.</b> ... va tenir molta energia?");

        jLabel82.setText("<html><b>11.</b> ... es va sentir desanimat i trist?");

        jLabel94.setText("<html><b>12.</b> Amb quina freqüència la salut física<br>o els problemes emocionals li han<br>dificultat les seves activitats socials<br>(com visitar els amics o familiars)?");

        jLabel103.setText("Sempre");

        jLabel105.setText("<html><center>Gairebé<br>sempre");

        jLabel108.setText("<html><center>Moltes<br>vegades");

        jLabel110.setText("<html><center>Algunes<br>vegades");

        jLabel116.setText("<html><center>Només<br>alguna vegada");

        jLabel125.setText("Mai");

        jLabel126.setText("<html><b>NOTA:</b> Transcriure en full de seguiment les 12 puntuacions corresponents a les respostes a cada ítem.");

        jLabel142.setText("Puntuació total:");

        jLabel146.setText("Excel·lent");

        jLabel147.setText("Molt bona");

        jLabel148.setText("Bona");

        jLabel175.setText("Regular");

        jLabel176.setText("Dolenta");

        sf12Total.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sf12Total.setText("0");

        sf12BtnGroup6.add(jRadioButton53);
        jRadioButton53.setText("1");

        sf12BtnGroup6.add(jRadioButton54);
        jRadioButton54.setText("2");

        sf12BtnGroup1.add(jRadioButton55);
        jRadioButton55.setText("1");

        sf12BtnGroup1.add(jRadioButton56);
        jRadioButton56.setText("2");

        sf12BtnGroup1.add(jRadioButton57);
        jRadioButton57.setText("3");

        sf12BtnGroup1.add(jRadioButton58);
        jRadioButton58.setText("4");

        sf12BtnGroup1.add(jRadioButton59);
        jRadioButton59.setText("5");

        sf12BtnGroup2.add(jRadioButton60);
        jRadioButton60.setText("1");

        sf12BtnGroup3.add(jRadioButton65);
        jRadioButton65.setText("1");

        sf12BtnGroup3.add(jRadioButton66);
        jRadioButton66.setText("2");

        sf12BtnGroup2.add(jRadioButton67);
        jRadioButton67.setText("2");

        sf12BtnGroup2.add(jRadioButton68);
        jRadioButton68.setText("3");

        sf12BtnGroup3.add(jRadioButton69);
        jRadioButton69.setText("3");

        sf12BtnGroup4.add(jRadioButton70);
        jRadioButton70.setText("1");

        sf12BtnGroup4.add(jRadioButton71);
        jRadioButton71.setText("2");

        sf12BtnGroup5.add(jRadioButton72);
        jRadioButton72.setText("1");

        sf12BtnGroup5.add(jRadioButton73);
        jRadioButton73.setText("2");

        sf12BtnGroup7.add(jRadioButton74);
        jRadioButton74.setText("1");

        sf12BtnGroup7.add(jRadioButton75);
        jRadioButton75.setText("2");

        sf12BtnGroup8.add(jRadioButton76);
        jRadioButton76.setText("1");

        sf12BtnGroup8.add(jRadioButton77);
        jRadioButton77.setText("2");

        sf12BtnGroup8.add(jRadioButton78);
        jRadioButton78.setText("3");

        sf12BtnGroup8.add(jRadioButton79);
        jRadioButton79.setText("4");

        sf12BtnGroup8.add(jRadioButton80);
        jRadioButton80.setText("5");

        sf12BtnGroup9.add(jRadioButton81);
        jRadioButton81.setText("1");

        sf12BtnGroup10.add(jRadioButton82);
        jRadioButton82.setText("1");

        sf12BtnGroup11.add(jRadioButton83);
        jRadioButton83.setText("1");

        sf12BtnGroup11.add(jRadioButton84);
        jRadioButton84.setText("2");

        sf12BtnGroup10.add(jRadioButton85);
        jRadioButton85.setText("2");

        sf12BtnGroup9.add(jRadioButton86);
        jRadioButton86.setText("2");

        sf12BtnGroup9.add(jRadioButton87);
        jRadioButton87.setText("3");

        sf12BtnGroup10.add(jRadioButton88);
        jRadioButton88.setText("3");

        sf12BtnGroup11.add(jRadioButton89);
        jRadioButton89.setText("3");

        sf12BtnGroup9.add(jRadioButton90);
        jRadioButton90.setText("4");

        sf12BtnGroup10.add(jRadioButton91);
        jRadioButton91.setText("4");

        sf12BtnGroup11.add(jRadioButton92);
        jRadioButton92.setText("4");

        sf12BtnGroup9.add(jRadioButton93);
        jRadioButton93.setText("5");

        sf12BtnGroup10.add(jRadioButton94);
        jRadioButton94.setText("5");

        sf12BtnGroup11.add(jRadioButton95);
        jRadioButton95.setText("5");

        sf12BtnGroup9.add(jRadioButton96);
        jRadioButton96.setText("6");

        sf12BtnGroup10.add(jRadioButton97);
        jRadioButton97.setText("6");

        sf12BtnGroup11.add(jRadioButton98);
        jRadioButton98.setText("6");

        sf12BtnGroup12.add(jRadioButton99);
        jRadioButton99.setText("1");

        sf12BtnGroup12.add(jRadioButton100);
        jRadioButton100.setText("2");

        sf12BtnGroup12.add(jRadioButton101);
        jRadioButton101.setText("3");

        sf12BtnGroup12.add(jRadioButton102);
        jRadioButton102.setText("4");

        sf12BtnGroup12.add(jRadioButton103);
        jRadioButton103.setText("5");

        sf12BtnGroup12.add(jRadioButton104);
        jRadioButton104.setText("6");

        javax.swing.GroupLayout sf12PanelLayout = new javax.swing.GroupLayout(sf12Panel);
        sf12Panel.setLayout(sf12PanelLayout);
        sf12PanelLayout.setHorizontalGroup(
            sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sf12PanelLayout.createSequentialGroup()
                .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sf12PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addGroup(sf12PanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(sf12PanelLayout.createSequentialGroup()
                                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(sf12PanelLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jRadioButton65)
                                                    .addComponent(jRadioButton60))))
                                        .addGap(18, 18, 18)
                                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(sf12PanelLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jRadioButton67)
                                                    .addComponent(jRadioButton66))))
                                        .addGap(18, 18, 18)
                                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(sf12PanelLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jRadioButton69)
                                                    .addComponent(jRadioButton68)))))
                                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(sf12PanelLayout.createSequentialGroup()
                                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sf12PanelLayout.createSequentialGroup()
                                                    .addComponent(jLabel40)
                                                    .addGap(14, 14, 14))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sf12PanelLayout.createSequentialGroup()
                                                    .addComponent(jRadioButton70)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                            .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jRadioButton71)
                                                .addGroup(sf12PanelLayout.createSequentialGroup()
                                                    .addGap(8, 8, 8)
                                                    .addComponent(jLabel41))))
                                        .addGroup(sf12PanelLayout.createSequentialGroup()
                                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadioButton72)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jRadioButton73)))
                                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(sf12PanelLayout.createSequentialGroup()
                                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel126, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(sf12PanelLayout.createSequentialGroup()
                                                .addComponent(jLabel142)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sf12Total))
                                            .addGroup(sf12PanelLayout.createSequentialGroup()
                                                .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(sf12PanelLayout.createSequentialGroup()
                                                        .addComponent(jLabel94, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jRadioButton99)
                                                        .addGap(26, 26, 26)
                                                        .addComponent(jRadioButton100)))
                                                .addGap(24, 24, 24)
                                                .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jRadioButton87)
                                                    .addComponent(jRadioButton88)
                                                    .addComponent(jRadioButton89)
                                                    .addComponent(jRadioButton101))
                                                .addGap(28, 28, 28)
                                                .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(sf12PanelLayout.createSequentialGroup()
                                                        .addComponent(jRadioButton102)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jRadioButton103))
                                                    .addGroup(sf12PanelLayout.createSequentialGroup()
                                                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jRadioButton90)
                                                            .addComponent(jRadioButton91)
                                                            .addComponent(jRadioButton92))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jRadioButton93)
                                                            .addComponent(jRadioButton94)
                                                            .addComponent(jRadioButton95))))))
                                        .addGap(35, 35, 35)
                                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton96)
                                            .addComponent(jRadioButton97)
                                            .addComponent(jRadioButton98)
                                            .addComponent(jRadioButton104)))
                                    .addGroup(sf12PanelLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel146)
                                            .addGroup(sf12PanelLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jRadioButton55)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel147)
                                            .addGroup(sf12PanelLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jRadioButton56)))
                                        .addGap(18, 18, 18)
                                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel148)
                                            .addComponent(jRadioButton57))
                                        .addGap(18, 18, 18)
                                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton58)
                                            .addComponent(jLabel175))
                                        .addGap(25, 25, 25)
                                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel176)
                                            .addComponent(jRadioButton59)))
                                    .addGroup(sf12PanelLayout.createSequentialGroup()
                                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(sf12PanelLayout.createSequentialGroup()
                                                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel49)
                                                .addGap(31, 31, 31)
                                                .addComponent(jLabel50)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel51))
                                            .addGroup(sf12PanelLayout.createSequentialGroup()
                                                .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(sf12PanelLayout.createSequentialGroup()
                                                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(48, 48, 48))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sf12PanelLayout.createSequentialGroup()
                                                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jRadioButton76)
                                                            .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)))
                                                .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(sf12PanelLayout.createSequentialGroup()
                                                        .addComponent(jRadioButton74)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jRadioButton75))
                                                    .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sf12PanelLayout.createSequentialGroup()
                                                            .addGap(9, 9, 9)
                                                            .addComponent(jLabel47)
                                                            .addGap(26, 26, 26)
                                                            .addComponent(jLabel48))
                                                        .addGroup(sf12PanelLayout.createSequentialGroup()
                                                            .addComponent(jRadioButton53)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(jRadioButton54)
                                                            .addGap(16, 16, 16)))
                                                    .addGroup(sf12PanelLayout.createSequentialGroup()
                                                        .addGap(6, 6, 6)
                                                        .addComponent(jRadioButton77)
                                                        .addGap(31, 31, 31)
                                                        .addComponent(jRadioButton78)))))
                                        .addGap(18, 18, 18)
                                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(sf12PanelLayout.createSequentialGroup()
                                                .addComponent(jLabel52)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel78))
                                            .addGroup(sf12PanelLayout.createSequentialGroup()
                                                .addComponent(jRadioButton79)
                                                .addGap(18, 18, 18)
                                                .addComponent(jRadioButton80))))))))
                    .addGroup(sf12PanelLayout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel103)
                            .addComponent(jRadioButton81)
                            .addComponent(jRadioButton82)
                            .addComponent(jRadioButton83))
                        .addGap(18, 18, 18)
                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel105, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton86)
                            .addComponent(jRadioButton85)
                            .addComponent(jRadioButton84))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel108, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel110, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel116, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel125)))
                .addContainerGap())
        );
        sf12PanelLayout.setVerticalGroup(
            sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sf12PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel146)
                    .addComponent(jLabel147)
                    .addComponent(jLabel148)
                    .addComponent(jLabel175)
                    .addComponent(jLabel176))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sf12PanelLayout.createSequentialGroup()
                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton55)
                            .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButton56)
                                .addComponent(jRadioButton57)
                                .addComponent(jRadioButton58)
                                .addComponent(jRadioButton59)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(sf12PanelLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jRadioButton60)
                                        .addComponent(jRadioButton67)
                                        .addComponent(jRadioButton68))))
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sf12PanelLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButton65)
                            .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButton66)
                                .addComponent(jRadioButton69)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel40)
                            .addComponent(jLabel41))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton70)
                            .addComponent(jRadioButton71))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton72)
                            .addComponent(jRadioButton73))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sf12PanelLayout.createSequentialGroup()
                                .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel47)
                                    .addComponent(jLabel48))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton53)
                                    .addComponent(jRadioButton54))
                                .addGap(18, 18, 18)
                                .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton74)
                                    .addComponent(jRadioButton75))
                                .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(sf12PanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(sf12PanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(sf12PanelLayout.createSequentialGroup()
                                                .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel50)
                                                    .addComponent(jLabel51))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jRadioButton76)
                                                    .addComponent(jRadioButton77)))
                                            .addComponent(jLabel49)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sf12PanelLayout.createSequentialGroup()
                                .addComponent(jLabel52)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton78))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sf12PanelLayout.createSequentialGroup()
                                .addComponent(jLabel78)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton79)
                                    .addComponent(jRadioButton80))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel105, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel108, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel110, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel116, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel125))
                            .addComponent(jLabel103))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sf12PanelLayout.createSequentialGroup()
                                .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(sf12PanelLayout.createSequentialGroup()
                                            .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jRadioButton81))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jRadioButton82))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel82, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jRadioButton83)))
                                        .addGroup(sf12PanelLayout.createSequentialGroup()
                                            .addComponent(jRadioButton86)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jRadioButton85)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jRadioButton84)))
                                    .addGroup(sf12PanelLayout.createSequentialGroup()
                                        .addComponent(jRadioButton90)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton91)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton92))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sf12PanelLayout.createSequentialGroup()
                                        .addComponent(jRadioButton93)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton94)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton95))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sf12PanelLayout.createSequentialGroup()
                                        .addComponent(jRadioButton96)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton97)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton98)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel94, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jRadioButton99)
                                        .addComponent(jRadioButton100)
                                        .addComponent(jRadioButton101)
                                        .addComponent(jRadioButton102)
                                        .addComponent(jRadioButton103)
                                        .addComponent(jRadioButton104)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel126, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sf12PanelLayout.createSequentialGroup()
                                .addComponent(jRadioButton87)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton88)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton89))))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(sf12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel142)
                    .addComponent(sf12Total))
                .addContainerGap())
        );

        sf12Scroll.setViewportView(sf12Panel);

        add(sf12Scroll, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel175;
    private javax.swing.JLabel jLabel176;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JRadioButton jRadioButton100;
    private javax.swing.JRadioButton jRadioButton101;
    private javax.swing.JRadioButton jRadioButton102;
    private javax.swing.JRadioButton jRadioButton103;
    private javax.swing.JRadioButton jRadioButton104;
    private javax.swing.JRadioButton jRadioButton53;
    private javax.swing.JRadioButton jRadioButton54;
    private javax.swing.JRadioButton jRadioButton55;
    private javax.swing.JRadioButton jRadioButton56;
    private javax.swing.JRadioButton jRadioButton57;
    private javax.swing.JRadioButton jRadioButton58;
    private javax.swing.JRadioButton jRadioButton59;
    private javax.swing.JRadioButton jRadioButton60;
    private javax.swing.JRadioButton jRadioButton65;
    private javax.swing.JRadioButton jRadioButton66;
    private javax.swing.JRadioButton jRadioButton67;
    private javax.swing.JRadioButton jRadioButton68;
    private javax.swing.JRadioButton jRadioButton69;
    private javax.swing.JRadioButton jRadioButton70;
    private javax.swing.JRadioButton jRadioButton71;
    private javax.swing.JRadioButton jRadioButton72;
    private javax.swing.JRadioButton jRadioButton73;
    private javax.swing.JRadioButton jRadioButton74;
    private javax.swing.JRadioButton jRadioButton75;
    private javax.swing.JRadioButton jRadioButton76;
    private javax.swing.JRadioButton jRadioButton77;
    private javax.swing.JRadioButton jRadioButton78;
    private javax.swing.JRadioButton jRadioButton79;
    private javax.swing.JRadioButton jRadioButton80;
    private javax.swing.JRadioButton jRadioButton81;
    private javax.swing.JRadioButton jRadioButton82;
    private javax.swing.JRadioButton jRadioButton83;
    private javax.swing.JRadioButton jRadioButton84;
    private javax.swing.JRadioButton jRadioButton85;
    private javax.swing.JRadioButton jRadioButton86;
    private javax.swing.JRadioButton jRadioButton87;
    private javax.swing.JRadioButton jRadioButton88;
    private javax.swing.JRadioButton jRadioButton89;
    private javax.swing.JRadioButton jRadioButton90;
    private javax.swing.JRadioButton jRadioButton91;
    private javax.swing.JRadioButton jRadioButton92;
    private javax.swing.JRadioButton jRadioButton93;
    private javax.swing.JRadioButton jRadioButton94;
    private javax.swing.JRadioButton jRadioButton95;
    private javax.swing.JRadioButton jRadioButton96;
    private javax.swing.JRadioButton jRadioButton97;
    private javax.swing.JRadioButton jRadioButton98;
    private javax.swing.JRadioButton jRadioButton99;
    private javax.swing.ButtonGroup sf12BtnGroup1;
    private javax.swing.ButtonGroup sf12BtnGroup10;
    private javax.swing.ButtonGroup sf12BtnGroup11;
    private javax.swing.ButtonGroup sf12BtnGroup12;
    private javax.swing.ButtonGroup sf12BtnGroup2;
    private javax.swing.ButtonGroup sf12BtnGroup3;
    private javax.swing.ButtonGroup sf12BtnGroup4;
    private javax.swing.ButtonGroup sf12BtnGroup5;
    private javax.swing.ButtonGroup sf12BtnGroup6;
    private javax.swing.ButtonGroup sf12BtnGroup7;
    private javax.swing.ButtonGroup sf12BtnGroup8;
    private javax.swing.ButtonGroup sf12BtnGroup9;
    private javax.swing.JPanel sf12Panel;
    private javax.swing.JScrollPane sf12Scroll;
    private javax.swing.JLabel sf12Total;
    // End of variables declaration//GEN-END:variables
}
