/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import model.Evaluador;
import controlador.Utils;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author USER
 */
public class NewUser extends javax.swing.JDialog {

    ArrayList<Evaluador> llistaEvaluadors;
    Evaluador eva;
    
    /**
     * Creates new form newUser
     */
    public NewUser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Utils.setIcon((JFrame)this.getOwner());
        this.setLocationRelativeTo(null);
        this.modificaBtn.setVisible(false);
        this.eliminaBtn.setVisible(false);
    }
    
    public NewUser(java.awt.Frame parent, boolean modal, ArrayList<Evaluador> llistaEvaluadors, Evaluador eva) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.eva = eva;
        this.llistaEvaluadors = llistaEvaluadors;
        this.newBtn.setVisible(false);
        
        this.idTextBox.setText(eva.getId());
        this.nameTextBox.setText(eva.getNom());
        this.passTextBox.setText(eva.getPassword());
        this.pass2TextBox.setText(eva.getPassword());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameTextBox = new javax.swing.JTextField();
        idTextBox = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        newBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        passTextBox = new javax.swing.JPasswordField();
        pass2TextBox = new javax.swing.JPasswordField();
        eliminaBtn = new javax.swing.JButton();
        modificaBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edita evaluador");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nou Usuari"));

        jLabel1.setText("Nom:");

        idLabel.setText("ID:");

        jLabel3.setText("Contrasenya:");

        jLabel4.setText("Repeteix contrasenya:");

        newBtn.setText("Crea");
        newBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancelar");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        eliminaBtn.setText("Elimina");
        eliminaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaBtnActionPerformed(evt);
            }
        });

        modificaBtn.setText("Modifica");
        modificaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(idTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(132, 132, 132))
                            .addComponent(nameTextBox)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passTextBox)
                                    .addComponent(pass2TextBox)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(modificaBtn)
                                .addGap(8, 8, 8)
                                .addComponent(eliminaBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(newBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelBtn)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idLabel)
                    .addComponent(idTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pass2TextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newBtn)
                    .addComponent(eliminaBtn)
                    .addComponent(cancelBtn)
                    .addComponent(modificaBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void newBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBtnActionPerformed

        JSONObject obj = null;
        try {
            obj = new JSONObject(getStringFile(Utils.USERS_PATH));
            JSONArray users = obj.getJSONArray("Users");
            int i = 0;
            boolean trobat = false;
            while ( i < users.length() && !trobat){
                if (users.getJSONObject(i).getString("name").equals(nameTextBox.getText())){
                    trobat = true;
                }
                i++;
            }
            boolean buits, pass;
            buits = "".equals(idTextBox.getText()) || "".equals(nameTextBox.getText()) || "".equals(passTextBox.getText()) || "".equals(pass2TextBox.getText());
            pass = !passTextBox.getText().equals(pass2TextBox.getText());
            if (trobat || buits || pass){
                if (buits) System.out.println("Has d'omplir tots els buits");
                else if(trobat) System.out.println("Nom ja utilitzat");
                else if(pass)System.out.println("Les contrasenyes no coincideixen");
            } else{
                JSONArray usr = new JSONArray();
                for (i = 0; i < users.length(); i++){
                    usr.put(users.getJSONObject(i));
                }
                
                JSONObject o = new JSONObject();
                o.put("id",idTextBox.getText());
                o.put("name", nameTextBox.getText().toLowerCase());
                o.put("password", passTextBox.getText());
                o.put("role","evaluador");
                
                usr.put(o);
                
                obj.put("Users", usr);
                PrintWriter out = new PrintWriter(Utils.USERS_PATH);
                out.write(obj.toString());
                out.close();
                this.dispose();
            }

            
        } catch (JSONException ex) {
            Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
        }
  
    }//GEN-LAST:event_newBtnActionPerformed

    private void modificaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificaBtnActionPerformed
        boolean idTrobat = false, nomTrobat = false;
        for (Evaluador e : llistaEvaluadors){
            if (e.getNom().equals(nameTextBox.getText()) && !e.getNom().equals(eva.getNom())){
                nomTrobat = true;
            }
            if (e.getId().equals(idTextBox.getText()) && !e.getId().equals(eva.getId()) ){
                idTrobat = true;
            }
        }
        boolean buits, pass;
        buits = "".equals(idTextBox.getText()) || "".equals(nameTextBox.getText()) || "".equals(passTextBox.getText()) || "".equals(pass2TextBox.getText());
        pass = !passTextBox.getText().equals(pass2TextBox.getText());
        if (nomTrobat || idTrobat || buits || pass){
            if (buits) System.out.println("Has d'omplir tots els buits");
            else if(nomTrobat) System.out.println("Nom ja utilitzat");
            else if(idTrobat) System.out.println("ID ja utilitzat");
            else if(pass)System.out.println("Les contrasenyes no coincideixen");
        } 
        else{
            eva.setId(idTextBox.getText());
            eva.setNom(nameTextBox.getText());
            eva.setPassword(passTextBox.getText());
            guardarJSON();
            this.dispose();
        }
    }//GEN-LAST:event_modificaBtnActionPerformed

    private void eliminaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaBtnActionPerformed
        llistaEvaluadors.remove(eva);
        guardarJSON();
        this.dispose();
    }//GEN-LAST:event_eliminaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewUser dialog = new NewUser(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private static String getStringFile(String file) {
	BufferedReader reader = null;
	try {
	    reader = new BufferedReader( new FileReader (file));
	    String line;
	    StringBuilder stringBuilder = new StringBuilder();
	    String ls = System.getProperty("line.separator");
	    while( ( line = reader.readLine() ) != null ) {
		stringBuilder.append( line );
		stringBuilder.append( ls );
	    }
	    return stringBuilder.toString();
	} catch (FileNotFoundException ex) {
	    Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
	} catch (IOException ex) {
	    Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
	} finally {
	    try {
		if(reader != null)
		    reader.close();
	    } catch (IOException ex) {
		Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
	    }
	}
	return null;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton eliminaBtn;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idTextBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modificaBtn;
    private javax.swing.JTextField nameTextBox;
    private javax.swing.JButton newBtn;
    private javax.swing.JPasswordField pass2TextBox;
    private javax.swing.JPasswordField passTextBox;
    // End of variables declaration//GEN-END:variables

    private void guardarJSON() {
        JSONArray usr = new JSONArray();
        JSONObject obj = new JSONObject();
        
        getUsers(usr);
        
        for (Evaluador e : llistaEvaluadors){
            try {
                    usr.put(e.toJSON());
            } catch (JSONException ex) {
                Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        try {
            obj.put("Users", usr);
        } catch (JSONException ex) {
            Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        PrintWriter out = null;
        try {
            out = new PrintWriter(Utils.USERS_PATH);
            out.write(obj.toString());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            out.close();
        }
    }

    private void getUsers(JSONArray u) {
        JSONObject obj;
        try {
            obj = new JSONObject(Utils.getStringFile(Utils.USERS_PATH));
            JSONArray users = obj.getJSONArray("Users");
            for (int i=0; i<users.length();i++){
                if (!users.getJSONObject(i).getString("role").equals("evaluador")){
                    u.put(users.getJSONObject(i));
                }
            }
        } catch (JSONException ex) {
            Logger.getLogger(NewUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
