/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import model.Pacient;
import controlador.Utils;

import java.awt.*;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.util.Properties;

import vista.tests.*;

/**
 *
 * @author USER
 */
public class ValoracioCuidador extends javax.swing.JFrame {

    private String valoracio;
    Pacient pacientActual;
    Frame parent;

    public ValoracioCuidador(){
        initComponents();
    }

    /**
     * Creates new form ValoracioCuidador
     */
    public ValoracioCuidador(Frame parent, Pacient pacient, String valoracio) {
        Utils.setIcon(this);

        this.parent = parent;
        
        initComponents();

        pacientActual = pacient;

        this.valoracio = valoracio;

        this.setTitle(this.getTitle()+" | T"+valoracio);
        
        addTabs();

        Utils.carregar(tabbedPanel,pacientActual.getId(), "ValCuid_T"+valoracio);

        Utils.setActionCommands(dataPanel);
    }
    
    private void addTabs() {
        NPI npi = new NPI(pacientActual);
        tabbedPanel.addTab(npi.getLabel(), npi);

        HAD had = new HAD(pacientActual);
        tabbedPanel.addTab(had.getLabel(), had);

        ZARIT zarit = new ZARIT(pacientActual);
        tabbedPanel.addTab(zarit.getLabel(), zarit);
        
        SF12 sf12 = new SF12(pacientActual);
        tabbedPanel.addTab(sf12.getLabel(), sf12);
        
        DUKE duke = new DUKE(pacientActual);
        tabbedPanel.addTab(duke.getLabel(), duke);
        
        FAQ faq = new FAQ(pacientActual);
        tabbedPanel.addTab(faq.getLabel(), faq);
        
        OHQSF ohqsf = new OHQSF(pacientActual);
        tabbedPanel.addTab(ohqsf.getLabel(), ohqsf);
    }
    
    private void guardarResultats(){
        Properties prop = new Properties();
	OutputStream output = null;

	try {

        File f = new File(Utils.PACIENT_DATA_PATH+pacientActual.getId()+File.separator);
        if (!f.exists()){
            f.mkdir();
        }
        File file = new File(Utils.PACIENT_DATA_PATH+pacientActual.getId()+File.separator+"resultsValCuid_T"+valoracio+".dat");

        output = new FileOutputStream(file);



        prop.store(output, "NEUROIMATGE");

	} catch (IOException io) {
		io.printStackTrace();
        } finally {
            if (output != null) {
		try {
                    output.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        dataPanel = new javax.swing.JPanel();
        tabbedPanel = new javax.swing.JTabbedPane();
        buttonPanel = new javax.swing.JPanel();
        acceptaBtn = new javax.swing.JButton();
        cancelaBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Valoració cuidador");

        mainPanel.setLayout(new java.awt.BorderLayout());

        dataPanel.setLayout(new java.awt.BorderLayout());

        tabbedPanel.setToolTipText("");
        tabbedPanel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dataPanel.add(tabbedPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(dataPanel, java.awt.BorderLayout.CENTER);

        acceptaBtn.setText("Accepta");
        acceptaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptaBtnActionPerformed(evt);
            }
        });

        cancelaBtn.setText("Cancel·la");
        cancelaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap(6240, Short.MAX_VALUE)
                .addComponent(acceptaBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelaBtn)
                .addContainerGap())
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acceptaBtn)
                    .addComponent(cancelaBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(buttonPanel, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptaBtnActionPerformed
        Utils.guardar(tabbedPanel,pacientActual.getId(), "ValCuid_T"+valoracio);
        guardarResultats();
        Utils.generaResultatsCSV(pacientActual.getId());
        ((MenuAvaluador)parent).checkCsv();
        //((MenuAvaluador)parent).checkCsvTotal();
        this.dispose();
    }//GEN-LAST:event_acceptaBtnActionPerformed

    private void cancelaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelaBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValoracioCuidador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValoracioCuidador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValoracioCuidador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValoracioCuidador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValoracioCuidador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptaBtn;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelaBtn;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTabbedPane tabbedPanel;
    // End of variables declaration//GEN-END:variables
}
